#!/usr/bin/env python3
"""Merge Discord environment variables into main .env file"""

import os
import re
from pathlib import Path

def merge_env_files():
    """Merge Discord environment variables into main .env file"""

    env_file = Path('.env')
    discord_env_file = Path('.env.discord')

    if not discord_env_file.exists():
        print("❌ .env.discord file not found")
        return False

    # Read Discord environment variables
    discord_vars = {}
    try:
        with open(discord_env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    match = re.match(r'^([^=]+)=(.*)$', line)
                    if match:
                        key, value = match.groups()
                        key = key.strip()
                        value = value.strip().strip('"').strip("'")
                        discord_vars[key] = value
    except Exception as e:
        print(f"❌ Error reading .env.discord: {e}")
        return False

    print(f"📋 Found {len(discord_vars)} Discord environment variables to merge")

    # Read existing .env file or create new one
    existing_content = ""
    if env_file.exists():
        try:
            with open(env_file, 'r') as f:
                existing_content = f.read()
            print("✅ Found existing .env file")
        except Exception as e:
            print(f"⚠️  Could not read existing .env file: {e}")
    else:
        print("📄 Creating new .env file")

    # Check for existing Discord variables and update or add them
    lines = existing_content.split('\n') if existing_content else []
    updated_lines = []
    discord_vars_added = set()

    # Process existing lines
    for line in lines:
        line = line.rstrip()
        if '=' in line and not line.startswith('#'):
            key = line.split('=', 1)[0].strip()
            if key in discord_vars:
                # Replace with Discord value
                updated_lines.append(f'{key}="{discord_vars[key]}"')
                discord_vars_added.add(key)
                print(f"🔄 Updated: {key}")
            else:
                updated_lines.append(line)
        else:
            updated_lines.append(line)

    # Add any remaining Discord variables
    if discord_vars_added:
        updated_lines.append("")  # Add blank line before Discord section
        updated_lines.append("# Discord Configuration - Auto-generated by Discord Manager")
        updated_lines.append(f"# Generated: {discord_vars.get('GENERATED_AT', 'Unknown')}")

    for key, value in discord_vars.items():
        if key not in discord_vars_added:
            updated_lines.append(f'{key}="{value}"')
            print(f"➕ Added: {key}")

    # Write back to .env file
    try:
        with open(env_file, 'w') as f:
            f.write('\n'.join(updated_lines))
            if updated_lines and not updated_lines[-1].endswith('\n'):
                f.write('\n')
        print(f"\n✅ Successfully merged Discord variables into {env_file}")
        return True
    except Exception as e:
        print(f"❌ Error writing to .env file: {e}")
        return False

def main():
    print("🔧 MERGING DISCORD ENVIRONMENT VARIABLES")
    print("=" * 50)

    if merge_env_files():
        print("\n🎉 Discord configuration permanently saved to .env file!")
        print("📝 Your application will now automatically load these variables")
        print("\n🧪 Test the configuration:")
        print("   python discord_bot_test.py")
        return True
    else:
        print("\n❌ Failed to merge environment variables")
        return False

if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)