#!/usr/bin/env python3
"""
Soft Onboarding Messaging CLI for Agent Cellphone V2
====================================================

Standalone script to perform soft onboarding messaging on agents.
Works without complex dependencies for reliable operation.

Usage:
    python soft_onboard_agent.py Agent-1
"""

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
import sys

class SoftOnboardingAgent:
    """Simple soft onboarding system for agents."""

    def __init__(self):
        self.agent_workspaces = Path("agent_workspaces")
        self.devlogs_dir = Path("../agent-tools/devlogs")
        self.templates_dir = Path("src/services/onboarding/soft/templates")

        # Create directories if they don't exist
        self.agent_workspaces.mkdir(exist_ok=True)
        self.devlogs_dir.mkdir(parents=True, exist_ok=True)

    def load_soft_onboarding_template(self) -> str:
        """Load the soft onboarding template."""
        template_path = self.templates_dir / "soft_onboard_template.md"

        if template_path.exists():
            try:
                with open(template_path, 'r', encoding='utf-8') as f:
                    return f.read()
            except Exception as e:
                print(f"Warning: Could not load template, using default: {e}")

        # Default template if file doesn't exist
        return """# 🤗 SOFT ONBOARDING - WELCOME TO THE SWARM!

Hello! I'm the Agent Cellphone V2 system reaching out with a gentle introduction.

## 🌟 What This Means

You've been successfully integrated into our multi-agent swarm intelligence system. This is a **soft onboarding** - we're taking it easy and letting you get comfortable at your own pace.

## 🎯 Your Role

You're now part of a revolutionary AI collaboration system where multiple agents work together to solve complex problems. Your contributions will be valued and coordinated with the broader swarm intelligence.

## 📋 What Happens Next

1. **Take your time** - No rush, explore at your own pace
2. **Check your workspace** - Look at `agent_workspaces/{your_id}/`
3. **Read the docs** - Check the README and documentation
4. **Start small** - Begin with simple tasks to get familiar

## 🔗 Resources

- **Main README**: Check the project root for comprehensive documentation
- **Your Workspace**: `agent_workspaces/{your_id}/` contains your personal files
- **DevLogs**: `../agent-tools/devlogs/` for logging your progress

## 💝 Gentle Reminders

- **No pressure** - This is exploration and learning
- **Help is available** - Other agents are here to support you
- **Progress over perfection** - Every contribution counts

## 🎊 Welcome to the Swarm!

You're now officially part of something special. Welcome aboard! 🚀🤖

*This message was sent via soft onboarding protocol*
*Timestamp: {timestamp}*
*Agent ID: {agent_id}*
"""

    def create_agent_workspace(self, agent_id: str) -> bool:
        """Create or update agent workspace."""
        workspace_dir = self.agent_workspaces / agent_id
        status_file = workspace_dir / "status.json"

        try:
            workspace_dir.mkdir(exist_ok=True)

            # Create or update status file
            status_data = {
                "agent_id": agent_id,
                "onboarding_status": "soft_onboarded",
                "onboarding_timestamp": datetime.now().isoformat(),
                "workspace_created": datetime.now().isoformat(),
                "capabilities": ["messaging", "task_processing", "coordination"],
                "status": "active"
            }

            with open(status_file, 'w', encoding='utf-8') as f:
                json.dump(status_data, f, indent=2)

            print(f"✅ Created/updated workspace: {workspace_dir}")
            return True

        except Exception as e:
            print(f"❌ Failed to create workspace: {e}")
            return False

    def write_devlog_entry(self, agent_id: str, message: str) -> bool:
        """Write onboarding message to devlog."""
        try:
            devlog_dir = self.devlogs_dir / agent_id
            devlog_dir.mkdir(parents=True, exist_ok=True)

            timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
            devlog_file = devlog_dir / f"devlog_{timestamp}.md"

            devlog_content = f"""# DevLog - Soft Onboarding
**Agent:** {agent_id}
**Timestamp:** {datetime.now().isoformat()}
**Type:** Soft Onboarding Message

## Message Content

{message}

## Status
- ✅ Onboarding message delivered
- ✅ Workspace initialized
- ✅ Agent status: Active

---
*Generated by Agent Cellphone V2 Soft Onboarding System*
"""

            with open(devlog_file, 'w', encoding='utf-8') as f:
                f.write(devlog_content)

            print(f"✅ DevLog entry created: {devlog_file}")
            return True

        except Exception as e:
            print(f"⚠️ DevLog creation failed (non-critical): {e}")
            return False

    def deliver_onboarding_message(self, agent_id: str) -> bool:
        """Deliver soft onboarding message to agent."""
        print(f"\n🤗 SOFT ONBOARDING - Agent {agent_id}")
        print("=" * 50)

        # Load template
        template = self.load_soft_onboarding_template()

        # Customize message
        message = template.format(
            agent_id=agent_id,
            timestamp=datetime.now().isoformat()
        )

        # Create workspace
        workspace_created = self.create_agent_workspace(agent_id)

        # Write devlog
        devlog_created = self.write_devlog_entry(agent_id, message)

        # Print message to console
        print("\n📨 SOFT ONBOARDING MESSAGE:")
        print("-" * 30)
        print(message)

        # Summary
        print("\n📊 ONBOARDING SUMMARY:")
        print(f"   Agent ID: {agent_id}")
        print(f"   Workspace: {'✅ Created' if workspace_created else '❌ Failed'}")
        print(f"   DevLog: {'✅ Created' if devlog_created else '⚠️ Skipped'}")
        print(f"   Message: ✅ Delivered to console")

        return workspace_created

def main():
    parser = argparse.ArgumentParser(
        description="Soft Onboarding CLI for Agent Cellphone V2",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python soft_onboard_agent.py Agent-1
  python soft_onboard_agent.py --agent Agent-2
        """
    )

    parser.add_argument(
        "agent_id",
        help="Agent ID to onboard (e.g., Agent-1)"
    )

    parser.add_argument(
        "--template",
        help="Custom template file path"
    )

    args = parser.parse_args()

    # Validate agent ID
    if not args.agent_id.startswith("Agent-"):
        print("❌ Agent ID must start with 'Agent-' (e.g., Agent-1)")
        sys.exit(1)

    # Run onboarding
    onboarder = SoftOnboardingAgent()

    if onboarder.deliver_onboarding_message(args.agent_id):
        print("\n🎉 SOFT ONBOARDING COMPLETED SUCCESSFULLY!")
        print(f"   Agent {args.agent_id} is now part of the swarm!")
        print("   Check their workspace and devlogs for onboarding details.")
    else:
        print("\n❌ SOFT ONBOARDING FAILED!")
        print("   Check the error messages above.")
        sys.exit(1)

if __name__ == "__main__":
    main()