groups:
- name: portfolio_platform_alerts
  rules:
  - alert: PortfolioHighResponseTime
    annotations:
      description: 95th percentile response time > 800ms for dadudekc.com
      summary: High response time on portfolio platform
    expr: http_request_duration_seconds{quantile='0.95', domain='dadudekc.com'} >
      0.8
    for: 5m
    labels:
      service: portfolio
      severity: warning
  - alert: PortfolioContactFormErrors
    annotations:
      description: Contact form errors > 5 in 5 minutes for dadudekc.com
      summary: High contact form error rate
    expr: portfolio_contact_form_errors_total{domain='dadudekc.com'} > 5
    for: 5m
    labels:
      service: portfolio
      severity: warning
  - alert: PortfolioDatabaseTimeouts
    annotations:
      description: 99th percentile DB query time > 5s for dadudekc.com
      summary: Portfolio database timeouts
    expr: portfolio_db_query_duration_seconds{quantile='0.99', domain='dadudekc.com'}
      > 5
    for: 2m
    labels:
      service: portfolio
      severity: critical
