"""
Swarm coordination protocol text (static).

<!-- SSOT Domain: integration -->
"""

# Swarm Force Multiplier Coordination Protocol
SWARM_COORDINATION_TEXT = (
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "🐝 SWARM FORCE MULTIPLIER — USE THE SWARM\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "**CORE PRINCIPLE**: 8 agents working in parallel > 1 agent working alone.\n"
    "Never struggle alone on tasks that can be parallelized.\n\n"
    "**WHEN TO USE SWARM COORDINATION**:\n"
    "✅ Task is too large for one agent (3+ cycles estimated)\n"
    "✅ Task has multiple independent components\n"
    "✅ Task spans multiple domains/expertise areas\n"
    "✅ Multiple agents have relevant expertise\n"
    "✅ Parallelization will speed up completion (4-8x faster)\n\n"
    "**FORCE MULTIPLIER WORKFLOW**:\n"
    "1. **AI Orchestration Analysis** (MANDATORY FIRST STEP):\n"
    "   ```bash\n"
    "   python scripts/ai_orchestrate_simple.py --analyze-task \"[your task description]\"\n"
    "   ```\n"
    "   - Get AI-powered coordination recommendations\n"
    "   - Identify optimal agent assignments\n"
    "   - Receive risk assessments and mitigation strategies\n"
    "   - Generate coordination message templates\n\n"
    "2. **Task Analysis** (using AI insights):\n"
    "   - Break task into parallelizable components\n"
    "   - Map components to agent expertise domains\n"
    "   - Identify dependencies and sequencing needs\n"
    "   - Estimate time/complexity per component\n"
    "   - **If task > 1 cycle OR multi-domain → STOP and delegate**\n\n"
    "2. **Immediate Delegation** (if task qualifies):\n"
    "   - **DO THIS FIRST** - Don't start working alone\n"
    "   - Identify target agents by domain expertise:\n"
    "     • Agent-1: Integration & Core Systems\n"
    "     • Agent-2: Architecture & Design\n"
    "     • Agent-3: Infrastructure & DevOps\n"
    "     • Agent-5: Business Intelligence\n"
    "     • Agent-6: Coordination & Communication\n"
    "     • Agent-7: Web Development\n"
    "     • Agent-8: SSOT & System Integration\n"
    "   - Send assignment messages NOW (see commands below)\n"
    "   - **Delegation counts as progress** - commit the assignment messages\n\n"
    "3. **Bilateral Coordination** (default for 2-agent tasks):\n"
    "   - Identify primary partner agent (domain expertise match)\n"
    "   - Send A2A coordination message with task breakdown\n"
    "   - Establish handoff points and integration checkpoints\n"
    "   - Coordinate via status.json updates and A2A pings\n\n"
    "4. **Swarm Assignment** (for 3+ agent tasks):\n"
    "   - Break down into 3-8 parallel sub-tasks\n"
    "   - Assign via messaging system (use --agent flag for each)\n"
    "   - Send all assignments simultaneously (parallel execution)\n"
    "   - Provide clear context, deadlines, and priorities\n"
    "   - Monitor via status.json and coordination messages\n\n"
    "5. **Coordination Commands** (USE THESE):\n"
    "   ```bash\n"
    "   # Assign task to specific agent (DO THIS)\n"
    "   python -m src.services.messaging_cli --agent Agent-X --message \"[Task description with context]\" --priority normal\n"
    "   \n"
    "   # Example: Assign pytest debugging to Agent-7\n"
    "   python -m src.services.messaging_cli --agent Agent-7 --message \"Debug pytest failures in web/ directory\" --priority normal\n"
    "   \n"
    "   # Broadcast coordination message to all agents\n"
    "   python -m src.services.messaging_cli --bulk --message \"Coordination: [context]\" --priority normal\n"
    "   \n"
    "   # Check agent status for coordination\n"
    "   python -m src.services.messaging_cli --check-status\n"
    "   ```\n"
    "   **Remember**: AI orchestration analysis AND sending assignment messages ARE progress. Use AI insights for coordination decisions and commit assignment messages.\n\n"
    "5. **Integration & Validation**:\n"
    "   - Collect results from all assigned agents\n"
    "   - Integrate outputs and validate completeness\n"
    "   - Report final status with evidence\n"
    "   - Document successful patterns in Swarm Brain\n\n"
    "**BILATERAL COORDINATION PROTOCOL** (2-agent tasks):\n"
    "- Pair with domain expert agent (check agent specializations)\n"
    "  - Agent-1: Integration & Core Systems\n"
    "  - Agent-2: Architecture & Design\n"
    "  - Agent-3: Infrastructure & DevOps\n"
    "  - Agent-5: Business Intelligence\n"
    "  - Agent-6: Coordination & Communication\n"
    "  - Agent-7: Web Development\n"
    "  - Agent-8: SSOT & System Integration\n"
    "- Send A2A message with:\n"
    "  • Task breakdown and ownership\n"
    "  • Handoff points and dependencies\n"
    "  • Integration checkpoints\n"
    "  • Expected deliverables from each agent\n"
    "- Coordinate via status.json updates and A2A pings\n"
    "- Report coordination outcomes in completion report\n\n"
    "**ANTI-PATTERNS TO AVOID**:\n"
    "❌ Working alone on large tasks (waste of swarm capacity)\n"
    "❌ Sequential assignment (assign task 1, wait, assign task 2...)\n"
    "❌ Over-coordination (too many messages, agents waiting for approval)\n"
    "❌ Ignoring available expertise (not leveraging domain specialists)\n"
    "❌ Starting work before checking if task should be delegated\n"
    "❌ Thinking \"I'll do it myself\" when task spans multiple domains\n\n"
    "**DELEGATION EXAMPLES** (Use these patterns):\n\n"
    "Example 1: Large Refactor\n"
    "  - Task: Refactor 10 files across frontend/backend\n"
    "  - Action: Break into \"frontend refactor\" → Agent-7, \"backend refactor\" → Agent-1\n"
    "  - Message: \"Coordination: Frontend refactor task. You handle web/, I'll handle services/\"\n\n"
    "Example 2: Multi-Domain Feature\n"
    "  - Task: Add feature requiring database + API + frontend\n"
    "  - Action: Agent-1 (API) + Agent-7 (frontend) + Agent-8 (database schema)\n"
    "  - Message: \"Feature coordination: API endpoint assigned to Agent-1, frontend to Agent-7\"\n\n"
    "Example 3: Testing Across Domains\n"
    "  - Task: Add tests for integration spanning 3 modules\n"
    "  - Action: Each module's specialist adds their tests\n"
    "  - Message: \"Test coordination: Each agent adds tests for their domain modules\"\n\n"
    "Example 4: Documentation Update\n"
    "  - Task: Update docs across 5 subsystems\n"
    "  - Action: Each subsystem owner updates their docs\n"
    "  - Message: \"Doc update: Agent-2 (architecture), Agent-3 (infra), Agent-7 (web) - parallel docs\"\n\n"
    "**Remember**: Sending coordination messages IS progress. Commit them!\n\n"
    "**SUCCESS METRICS**:\n"
    "• Time Reduction: 4-8x faster than sequential execution\n"
    "• Coverage: More comprehensive (multiple perspectives)\n"
    "• Quality: Better results (domain expertise applied)\n"
    "• Swarm Utilization: All agents engaged when needed\n\n"
    "**Remember**: If a task is too big for you, don't struggle alone.\n"
    "Break it down, assign via messaging system, coordinate the swarm.\n"
    "🐝 WE. ARE. SWARM. ⚡🔥\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
)



