"""
Operating cycle and checklist texts (static).

<!-- SSOT Domain: integration -->
"""

# Canonical operating cycle text for S2A messages.
AGENT_OPERATING_CYCLE_TEXT = (
    "Agent Operating Cycle (canonical):\n"
    "1) Claim\n"
    "2) Sync SSOT/context\n"
    "3) Slice\n"
    "4) Execute\n"
    "5) Validate\n"
    "6) Commit\n"
    "7) Report evidence\n"
)

# Cycle checklist to keep start/during/end behavior explicit
# Reference: docs/AGENT_OPERATING_CYCLE_WORKFLOW.md
CYCLE_CHECKLIST_TEXT = (
    "Cycle Checklist:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "CYCLE START:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Check inbox (priority: D2A → C2A → A2A)\n"
    "- Check Contract System (--get-next-task)\n"
    "- Check Swarm Brain (use MCP: search_swarm_knowledge) for relevant patterns/solutions (advisory only - see docs/governance/SWARM_BRAIN_POLICY.md)\n"
    "- Check MASTER_TASK_LOG.md (use MCP: get_tasks) for assigned tasks\n"
    "- 🔍 **FORCE MULTIPLIER ASSESSMENT (MANDATORY FIRST STEP)**:\n"
<<<<<<< HEAD
    "  - 🤖 **AI ORCHESTRATION CONSULTATION** (MANDATORY):\n"
    "    - Run: python scripts/ai_orchestrate_simple.py --analyze-task \"[task description]\"\n"
    "    - Get AI recommendations for task allocation and coordination strategy\n"
    "    - Factor AI insights into force multiplier decisions\n"
=======
>>>>>>> origin/codex/build-cross-platform-control-plane-for-swarm-console
    "  - Will this task take >1 cycle? → STOP, delegate parts to swarm\n"
    "  - Does this touch 2+ domains? → STOP, coordinate with domain experts\n"
    "  - Is another agent better suited? → STOP, message them to take over\n"
    "  - Can this be parallelized? → STOP, break down and assign to 2-4 agents\n"
    "  - ONLY if all answers are NO → proceed solo\n"
    "- Update status.json (status=ACTIVE, increment cycle_count)\n"
    "- Update FSM State\n"
    "- Review current mission\n"
    "\n"
    "❌ DO NOT: Add tasks to cycle planner here (unless urgent)\n"
    "❌ DO NOT: Message other agents here (unless urgent coordination needed)\n"
    "\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "DURING CYCLE:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "📋 PHASE 3: SLICE (Technical Implementation Planning):\n"
    "1. Start with explicit technical instructions (not general \"build this\")\n"
    "2. Request full technical implementation plan from AI first\n"
    "3. Vet the plan before execution\n"
    "4. Convert validated plan into detailed prompt for model\n"
    "5. Code review: Confirm implementation won't be spaghetti\n"
    "6. Ensure clean architecture patterns, not spaghetti code\n"
    "\n"
    "- Update status when phase changes\n"
    "- Update when tasks complete\n"
    "- Update if blocked\n"
    "- If new task identified → Use MCP: add_task_to_inbox(task, agent_id)\n"
    "- If task blocked → Use MCP: move_task_to_waiting(task_description, reason, agent_id)\n"
    "\n"
    "✅ MESSAGE OTHER AGENTS WHEN:\n"
    "- Task expands → Break down and coordinate (use A2A messaging)\n"
    "- Need domain expertise → Message domain specialist agent\n"
    "- Cross-domain work → Message relevant agents for coordination\n"
    "- 75-80% complete → Send \"gas\" to next agent in sequence (pipeline continuity)\n"
    "- Blocked → Message for help or escalate to Captain\n"
    "- Force multiplier opportunity → Break down and assign to swarm\n"
    "\n"
    "❌ DO NOT: Add tasks to cycle planner here (unless new work identified)\n"
    "\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "CYCLE END:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Update completed_tasks\n"
    "- Update next_actions\n"
    "\n"
    "✅ UPDATE MASTER_TASK_LOG (MANDATORY):\n"
    "- Use MCP tool: task_manager_server (add_task_to_inbox, mark_task_complete, move_task_to_waiting)\n"
    "- If task completed → mark_task_complete(task_description, section=\"THIS WEEK\")\n"
    "- If task blocked → move_task_to_waiting(task_description, reason=\"blocked on X\", agent_id=\"{agent_id}\")\n"
    "- If new task identified → add_task_to_inbox(task=\"description\", agent_id=\"{agent_id}\")\n"
    "- Location: MASTER_TASK_LOG.md (repository root)\n"
    "- When: After completing work, before session transition\n"
    "- Why: Central task tracking, enables delegation, prevents task loss\n"
    "- Reference: QUICK_START_GUIDE.md, DELEGATION_BOARD.md\n"
    "\n"
    "✅ VERIFY WORK (BEFORE COMMITTING):\n"
    "- Use MCP: verify_git_work(agent_id, file_path, claimed_changes)\n"
    "- Use MCP: verify_work_exists(file_patterns, agent_name)\n"
    "- Ensure work is actually committed before claiming\n"
    "\n"
    "✅ CHECK V2 COMPLIANCE (BEFORE COMMITTING):\n"
    "- Use MCP: check_v2_compliance(file_path)\n"
    "- Use MCP: validate_file_size(file_path)\n"
    "- Use MCP: get_v2_exceptions() if file exceeds limits\n"
    "- Prevent V2 violations before committing\n"
    "\n"
    "✅ ADD TASKS TO CYCLE PLANNER HERE:\n"
    "- Location: agent_workspaces/{agent_id}/cycle_planner_tasks_YYYY-MM-DD.json\n"
    "- When: After completing current work, before session transition\n"
    "- What: Unfinished work, blockers, next session priorities\n"
    "- Reference: Session Cleanup Template Step 9\n"
    "\n"
    "✅ MESSAGE OTHER AGENTS HERE:\n"
    "- Coordination outcomes → If swarm was engaged, report results\n"
    "- Handoff → If work continues with another agent\n"
    "- Completion → Notify relevant agents of completed work\n"
    "\n"
    "- Commit status.json to git\n"
    "- Create & post devlog automatically\n"
    "- Share learnings to Swarm Brain (use MCP: share_learning)\n"
    "- Record decisions if made (use MCP: record_decision)\n"
    "- Report coordination outcomes if swarm was engaged\n"
    "\n"
    "✅ VERIFY WORK (BEFORE COMMITTING):\n"
    "- Use MCP: verify_git_work(agent_id, file_path, claimed_changes)\n"
    "- Use MCP: verify_work_exists(file_patterns, agent_name)\n"
    "- Ensure work is actually committed before claiming\n"
    "\n"
    "✅ CHECK V2 COMPLIANCE (BEFORE COMMITTING):\n"
    "- Use MCP: check_v2_compliance(file_path)\n"
    "- Use MCP: validate_file_size(file_path)\n"
    "- Use MCP: get_v2_exceptions() if file exceeds limits\n"
    "- Prevent V2 violations before committing\n"
    "\n"
    "📖 Full workflow guide: docs/AGENT_OPERATING_CYCLE_WORKFLOW.md\n"
)



