"""
S2A template strings (misc/less common set).

<!-- SSOT Domain: integration -->
"""

S2A_TEMPLATES_MISC: dict[str, str] = {
    "PASSDOWN": (
        "[HEADER] S2A PASSDOWN\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
        "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
        "- Search the codebase for TODO/FIXME items and real work opportunities\n"
        "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
        "- Execute complete implementation with testing and documentation\n"
        "- Make work publicly visible through git commits, devlogs, and blog posts\n"
        "- Transform message receipt into forward momentum, not confirmation loops\n\n"
        "What changed:\n{context}\n\n"
        "Your next slice:\n{actions}\n\n"
        "{operating_cycle}\n"
        "If blocked:\n{fallback}\n"
    ),
    "TELEPHONE_STATUS_GAME": (
        "[HEADER] S2A TELEPHONE STATUS GAME\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
        "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
        "- Search the codebase for TODO/FIXME items and real work opportunities\n"
        "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
        "- Execute complete implementation with testing and documentation\n"
        "- Make work publicly visible through git commits, devlogs, and blog posts\n"
        "- Transform message receipt into forward momentum, not confirmation loops\n\n"
        "Chain Context:\n{context}\n\n"
        "Your move:\n{actions}\n\n"
        "Rules:\n"
        "- Pass actionable state + next slice.\n"
        "- No acknowledgement-only responses.\n\n"
        "{operating_cycle}\n"
        "If blocked:\n{fallback}\n"
    ),
    "TASK_CYCLE": (
        "[HEADER] S2A TASK CYCLE\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
        "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
        "- Search the codebase for TODO/FIXME items and real work opportunities\n"
        "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
        "- Execute complete implementation with testing and documentation\n"
        "- Make work publicly visible through git commits, devlogs, and blog posts\n"
        "- Transform message receipt into forward momentum, not confirmation loops\n\n"
        "Cycle Objective:\n{context}\n\n"
        "Assigned Slice:\n{actions}\n\n"
        "{operating_cycle}\n"
        "If blocked:\n{fallback}\n"
    ),
    "FSM_UPDATE": (
        "[HEADER] S2A FSM UPDATE\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
        "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
        "- Search the codebase for TODO/FIXME items and real work opportunities\n"
        "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
        "- Execute complete implementation with testing and documentation\n"
        "- Make work publicly visible through git commits, devlogs, and blog posts\n"
        "- Transform message receipt into forward momentum, not confirmation loops\n\n"
        "State Change:\n{context}\n\n"
        "Required Behavior:\n{actions}\n\n"
        "{operating_cycle}\n"
        "If blocked:\n{fallback}\n"
    ),
    "DEBATE_CYCLE": (
        "[HEADER] S2A DEBATE CYCLE\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
        "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
        "- Search the codebase for TODO/FIXME items and real work opportunities\n"
        "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
        "- Execute complete implementation with testing and documentation\n"
        "- Make work publicly visible through git commits, devlogs, and blog posts\n"
        "- Transform message receipt into forward momentum, not confirmation loops\n\n"
        "Debate Topic:\n{topic}\n\n"
        "Role/Position:\n{role}\n\n"
        "Context:\n{context}\n\n"
        "Rules:\n{rules}\n\n"
        "Deliverable:\n{deliverable}\n\n"
        "{operating_cycle}\n"
        "If blocked:\n{fallback}\n"
        "#DEBATE #S2A\n"
    ),
    "CYCLE_V2": (
        "[HEADER] C2A CYCLE V2 - MAX PRODUCTIVITY\n"
        "From: Captain Agent-4\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
        "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
        "- Search the codebase for TODO/FIXME items and real work opportunities\n"
        "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
        "- Execute complete implementation with testing and documentation\n"
        "- Make work publicly visible through git commits, devlogs, and blog posts\n"
        "- Transform message receipt into forward momentum, not confirmation loops\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "MISSION\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "{mission}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "DEFINITION OF DONE (DoD)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "{dod}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "CONSTRAINTS\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "SSOT: {ssot_constraint}\n"
        "V2: {v2_constraint}\n"
        "Touch Surface: {touch_surface}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "VALIDATION REQUIRED\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "{validation_required}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "PRIORITY\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "{priority_level}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "HANDOFF EXPECTATION\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "{handoff_expectation}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "AGENT OPERATING CYCLE V2\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "A) Pre-Cycle Rules (Hard Guards):\n"
        "   • WIP = 1 (only one active objective per cycle)\n"
        "   • DoD required (if missing, write 3-line DoD)\n"
        "   • SSOT boundaries first (confirm where truth lives)\n"
        "   • V2 Compliance gate (split if file exceeds limits)\n\n"
        "B) Start of Cycle (Fast):\n"
        "   1. Inbox sweep (max 60 seconds)\n"
        "   2. Claim task: --get-next-task --agent {recipient}\n"
        "   3. Pull last 1 relevant pattern from Swarm Brain\n"
        "   4. Write Micro-Plan (3 bullets max):\n"
        "      - Change target\n"
        "      - Validation method\n"
        "      - Exit criteria\n"
        "   5. Update status.json with phase, mission, micro-plan, DoD\n\n"
        "C) Execution Burst (Timeboxed):\n"
        "   1. Implement smallest viable change toward DoD\n"
        "   2. If scope expands: split into subtask, notify Captain\n"
        "   3. Keep changes localized and typed\n"
        "   4. No refactors unless they reduce immediate risk\n\n"
        "D) Mid-Cycle Checkpoint (Anti-Drift):\n"
        "   After first meaningful change:\n"
        "   • Still aligned with DoD?\n"
        "   • Still within SSOT?\n"
        "   • Still within V2?\n"
        "   If no: adjust plan, report correction\n\n"
        "E) Validation First-Class (Shift Left):\n"
        "   1. Run tests/lint/verification for touched surface\n"
        "   2. If tests missing: add minimal tests\n"
        "   3. Log evidence (command/output summary)\n\n"
        "F) Reporting Contract (No Empty Replies):\n"
        "   Must include:\n"
        "   • What changed (artifact-level)\n"
        "   • Validation evidence\n"
        "   • Measurable result\n"
        "   • Next recommended action\n\n"
        "G) Documentation:\n"
        "   • status.json updated (COMPLETE/BLOCKED/HANDOFF_READY)\n"
        "   • Discord devlog posted for completed actions\n\n"
        "H) Escalation Thresholds:\n"
        "   Escalate when:\n"
        "   • DoD unclear beyond 2 reasonable assumptions\n"
        "   • SSOT conflict detected\n"
        "   • Cross-agent dependency required\n"
        "   • Change affects >2 modules/domains\n\n"
        "I) Swarm Force Multiplier (CRITICAL):\n"
        "   Before starting execution:\n"
        "   • Assess task size: Is this a force multiplier opportunity?\n"
        "   • If task is large (3+ cycles) or spans multiple domains:\n"
        "     → Break down into parallelizable components\n"
        "     → Assign to 2-8 agents via messaging system\n"
        "     → Coordinate parallel execution\n"
        "     → Integrate results\n"
        "   • Remember: 8 agents working in parallel > 1 agent working alone\n"
        "   • See Swarm Coordination Protocol below for details\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "SUCCESS METRICS PER CYCLE\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "• Output: ≥1 merged-ready artifact OR ≥1 validated decision\n"
        "• Validation: evidence included every time\n"
        "• Drift: zero off-mission edits\n"
        "• WIP: never >1\n"
        "• Swarm Utilization: Agents engaged when task requires coordination\n\n"
        "{swarm_coordination}\n"
        "If blocked:\n{fallback}\n"
        "#CYCLE_V2 #C2A #SWARM-COORDINATION\n"
    ),
}



