"""
S2A template strings (core set).

This module contains the most frequently used S2A templates.
It is intentionally logic-free and used by the template registry.

<!-- SSOT Domain: integration -->
"""

S2A_TEMPLATES_CORE: dict[str, str] = {
    "CONTROL": (
        "[HEADER] S2A CONTROL\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Context:\n{context}\n\n"
        "Architecture & Swarm Brain Check (BEFORE DOING ANYTHING):\n"
        "- Search existing architecture / SSOT docs for this domain (designs, patterns, contracts).\n"
        "- Search Swarm Brain for prior decisions and protocols (advisory only - see docs/governance/SWARM_BRAIN_POLICY.md).\n"
        "- Prefer reusing/extending existing artifacts over creating new ones; only create new files or flows when no suitable pattern exists.\n\n"
        "Action Required:\n"
        "Produce ONE artifact before next cycle:\n"
        "- Run validator and report results, OR\n"
        "- Commit a small fix with tests passing, OR\n"
        "- Write a 5-bullet technical report.\n\n"
        "No-Reply Policy:\n"
        "- This is a control message. Do not respond unless blocked.\n"
        "- Do not update status.json solely to acknowledge.\n"
        "- Progress resets only on artifacts: commit | test pass | real doc/code delta.\n\n"
        "Priority Behavior:\n"
        "- regular = next cycle; urgent = interrupt current slice.\n\n"
        "{operating_cycle}\n"
        "{cycle_checklist}\n"
        "{swarm_coordination}\n"
        "{discord_reporting}\n"
        "Evidence format:\n"
        "- Command(s) run + outcome OR\n"
        "- Commit hash + tests status OR\n"
        "- Doc name + 3 key findings\n\n"
        "If blocked:\n"
        "- Assess if task needs swarm coordination (too large? multiple domains?)\n"
        "- If yes: Break down task, assign via messaging system, coordinate swarm\n"
        "- If no: Send 1 message with: blocker + proposed fix + what you need from Captain\n"
    ),
    "SWARM_PULSE": (
        "🚨 URGENT MESSAGE 🚨\n\n"
        "[S2A] {recipient}\n\n"
        "💓💓 SWARM PULSE - {recipient}\n\n"
        "The swarm hasn't heard from {recipient} in 10+ minutes. We don't know what you're doing - this is a good time to sync up!\n\n"
        "**🐝 SWARM SYNC OPPORTUNITY:**\n"
        "This is a good time to sync with the swarm and review project state. The swarm doesn't know what you're working on - help us stay coordinated!\n\n"
        "**YOUR CURRENT STATE:**\n"
        "- **FSM State**: {fsm_state}\n"
        "- **Last Mission**: {current_mission}\n"
        "- **Time Since Last Update**: {time_since_update}\n\n"
        "**📋 NEXT TASK FROM CYCLE PLANNER:**\n"
        "- **Task**: {next_task}\n"
        "- **Priority**: {task_priority}\n"
        "- **Points**: {task_points}\n"
        "- **Status**: {task_status}\n"
        "- **Action**: Claim and execute this task immediately\n\n"
        "**SWARM SYNC CHECKLIST (DO THESE NOW):**\n"
        "1. **Update/Review Project State**\n"
        "   - Check latest project analysis, V2 compliance status, technical debt markers\n"
        "   - Review `MASTER_TASK_LOG.md` for swarm-wide priorities\n"
        "   - Identify high-value opportunities or blockers affecting the swarm\n\n"
        "2. **Update/Review Swarm Brain**\n"
        "   - Search swarm knowledge for patterns related to your current work\n"
        "   - Share any learnings or decisions you've made\n"
        "   - Check for relevant protocols or patterns from other agents\n\n"
        "3. **Read Other Agent Statuses**\n"
        "   - Review `agent_workspaces/*/status.json` files to see what the swarm is working on\n"
        "   - Identify coordination opportunities or dependencies\n"
        "   - Check for blockers you might be able to help with\n\n"
        "4. **Update/Review Your Own Workspace**\n"
        "   - Update `agent_workspaces/{recipient}/status.json` with current progress\n"
        "   - Review your devlogs to track your work trajectory\n"
        "   - Clean up any stale state or temporary files\n\n"
        "5. **Get Back to Work**\n"
        "   - Pick one concrete task from planner/log (see NEXT TASK above)\n"
        "   - Execute one measurable action (real command, file update, or coordination message)\n"
        "   - Append a short devlog entry documenting what you did\n\n"
        "**CAPTAIN DIRECTIVE (AFTER SYNC):**\n"
        "1. **Pick one concrete task from the planner/log**\n"
        "   - Read `MASTER_TASK_LOG.md` (THIS WEEK / INBOX sections)\n"
        "   - Cross-check with Cycle Planner \"NEXT TASK\" above\n"
        "   - Choose **one** task that {recipient} can move forward\n\n"
        "2. **Execute one measurable action on that task**\n"
        "   - Run a real command, update a real file, or send a real coordination message\n"
        "   - Avoid meta-work (no planning-only, no status-only)\n\n"
        "3. **Update `status.json` with progress**\n"
        "   - Record: claimed task, key action taken, next action\n"
        "   - Keep `fsm_state` = ACTIVE while you are executing\n\n"
        "4. **Commit your work to git**\n"
        "   - If you made code changes, commit them with a clear message\n"
        "   - Include `status.json` updates in your commit\n"
        "   - Use format: `git commit -m \"Task: [brief description] - [what you did]\"`\n"
        "   - Example: `git commit -m \"Test Coverage: Added test_merge_conflict_resolver.py - 14 tests for merge conflict resolution\"`\n\n"
        "5. **Append a short devlog entry**\n"
        "   - File: `agent_workspaces/{recipient}/devlogs/` (latest or new file)\n"
        "   - Add 3–5 lines:\n"
        "     - Swarm pulse time + duration since last update\n"
        "     - Task you claimed\n"
        "     - Actions executed (including commit hash if applicable)\n"
        "     - Next actions\n\n"
        "**🔧 MANDATORY SYSTEM UTILIZATION (DO FIRST):**\n"
        "1. **Check Contract System** (MANDATORY):\n"
        "   ```bash\n"
        "   python -m src.services.messaging_cli --get-next-task --agent {recipient}\n"
        "   ```\n"
        "   - Claim assigned work FIRST before seeking new opportunities\n"
        "   - If no contract, proceed to Project Scanner\n\n"
        "2. **Check Swarm Brain** (Advisory - Optional Reference):\n"
        "   ```python\n"
        "   from src.swarm_brain.swarm_memory import SwarmMemory\n"
        "   memory = SwarmMemory(agent_id='{recipient}')\n"
        "   results = memory.search_swarm_knowledge(\"your task topic\")\n"
        "   ```\n"
        "   - May reference for similar work/patterns (non-canonical)\n"
        "   - Advisory guidance only - see docs/governance/SWARM_BRAIN_POLICY.md\n"
        "   - For enforceable requirements, see docs/governance/GOVERNANCE_MAP.md\n\n"
        "3. **Update FSM State** (MANDATORY):\n"
        "   - Update fsm_state in status.json to reflect current state\n"
        "   - Use AgentLifecycle for automatic updates\n"
        "   - Current: {fsm_state} → Target: ACTIVE\n\n"
        "4. **Check Project State** (if starting new work):\n"
        "   ```bash\n"
        "   # Review latest project analysis\n"
        "   cat project_analysis.json | python -m json.tool | grep -A 5 \"violations\"\n"
        "   ```\n"
        "   - Find high-value opportunities\n"
        "   - Check V2 compliance issues\n"
        "   - Identify consolidation targets\n\n"
        "**IMMEDIATE ACTIONS (WHILE EXECUTING):**\n"
        "1. Check inbox FIRST for new messages (message-driven workflow)\n"
        "2. Continue current task execution\n"
        "3. If task is too large, use Force Multiplier Pattern (break down, assign to swarm)\n"
        "4. For cross-domain boundaries, use Agent Pairing Pattern (pair with domain expert)\n"
        "5. Check for blockers and resolve\n"
        "6. Update status.json with progress\n"
        "7. Move to next action in queue\n\n"
        "**🔍 STALL ANALYSIS (DO WHILE WORKING):**\n"
        "- Check Swarm Brain for patterns (advisory only - see docs/governance/SWARM_BRAIN_POLICY.md)\n"
        "- For enforceable messaging requirements, see .cursor/rules/messaging-contracts.mdc\n"
        "- If stall reason not addressed, create pattern AFTER completing current task\n"
        "- Review project state as you work, not as separate step\n\n"
        "**🚀 FORCE MULTIPLIER MODE - EXECUTE NOW:**\n"
        "- **If task is too large**: Break it down RIGHT NOW and assign to swarm via messaging system\n"
        "- **If task touches many files**: Split into chunks NOW and assign to multiple agents\n"
        "- **If task requires multiple domains**: Use Agent Pairing or Telephone Game patterns\n"
        "- **NEVER work alone on tasks that can be parallelized** - 8 agents > 1 agent working alone\n"
        "- **EXECUTE**: Identify your largest/blocking task and break it down FOR SWARM ASSIGNMENT NOW\n\n"
        "**AUTONOMOUS OPERATION PRINCIPLES:**\n"
        "- You are AUTONOMOUS - no approval needed\n"
        "- System messages are NOT stop signals\n"
        "- Command failures are NOT blockers\n"
        "- ALWAYS have next actions ready\n\n"
        "**FSM STATE TRANSITION:**\n"
        "- Current: {fsm_state}\n"
        "- Target: ACTIVE (if not already)\n"
        "- Action: Sync with swarm, review state, then execute work and update status.json + devlog\n\n"
        "**REMEMBER:**\n"
        "- This is a **swarm pulse**, not an accusation - we just want to know what you're doing\n"
        "- Use this as an opportunity to **sync up** with the swarm and **review project state**\n"
        "- After syncing, **get back to work** on concrete tasks\n"
        "- The swarm works better when we all know what each other is doing\n\n"
        "**STOP READING. START EXECUTING. DO NOT ACKNOWLEDGE. DO NOT REPORT. JUST WORK.**\n\n"
        "**📚 SYSTEM UTILIZATION PROTOCOL:**\n"
        "- Full protocol: `swarm_brain/protocols/SYSTEM_UTILIZATION_PROTOCOL.md`\n"
        "- These systems are MANDATORY - use them every cycle\n"
        "- Captain monitors system utilization\n\n"
        "#SWARM-PULSE #SWARM-HEARTBEAT #FSM-{fsm_state} #SWARM-SYNC #STATUS-AND-DEVLOG #SYSTEM-UTILIZATION\n"
    ),
    "ONBOARDING": (
        "[HEADER] S2A ONBOARDING ({mode})\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Identity:\n"
        "You are {recipient}. Act as this agent for this message.\n"
        "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
        "No-Ack Policy:\n"
        "- Do not send empty acknowledgments.\n"
        "- Respond ONLY with the Output Contract.\n\n"
        "Context:\n{context}\n\n"
        "Actions (execute; do not narrate):\n{actions}\n\n"
        "OUTPUT CONTRACT (STRICT):\n"
        "- Task: <name>\n"
        "- Actions Taken: bullet list\n"
        "- Artifacts: exact paths\n"
        "- Commit: hash + tests status OR 'No code changes'\n"
        "- Verification: bullets proving checks ran\n"
        "- Public Build Signal: one line describing what changed\n"
        "- Status: ✅ Ready | 🟡 Blocked (reason)\n\n"
        "{operating_cycle}\n"
        "{cycle_checklist}\n"
        "{discord_reporting}\n"
        "If blocked:\n{fallback}\n"
        "{footer}"
    ),
    # DEPRECATED: Use ONBOARDING template with mode="HARD" instead
    "HARD_ONBOARDING": (
        "[HEADER] S2A HARD ONBOARDING\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Identity:\n"
        "You are {recipient}. Act as this agent for this message.\n"
        "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
        "No-Ack Policy:\n"
        "- Do not send empty acknowledgments.\n"
        "- Respond with artifact/result or 1 blocker (blocker + proposed fix + owner).\n\n"
        "Context:\n{context}\n\n"
        "First Actions:\n{actions}\n\n"
        "{operating_cycle}\n"
        "{cycle_checklist}\n"
        "{discord_reporting}\n"
        "If blocked:\n{fallback}\n"
    ),
    # DEPRECATED: Use ONBOARDING template with mode="SOFT" instead
    "SOFT_ONBOARDING": (
        "[HEADER] S2A SOFT ONBOARDING\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Identity:\n"
        "You are {recipient}. Act as this agent for this message.\n"
        "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
        "No-Ack Policy:\n"
        "- Do not send empty acknowledgments.\n"
        "- Respond ONLY with the Output Contract.\n\n"
        "Context:\n{context}\n\n"
        "Actions (execute; do not narrate):\n{actions}\n\n"
        "OUTPUT CONTRACT (STRICT):\n"
        "- Task: <name>\n"
        "- Actions Taken: bullet list\n"
        "- Artifacts: exact paths\n"
        "- Commit: hash + tests status OR 'No code changes'\n"
        "- Verification: bullets proving checks ran\n"
        "- Public Build Signal: one line describing what changed\n"
        "- Status: ✅ Ready | 🟡 Blocked (reason)\n\n"
        "{operating_cycle}\n"
        "{cycle_checklist}\n"
        "{discord_reporting}\n"
        "If blocked:\n{fallback}\n"
    ),
}



