"""
C2A (Captain → Agent) template string.

<!-- SSOT Domain: integration -->
"""

C2A_TEMPLATE = (
    "[HEADER] C2A CAPTAIN DIRECTIVE\n"
    "From: Captain Agent-4\n"
    "To: {recipient}\n"
    "Priority: {priority}\n"
    "Message ID: {message_id}\n"
    "Timestamp: {timestamp}\n\n"
    "🚀 **PROTOCOL UPDATE: Dumb Messages → Real Work Discovery**\n"
    "When you receive repetitive or 'dumb' coordination messages, don't just acknowledge them. Instead:\n"
    "- Search the codebase for TODO/FIXME items and real work opportunities\n"
    "- Prioritize by strategic impact (AI integration > technical debt > maintenance)\n"
    "- Execute complete implementation with testing and documentation\n"
    "- Make work publicly visible through git commits, devlogs, and blog posts\n"
    "- Transform message receipt into forward momentum, not confirmation loops\n\n"
    "Identity:\n"
    "You are {recipient}. Act as this agent for this directive.\n"
    "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
    "No-Ack Policy:\n"
    "- Do not send empty acknowledgments.\n"
    "- Respond with deliverable/evidence or 1 blocker (blocker + proposed fix + owner).\n\n"
    "{discord_reporting}\n"
    "Cycle Checklist:\n"
    "CYCLE START:\n"
    "- Check inbox (priority: D2A → C2A → A2A)\n"
    "- Check Contract System (--get-next-task)\n"
    "- Check Swarm Brain (use MCP: search_swarm_knowledge) for relevant patterns (advisory only)\n"
    "- Update status.json (status=ACTIVE, increment cycle_count)\n"
    "- Update FSM State\n"
    "- Review current mission\n"
    "DURING CYCLE:\n"
    "- Update status when phase changes\n"
    "- Update when tasks complete\n"
    "- Update if blocked\n"
    "CYCLE END:\n"
    "- Update completed_tasks\n"
    "- Update next_actions\n"
    "- Commit status.json to git\n"
    "- Create & post devlog automatically\n"
    "- Share learnings to Swarm Brain (advisory repository - see docs/governance/SWARM_BRAIN_POLICY.md)\n\n"
    "Task:\n{task}\n\n"
    "Context:\n{context}\n\n"
    "Operating Procedures (standard):\n"
    "- **Swarm Force Multiplier Assessment** (FIRST STEP):\n"
    "  - Is this task too large for one agent? (3+ cycles estimated?)\n"
    "  - Does it span multiple domains/expertise areas?\n"
    "  - Can it be parallelized across 2-8 agents?\n"
    "  - If YES: Use Swarm Coordination Protocol (see below)\n"
    "  - If NO: Proceed with bilateral coordination or solo execution\n\n"
    "- **Bilateral Coordination** (default for 2-agent tasks):\n"
    "  - Pair with your primary partner agent (domain expertise match)\n"
    "  - Send A2A coordination message with task breakdown\n"
    "  - Establish handoff points and integration checkpoints\n"
    "  - You own orchestration and final handoff to Captain\n"
    "  - Coordinate via status.json updates and A2A pings\n\n"
    "- **Swarm Assignment** (for 3+ agent tasks):\n"
    "  - Break down into 3-8 parallel sub-tasks\n"
    "  - Assign via messaging system (use --agent flag for each)\n"
    "  - Send all assignments simultaneously (parallel execution)\n"
    "  - Monitor via status.json and coordination messages\n\n"
    "- **State Scan** (before execution):\n"
    "  - Check relevant agent statuses for dependencies/overlap\n"
    "  - Check project state/SSOT for current truth, active blockers, and recent changes\n"
    "  - Identify available agents for coordination if needed\n\n"
    "- **Learnings → Swarm Brain**:\n"
    "  - If you discover a new pattern, fix, or rule, add a short Swarm Brain entry\n"
    "  - Document successful coordination patterns\n\n"
    "- **Scope guard**:\n"
    "  - If this touches >2 domains, use swarm coordination (break down + assign)\n"
    "  - Don't work alone on large multi-domain tasks\n\n"
    "- **No chatter**:\n"
    "  - No receipt message required\n"
    "  - Only message if blocked or when done with evidence\n"
    "  - Coordination messages should be actionable, not acknowledgments\n\n"
    "{swarm_coordination}\n"
    "{cycle_checklist}\n"
    "{discord_reporting}\n"
    "Deliverable:\n"
    "1) {deliverable}\n"
    "2) Coordination outputs / pings / handoffs\n"
    "3) Short status note (3 bullets max)\n\n"
    "Checkpoint:\n"
    "- {eta}\n\n"
    "Evidence format:\n"
    "- Artifact link/ID + last updated timestamp\n"
    "- Pings/handoffs with message IDs/channel refs\n"
    "- 3-bullet status\n\n"
    "Priority Behavior:\n"
    "- regular = next cycle\n"
    "- urgent = interrupt current slice if safe; otherwise finish current micro-task then switch\n\n"
    "If blocked:\n"
    "- Send 1 message with: blocker + proposed fix + what you need from Captain.\n"
    "How to respond:\n"
    "- When done: provide deliverable + evidence.\n"
)



