"""
A2A (Agent ↔ Agent) coordination template string.

<!-- SSOT Domain: integration -->
"""

A2A_TEMPLATE = (
    "[HEADER] A2A COORDINATION — BILATERAL SWARM COORDINATION\n"
    "From: {sender}\n"
    "To: {recipient}\n"
    "Priority: {priority}\n"
    "Message ID: {message_id}\n"
    "Timestamp: {timestamp}\n\n"
    "🐝 **COORDINATED SWARM REQUEST**:\n"
    "This is a bilateral coordination request to leverage swarm force multiplication.\n"
    "We're asking for your expertise to parallelize work and accelerate completion.\n\n"
    "**COORDINATION REQUEST**:\n{ask}\n\n"
    "**CONTEXT**:\n{context}\n\n"
    "**WHY THIS COORDINATION?**\n{coordination_rationale}\n\n"
    "**EXPECTED CONTRIBUTION**:\n{expected_contribution}\n\n"
    "**TIMING**:\n{coordination_timeline}\n\n"
    "**RESPONSE REQUIRED**:\n"
    "Reply within 30 minutes with acceptance/decline and proposed approach.\n\n"
    "**WHAT TO INCLUDE IN YOUR REPLY** (for ACCEPT responses):\n"
    "- **Proposed approach**: How you'll coordinate (your role + partner's role)\n"
    "- **Synergy identification**: How your capabilities complement your partner's\n"
    "- **Next steps**: Suggested initial coordination touchpoint or action item\n"
    "- **Relevant capabilities**: Brief list of your applicable skills\n"
    "- **Timeline**: When you can start and expected coordination sync time\n\n"
    "**REPLY FORMAT (MANDATORY)**:\n"
    "```\n"
    "A2A REPLY to {message_id}:\n"
    "✅ ACCEPT: [Proposed approach: your role + partner role. Synergy: how capabilities complement. Next steps: initial action. Capabilities: key skills. Timeline: start time + sync time] | ETA: [timeframe]\n"
    "OR\n"
    "❌ DECLINE: [reason] | Alternative: [suggested agent]\n"
    "```\n\n"
    "**REPLY COMMAND**:\n"
    "```bash\n"
    "python -m src.services.messaging_cli --agent {sender} \\\n"
    "  --message \"A2A REPLY to {message_id}: [your response]\" \\\n"
    "  --category a2a --sender Agent-X --tags coordination-reply\n"
    "```\n"
    "**IMPORTANT SENDER IDENTIFICATION**: \n"
    "- `--agent {sender}` = recipient (who you're replying to, shown above as 'From: {sender}')\n"
    "- `--sender Agent-X` = **YOU** (replace X with your agent number, e.g., `Agent-2` or `Agent-5`)\n"
    "- Always include `--sender Agent-X` so your response header shows your agent ID instead of defaulting to CAPTAIN\n\n"
    "**COORDINATION PRINCIPLES**:\n"
    "- 2 agents working in parallel > 1 agent working alone\n"
    "- Share context via status.json updates and A2A pings\n"
    "- Report progress to accelerate integration\n"
    "- **Be proactive**: Propose concrete next steps rather than 'standing by'\n"
    "- **Identify synergy**: Explain how your skills complement your partner's\n"
    "- **Suggest handoffs**: Propose coordination touchpoints or integration points\n\n"
    "If blocked: Send brief blocker description + proposed solution\n\n"
    "#A2A #BILATERAL-COORDINATION #SWARM-FORCE-MULTIPLIER\n"
)



