groups:
- name: migrated_sites_alerts
  rules:
  - alert: WebsiteDown
    annotations:
      description: Website {{ $labels.instance }} has been down for more than 5 minutes.
      summary: Website {{ $labels.instance }} is down
    expr: up{job='migrated-sites'} == 0
    for: 5m
    labels:
      severity: critical
  - alert: HighResponseTime
    annotations:
      description: 95th percentile response time is {{ $value }}s for {{ $labels.instance
        }}.
      summary: High response time on {{ $labels.instance }}
    expr: http_request_duration_seconds{quantile='0.95', job='migrated-sites'} > 5
    for: 10m
    labels:
      severity: warning
  - alert: SSLCertificateExpiring
    annotations:
      description: SSL certificate for {{ $labels.instance }} expires in {{ $value
        }} days.
      summary: SSL certificate expiring soon
    expr: ssl_certificate_expiry_days < 30
    labels:
      severity: warning
