"""Shared constants for the decision module."""

DEFAULT_MAX_CONCURRENT_DECISIONS = 100
DECISION_TIMEOUT_SECONDS = 300
DEFAULT_CONFIDENCE_THRESHOLD = 0.7
AUTO_CLEANUP_COMPLETED_DECISIONS = True
CLEANUP_INTERVAL_MINUTES = 15
MAX_DECISION_HISTORY = 1000
