"""
Website Publisher - Phase 3
===========================

Converts markdown to HTML and publishes to website.

Author: Agent-7 (Web Development Specialist)
V2 Compliant: <300 lines
"""

import re
from pathlib import Path
from typing import Optional, Dict, Any
from datetime import datetime


class WebsitePublisher:
    """Publishes artifacts to website."""
    
    def __init__(
        self,
        output_path: Optional[Path] = None,
        markdown_to_html: bool = True
    ):
        """Initialize website publisher."""
        if output_path is None:
            output_path = Path("website/content")
        self.output_path = Path(output_path)
        self.output_path.mkdir(parents=True, exist_ok=True)
        self.markdown_to_html = markdown_to_html
    
    def _markdown_to_html(self, markdown_content: str) -> str:
        """Convert markdown to HTML (basic implementation)."""
        html = markdown_content
        
        # Headers
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', html, flags=re.MULTILINE)
        
        # Bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        
        # Italic
        html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)
        
        # Links
        html = re.sub(
            r'\[(.+?)\]\((.+?)\)',
            r'<a href="\2">\1</a>',
            html
        )
        
        # Code blocks
        html = re.sub(
            r'```(\w+)?\n(.*?)```',
            r'<pre><code>\2</code></pre>',
            html,
            flags=re.DOTALL
        )
        
        # Inline code
        html = re.sub(r'`(.+?)`', r'<code>\1</code>', html)
        
        # Paragraphs
        lines = html.split('\n')
        result = []
        in_paragraph = False
        
        for line in lines:
            if line.strip() and not line.strip().startswith('<'):
                if not in_paragraph:
                    result.append('<p>')
                    in_paragraph = True
                result.append(line)
            else:
                if in_paragraph:
                    result.append('</p>')
                    in_paragraph = False
                result.append(line)
        
        if in_paragraph:
            result.append('</p>')
        
        return '\n'.join(result)
    
    def _wrap_html(self, content: str, title: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Wrap content in HTML template."""
        if metadata is None:
            metadata = {}
        
        html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1, h2, h3, h4 {{
            color: #2c3e50;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
        }}
        pre {{
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
        a {{
            color: #3498db;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <article>
        {content}
    </article>
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 0.9em;">
        <p>Generated by Dream.OS Output Flywheel v1.0</p>
        <p>Published: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </footer>
</body>
</html>"""
        return html_template
    
    def publish_artifact(
        self,
        artifact_type: str,
        artifact_path: str,
        title: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Publish artifact to website."""
        source_file = Path(artifact_path)
        if not source_file.exists():
            return {
                "success": False,
                "error": f"Artifact file not found: {artifact_path}"
            }
        
        # Read markdown content
        try:
            markdown_content = source_file.read_text(encoding="utf-8")
        except Exception as e:
            return {
                "success": False,
                "error": f"Failed to read artifact: {e}"
            }
        
        # Convert to HTML if enabled
        if self.markdown_to_html:
            html_content = self._markdown_to_html(markdown_content)
        else:
            html_content = markdown_content
        
        # Determine title
        if title is None:
            title = source_file.stem.replace("_", " ").title()
        
        # Wrap in HTML template
        full_html = self._wrap_html(html_content, title, metadata)
        
        # Determine output filename
        output_filename = source_file.stem + ".html"
        output_file = self.output_path / output_filename
        
        # Write HTML file
        try:
            output_file.write_text(full_html, encoding="utf-8")
        except Exception as e:
            return {
                "success": False,
                "error": f"Failed to write HTML file: {e}"
            }
        
        return {
            "success": True,
            "status": "published",
            "message": f"Artifact published to {output_file}",
            "output_path": str(output_file)
        }




