"""
Blog Generator Module
====================

Generates Victor-voiced blog posts from agent status data.

Protocol: CYCLE_ACCOMPLISHMENTS_REPORT_GENERATION v2.0
Author: Agent-7 (Web Development Specialist)
Date: 2025-12-30
V2 Compliant: Yes

<!-- SSOT Domain: tools -->
"""

import re
import yaml
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional


def load_voice_profile(workspace_root: Optional[Path] = None) -> Optional[Dict[str, Any]]:
    """
    Load Victor's voice profile.
    
    Args:
        workspace_root: Root workspace path (defaults to current directory)
    
    Returns:
        Voice profile dict or None if not found
    """
    if workspace_root is None:
        workspace_root = Path.cwd()
    
    profile_path = workspace_root / "config" / "voice_profiles" / "victor_voice_profile.yaml"
    
    if profile_path.exists():
        try:
            with open(profile_path, 'r', encoding='utf-8') as f:
                return yaml.safe_load(f)
        except Exception as e:
            print(f"⚠️ Error loading voice profile: {e}")
    
    return None


def apply_victor_voice(text: str, profile: Optional[Dict[str, Any]], mode: str = 'narrative') -> str:
    """
    Apply Victor's voice rules heuristically.
    
    Args:
        text: Text to transform
        profile: Voice profile dict
        mode: 'narrative' (blog) or 'operational' (report)
    
    Returns:
        Transformed text
    """
    if not profile:
        return text.lower()  # Basic fallback
    
    rules = profile.get('voice_profile', {}).get('modes', {}).get(mode, {}).get('rules', {})
    lexicon = profile.get('voice_profile', {}).get('lexicon', {})
    
    # 1. Lowercase (mostly)
    if rules.get('casing') == 'mostly lowercase':
        lines = text.split('\n')
        processed_lines = []
        for line in lines:
            processed_lines.append(line.lower())
        text = '\n'.join(processed_lines)
    
    # 2. Remove Bullets
    if not rules.get('use_bullets', True):
        text = re.sub(r'^\s*-\s+', '', text, flags=re.MULTILINE)
    
    # 3. Formatting removal (Markdown headers to text)
    if mode == 'narrative':
        text = re.sub(r'^#+\s+', '', text, flags=re.MULTILINE)
        text = text.replace('**', '')  # Remove bold
    
    # 4. Lexicon Swaps
    replacements = {
        "completed tasks": "shipped items",
        "achievements": "wins",
        "active tasks": "building",
        "current mission": "current focus",
        "status:": "state:",
        "priority:": "level:",
        "in progress": "building",
        "generated by": "signal from",
        "total agents": "swarm size",
    }
    
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    # 5. Structure adjustment (Narrative flow)
    if mode == 'narrative':
        # Compact multiple newlines
        text = re.sub(r'\n{3,}', '\n\n', text)
    
    return text


def format_task_for_blog(task: Any) -> str:
    """
    Format a task for blog display (clean and simple).
    
    Args:
        task: Task as string or dict
    
    Returns:
        Clean task text
    """
    if isinstance(task, str):
        task_text = task
    elif isinstance(task, dict):
        task_text = task.get("task", "")
    else:
        task_text = str(task)
    
    # Clean up task text
    task_text = task_text.lower().replace('complete', '').replace('✅', '').strip()
    return task_text


def generate_narrative_blog_content(
    agents_data: List[Dict[str, Any]],
    total_completed: int,
    total_achievements: int,
    active_agents: int,
    date_str: str,
    workspace_root: Optional[Path] = None
) -> str:
    """
    Generate the blog post content using Victor's narrative voice.
    
    Args:
        agents_data: List of agent status dicts
        total_completed: Total completed tasks
        total_achievements: Total achievements
        active_agents: Number of active agents
        date_str: Date string for the report
        workspace_root: Root workspace path for voice profile
    
    Returns:
        Blog post content as string
    """
    profile = load_voice_profile(workspace_root)
    
    # Intro
    content = f"cycle report for {date_str}.\n"
    content += f"swarm size: {active_agents}.\n"
    content += f"shipped items: {total_completed}.\n"
    content += f"wins: {total_achievements}.\n\n"
    
    content += "here is the signal.\n\n"
    
    for data in agents_data:
        agent_id = data.get("agent_id", "unknown").lower()
        agent_name = data.get("agent_name", "unknown").lower()
        mission = data.get("current_mission", "no mission").lower()
        
        content += f"{agent_id} ({agent_name})\n"
        content += f"focus: {mission}\n\n"
        
        # Completed (Narrative style: just list them simply)
        completed = data.get("completed_tasks", [])
        if completed:
            content += "shipped:\n"
            for task in completed[-5:]:  # Top 5 only for blog to keep it tight
                task_text = format_task_for_blog(task)
                if task_text:
                    content += f"{task_text}\n"
            content += "\n"
        
        # Achievements
        achievements = data.get("achievements", [])
        if achievements:
            content += "wins:\n"
            for ach in achievements[-3:]:
                if isinstance(ach, str):
                    ach_text = ach
                elif isinstance(ach, dict):
                    ach_text = ach.get("title", "")
                else:
                    ach_text = str(ach)
                
                ach_text = ach_text.lower().strip()
                if ach_text:
                    content += f"{ach_text}\n"
            content += "\n"
        
        content += "\n"
    
    content += "closure.\n"
    content += "victor.\n"
    
    # Apply voice transformation
    return apply_victor_voice(content, profile, mode='narrative')


def save_blog_post(
    blog_content: str,
    date_str: str,
    active_agents: int,
    total_completed: int,
    workspace_root: Optional[Path] = None
) -> Path:
    """
    Save blog post with frontmatter to docs/blog/.
    
    Args:
        blog_content: Blog post body content
        date_str: Date string for the report
        active_agents: Number of active agents
        total_completed: Total completed tasks
        workspace_root: Root workspace path (defaults to current directory)
    
    Returns:
        Path to saved blog post file
    """
    if workspace_root is None:
        workspace_root = Path.cwd()
    
    blog_dir = workspace_root / "docs" / "blog"
    blog_dir.mkdir(parents=True, exist_ok=True)
    
    blog_filename = f"cycle_accomplishments_{date_str}.md"
    blog_path = blog_dir / blog_filename
    
    # Create blog-friendly content with Frontmatter
    blog_final_content = f"""---
title: "cycle report: {date_str}"
date: {date_str}
author: victor
category: devlog
tags: [swarm, cycle-report, build-in-public]
excerpt: "swarm size: {active_agents}. shipped: {total_completed}. the signal."
---

{blog_content}
"""
    
    with open(blog_path, 'w', encoding='utf-8') as f:
        f.write(blog_final_content)
    
    return blog_path

