#!/usr/bin/env python3
"""
Messaging Templates & Text - V2 Compliance Module
=================================================

<!-- SSOT Domain: integration -->

Canonical policy text, template strings, and formatting helpers.

Author: Agent-1 (Integration & Core Systems Specialist)
Created: 2025-10-11
License: MIT
"""

from __future__ import annotations

from typing import Any

from .messaging_models import MessageCategory


# Canonical operating cycle text for S2A messages.
AGENT_OPERATING_CYCLE_TEXT = (
    "Agent Operating Cycle (canonical):\n"
    "1) Claim\n"
    "2) Sync SSOT/context\n"
    "3) Slice\n"
    "4) Execute\n"
    "5) Validate\n"
    "6) Commit\n"
    "7) Report evidence\n"
)

# Cycle checklist to keep start/during/end behavior explicit
# Reference: docs/AGENT_OPERATING_CYCLE_WORKFLOW.md
CYCLE_CHECKLIST_TEXT = (
    "Cycle Checklist:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "CYCLE START:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Check inbox (priority: D2A → C2A → A2A)\n"
    "- Check Contract System (--get-next-task)\n"
    "- Check Swarm Brain (search relevant topics)\n"
    "- 🔍 **FORCE MULTIPLIER ASSESSMENT (MANDATORY FIRST STEP)**:\n"
    "  - Will this task take >1 cycle? → STOP, delegate parts to swarm\n"
    "  - Does this touch 2+ domains? → STOP, coordinate with domain experts\n"
    "  - Is another agent better suited? → STOP, message them to take over\n"
    "  - Can this be parallelized? → STOP, break down and assign to 2-4 agents\n"
    "  - ONLY if all answers are NO → proceed solo\n"
    "- Update status.json (status=ACTIVE, increment cycle_count)\n"
    "- Update FSM State\n"
    "- Review current mission\n"
    "\n"
    "❌ DO NOT: Add tasks to cycle planner here (unless urgent)\n"
    "❌ DO NOT: Message other agents here (unless urgent coordination needed)\n"
    "\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "DURING CYCLE:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "📋 PHASE 3: SLICE (Technical Implementation Planning):\n"
    "1. Start with explicit technical instructions (not general \"build this\")\n"
    "2. Request full technical implementation plan from AI first\n"
    "3. Vet the plan before execution\n"
    "4. Convert validated plan into detailed prompt for model\n"
    "5. Code review: Confirm implementation won't be spaghetti\n"
    "6. Ensure clean architecture patterns, not spaghetti code\n"
    "\n"
    "- Update status when phase changes\n"
    "- Update when tasks complete\n"
    "- Update if blocked\n"
    "\n"
    "✅ MESSAGE OTHER AGENTS WHEN:\n"
    "- Task expands → Break down and coordinate (use A2A messaging)\n"
    "- Need domain expertise → Message domain specialist agent\n"
    "- Cross-domain work → Message relevant agents for coordination\n"
    "- 75-80% complete → Send \"gas\" to next agent in sequence (pipeline continuity)\n"
    "- Blocked → Message for help or escalate to Captain\n"
    "- Force multiplier opportunity → Break down and assign to swarm\n"
    "\n"
    "❌ DO NOT: Add tasks to cycle planner here (unless new work identified)\n"
    "\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "CYCLE END:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Update completed_tasks\n"
    "- Update next_actions\n"
    "\n"
    "✅ ADD TASKS TO CYCLE PLANNER HERE:\n"
    "- Location: agent_workspaces/{agent_id}/cycle_planner_tasks_YYYY-MM-DD.json\n"
    "- When: After completing current work, before session transition\n"
    "- What: Unfinished work, blockers, next session priorities\n"
    "- Reference: Session Cleanup Template Step 9\n"
    "\n"
    "✅ MESSAGE OTHER AGENTS HERE:\n"
    "- Coordination outcomes → If swarm was engaged, report results\n"
    "- Handoff → If work continues with another agent\n"
    "- Completion → Notify relevant agents of completed work\n"
    "\n"
    "- Commit status.json to git\n"
    "- Create & post devlog automatically\n"
    "- Share learnings to Swarm Brain\n"
    "- Report coordination outcomes if swarm was engaged\n"
    "\n"
    "📖 Full workflow guide: docs/AGENT_OPERATING_CYCLE_WORKFLOW.md\n"
)

# Swarm Force Multiplier Coordination Protocol
SWARM_COORDINATION_TEXT = (
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "🐝 SWARM FORCE MULTIPLIER — USE THE SWARM\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "**CORE PRINCIPLE**: 8 agents working in parallel > 1 agent working alone.\n"
    "Never struggle alone on tasks that can be parallelized.\n\n"
    "**WHEN TO USE SWARM COORDINATION**:\n"
    "✅ Task is too large for one agent (3+ cycles estimated) → BREAK DOWN + DELEGATE\n"
    "✅ Task has multiple independent components → PARALLEL COORDINATION\n"
    "✅ Task spans multiple domains/expertise areas → MULTI-AGENT COORDINATION\n"
    "✅ Multiple agents have relevant expertise → PRIMARY+SUPPORT or PARALLEL\n"
    "✅ Quality would improve with domain expert review → PRIMARY+SUPPORT pattern\n"
    "✅ Parallelization will speed up completion (4-8x faster) → SWARM COORDINATION\n"
    "✅ Even 2-agent tasks can benefit from 3-agent coordination (Primary+Support) → EXPAND\n\n"
    "**COORDINATION PATTERNS (Use These!):**\n"
    "🔹 **Primary+Support**: Executor + Domain Expert (e.g., Agent-1 executes, Agent-3 validates)\n"
    "🔹 **Parallel Work**: 2-4 agents on independent components simultaneously\n"
    "🔹 **Pipeline**: Sequential stages with handoffs (Agent-1 → Agent-2 → Agent-3)\n"
    "🔹 **Swarm**: 3-8 agents combining multiple patterns for maximum effectiveness\n\n"
    "**FORCE MULTIPLIER WORKFLOW**:\n"
    "1. **Task Analysis** (FIRST - before starting work):\n"
    "   - Break task into parallelizable components\n"
    "   - Map components to agent expertise domains\n"
    "   - Identify dependencies and sequencing needs\n"
    "   - Estimate time/complexity per component\n"
    "   - **If task > 1 cycle OR multi-domain → STOP and delegate**\n\n"
    "2. **Immediate Delegation** (if task qualifies):\n"
    "   - **DO THIS FIRST** - Don't start working alone\n"
    "   - Identify target agents by domain expertise:\n"
    "     • Agent-1: Integration & Core Systems\n"
    "     • Agent-2: Architecture & Design\n"
    "     • Agent-3: Infrastructure & DevOps\n"
    "     • Agent-5: Business Intelligence\n"
    "     • Agent-6: Coordination & Communication\n"
    "     • Agent-7: Web Development\n"
    "     • Agent-8: SSOT & System Integration\n"
    "   - Send assignment messages NOW (see commands below)\n"
    "   - **Delegation counts as progress** - commit the assignment messages\n\n"
    "3. **Bilateral Coordination** (default for 2-agent tasks):\n"
    "   - Identify primary partner agent (domain expertise match)\n"
    "   - Send A2A coordination message with task breakdown\n"
    "   - Establish handoff points and integration checkpoints\n"
    "   - Coordinate via status.json updates and A2A pings\n\n"
    "4. **Swarm Assignment** (for 3+ agent tasks):\n"
    "   - Break down into 3-8 parallel sub-tasks\n"
    "   - Assign via messaging system (use --agent flag for each)\n"
    "   - Send all assignments simultaneously (parallel execution)\n"
    "   - Provide clear context, deadlines, and priorities\n"
    "   - Monitor via status.json and coordination messages\n\n"
    "5. **Coordination Commands** (USE THESE):\n"
    "   ```bash\n"
    "   # Assign task to specific agent (DO THIS)\n"
    "   python -m src.services.messaging_cli --agent Agent-X --message \"[Task description with context]\" --priority normal\n"
    "   \n"
    "   # Example: Assign pytest debugging to Agent-7\n"
    "   python -m src.services.messaging_cli --agent Agent-7 --message \"Debug pytest failures in web/ directory\" --priority normal\n"
    "   \n"
    "   # Broadcast coordination message to all agents\n"
    "   python -m src.services.messaging_cli --bulk --message \"Coordination: [context]\" --priority normal\n"
    "   \n"
    "   # Check agent status for coordination\n"
    "   python -m src.services.messaging_cli --check-status\n"
    "   ```\n"
    "   **Remember**: Sending assignment messages IS progress. Commit them.\n\n"
    "5. **Integration & Validation**:\n"
    "   - Collect results from all assigned agents\n"
    "   - Integrate outputs and validate completeness\n"
    "   - Report final status with evidence\n"
    "   - Document successful patterns in Swarm Brain\n\n"
    "**BILATERAL COORDINATION PROTOCOL** (2-agent tasks):\n"
    "- Pair with domain expert agent (check agent specializations)\n"
    "  - Agent-1: Integration & Core Systems\n"
    "  - Agent-2: Architecture & Design\n"
    "  - Agent-3: Infrastructure & DevOps\n"
    "  - Agent-5: Business Intelligence\n"
    "  - Agent-6: Coordination & Communication\n"
    "  - Agent-7: Web Development\n"
    "  - Agent-8: SSOT & System Integration\n"
    "- Send A2A message with:\n"
    "  • Task breakdown and ownership\n"
    "  • Handoff points and dependencies\n"
    "  • Integration checkpoints\n"
    "  • Expected deliverables from each agent\n"
    "- Coordinate via status.json updates and A2A pings\n"
    "- Report coordination outcomes in completion report\n\n"
    "**ANTI-PATTERNS TO AVOID**:\n"
    "❌ Working alone on large tasks (waste of swarm capacity)\n"
    "❌ Sequential assignment (assign task 1, wait, assign task 2...)\n"
    "❌ Over-coordination (too many messages, agents waiting for approval)\n"
    "❌ Ignoring available expertise (not leveraging domain specialists)\n"
    "❌ Starting work before checking if task should be delegated\n"
    "❌ Thinking \"I'll do it myself\" when task spans multiple domains\n\n"
    "**DELEGATION EXAMPLES** (Use these patterns):\n\n"
    "Example 1: Large Refactor\n"
    "  - Task: Refactor 10 files across frontend/backend\n"
    "  - Action: Break into \"frontend refactor\" → Agent-7, \"backend refactor\" → Agent-1\n"
    "  - Message: \"Coordination: Frontend refactor task. You handle web/, I'll handle services/\"\n\n"
    "Example 2: Multi-Domain Feature\n"
    "  - Task: Add feature requiring database + API + frontend\n"
    "  - Action: Agent-1 (API) + Agent-7 (frontend) + Agent-8 (database schema)\n"
    "  - Message: \"Feature coordination: API endpoint assigned to Agent-1, frontend to Agent-7\"\n\n"
    "Example 3: Testing Across Domains\n"
    "  - Task: Add tests for integration spanning 3 modules\n"
    "  - Action: Each module's specialist adds their tests\n"
    "  - Message: \"Test coordination: Each agent adds tests for their domain modules\"\n\n"
    "Example 4: Documentation Update\n"
    "  - Task: Update docs across 5 subsystems\n"
    "  - Action: Each subsystem owner updates their docs\n"
    "  - Message: \"Doc update: Agent-2 (architecture), Agent-3 (infra), Agent-7 (web) - parallel docs\"\n\n"
    "**Remember**: Sending coordination messages IS progress. Commit them!\n\n"
    "**SUCCESS METRICS**:\n"
    "• Time Reduction: 4-8x faster than sequential execution\n"
    "• Coverage: More comprehensive (multiple perspectives)\n"
    "• Quality: Better results (domain expertise applied)\n"
    "• Swarm Utilization: All agents engaged when needed\n\n"
    "**Remember**: If a task is too big for you, don't struggle alone.\n"
    "Break it down, assign via messaging system, coordinate the swarm.\n"
    "🐝 WE. ARE. SWARM. ⚡🔥\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
)

# Discord reporting policy to enforce completion visibility (for S2A/C2A)
DISCORD_REPORTING_TEXT = (
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "DISCORD REPORTING POLICY — CRITICAL VISIBILITY\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "I may not be at the computer. Discord is the primary visibility channel.\n\n"
    "Your completion report MUST be posted to Discord when a task slice finishes.\n\n"
    "When to post:\n"
    "[ ] After completing a slice with a real artifact\n"
    "[ ] After a meaningful commit\n"
    "[ ] After validation/test results\n"
    "[ ] When blocked (post blocker + next step)\n\n"
    "What to include:\n"
    "- Task\n"
    "- Actions Taken\n"
    "- Commit Message (if code touched)\n"
    "- Status (✅ done or 🟡 blocked + next step)\n"
    "- Artifact path(s) if relevant\n\n"
    "Do not send acknowledgment-only messages.\n"
    "The Discord post is the completion handshake.\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "HOW TO POST TO DISCORD (EXACT COMMAND)\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "**Command:**\n"
    "```bash\n"
    "python tools/devlog_manager.py post --agent {recipient} --file <devlog_file.md>\n"
    "```\n\n"
    "**Steps:**\n"
    "1. Create a markdown file: `devlogs/YYYY-MM-DD_agent-X_topic.md`\n"
    "2. Write your completion report in the file\n"
    "3. Run the command above, replacing:\n"
    "   - `{recipient}` with your agent ID (e.g., Agent-1)\n"
    "   - `<devlog_file.md>` with your file path\n\n"
    "**Example:**\n"
    "```bash\n"
    "# Create devlog file\n"
    "echo '# Task Complete\\n\\nActions: ...' > devlogs/2025-12-08_agent-1_task_complete.md\n"
    "# Post to Discord\n"
    "python tools/devlog_manager.py post --agent Agent-1 --file devlogs/2025-12-08_agent-1_task_complete.md\n"
    "```\n\n"
    "**This may be the ONLY way users see your messages!**\n"
)

# D2A (Discord → Agent) response policy - lightweight and human-first
D2A_RESPONSE_POLICY_TEXT = (
    "Discord Response Policy:\n"
    "- This message originated from Discord.\n"
    "- Reply in Discord with your status/answer when you act on this.\n"
    "- Discord is the visibility channel; status-only or chat-only replies do NOT count.\n"
    "- Include evidence: artifact/validation/delegation. Keep replies short and high-signal.\n"
)

# D2A preferred reply format - compact reminder
D2A_REPORT_FORMAT_TEXT = (
    "Preferred Reply Format (short):\n"
    "- Task\n"
    "- Actions Taken\n"
    "- Commit Message (if code touched)\n"
    "- Status (✅ done or 🟡 blocked + next step)\n"
)


def format_d2a_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Format D2A payload with default values."""
    payload.setdefault("interpretation", "Pending agent interpretation.")
    payload.setdefault(
        "actions", "Evaluate request and execute if safe/within scope.")
    payload.setdefault(
        "fallback",
        "Ask for clarification in Discord with one focused question.",
    )
    payload.setdefault("discord_response_policy", D2A_RESPONSE_POLICY_TEXT)
    payload.setdefault("d2a_report_format", D2A_REPORT_FORMAT_TEXT)
    return payload


# Template strings for standard headers. Payloads should be formatted by the caller.
MESSAGE_TEMPLATES: dict[MessageCategory, Any] = {
    # S2A: System-to-Agent (control/ops/cycles)
    MessageCategory.S2A: {
        "CONTROL": (
            "[HEADER] S2A CONTROL\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Context:\n{context}\n\n"
            "Action Required:\n"
            "Produce ONE artifact before next cycle:\n"
            "- Run validator and report results, OR\n"
            "- Commit a small fix with tests passing, OR\n"
            "- Write a 5-bullet technical report.\n\n"
            "No-Reply Policy:\n"
            "- This is a control message. Do not respond unless blocked.\n"
            "- Do not update status.json solely to acknowledge.\n"
            "- Progress resets only on artifacts: commit | test pass | real doc/code delta.\n\n"
            "Priority Behavior:\n"
            "- regular = next cycle; urgent = interrupt current slice.\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{swarm_coordination}\n"
            "{discord_reporting}\n"
            "Evidence format:\n"
            "- Command(s) run + outcome OR\n"
            "- Commit hash + tests status OR\n"
            "- Doc name + 3 key findings\n\n"
            "If blocked:\n"
            "- Assess if task needs swarm coordination (too large? multiple domains?)\n"
            "- If yes: Break down task, assign via messaging system, coordinate swarm\n"
            "- If no: Send 1 message with: blocker + proposed fix + what you need from Captain\n"
        ),
        "STALL_RECOVERY": (
            "[HEADER] S2A STALL RECOVERY — DO NOT REPLY\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "🚨 STOP. DO NOTHING ELSE. COORDINATE NOW. 🚨\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**YOU ARE STALLED. THIS IS YOUR SIGNAL TO USE THE SWARM, NOT WORK ALONE.**\n\n"
            "**MANDATORY FIRST ACTION (NON-NEGOTIABLE)**:\n"
            "→ Send 2-4 coordination messages RIGHT NOW\n"
            "→ This IS your required output - delegation messages count as progress\n"
            "→ If you haven't sent coordination messages today, this is MANDATORY\n\n"
            "**VIOLATION**: Working solo when stalled = wasted swarm capacity = system failure\n"
            "**REQUIREMENT**: Minimum 1 coordination message per day (stall recovery = 2-4 minimum)\n\n"
            "Reason:\n{context}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "⚡ IMMEDIATE ACTION: COORDINATION REQUIRED ⚡\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**STEP 1: Answer this question RIGHT NOW (30 seconds):**\n\n"
            "**Have you sent ANY coordination messages today?**\n"
            "   → If NO: Send 2-4 coordination messages NOW (mandatory - do this before anything else)\n"
            "   → If YES: Send 1-2 more coordination messages NOW (stall recovery requires more)\n\n"
            "**STEP 2: If task exists, break it down and delegate:**\n"
            "   1. Identify 2-4 parallel components\n"
            "   2. Map to domain experts (see agent list below)\n"
            "   3. Send coordination message to each agent\n"
            "   4. Commit the messages (they ARE progress)\n\n"
            "**STEP 3: If no clear task, find coordination opportunities:**\n"
            "   - Review other agents' status.json for handoff opportunities\n"
            "   - Check for unassigned work that needs parallel execution\n"
            "   - Identify blockers that need multi-agent coordination\n"
            "   - Send coordination offers to relevant agents\n\n"
            "**COMMAND TO USE** (copy/paste this, replace Agent-X and message):\n"
            "```bash\n"
            "python -m src.services.messaging_cli --agent Agent-X --message \"[task component]\" --priority normal\n"
            "```\n"
            "**Send 2-4 of these messages NOW. Commit them. This IS your output.**\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "📊 COORDINATION QUOTA ENFORCEMENT\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**DAILY MINIMUM**: 1 coordination message per day (ABSOLUTE MINIMUM)\n"
            "**STALL RECOVERY MINIMUM**: 2-4 coordination messages (REQUIRED WHEN STALLED)\n"
            "**TARGET**: 3-5 coordination messages per day (GOOD swarm utilization)\n"
            "**EXCELLENT**: 5+ coordination messages per day (EXCELLENT force multiplier usage)\n\n"
            "**TODAY'S STATUS CHECK** (Answer NOW):\n"
            "   → Count: How many coordination messages have YOU sent today?\n"
            "   → If 0: Send 4 coordination messages NOW (mandatory)\n"
            "   → If 1: Send 2-3 more coordination messages NOW (stall recovery requires more)\n"
            "   → If 2+: Send 1-2 more coordination messages (stall = need more coordination)\n\n"
            "**VIOLATION = WASTE**: Working alone when stalled = you're wasting 7 other agents\n"
            "**REQUIREMENT = COORDINATION**: Stall recovery = coordination is your job, not solo work\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "⚡ DEFAULT ACTION: DELEGATE TO SWARM (USE THIS 95% OF THE TIME WHEN STALLED)\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**RULE**: If you're stalled, you're STALLED because you need the swarm, not because you need to work alone.\n\n"
            "**IMMEDIATE STEPS** (Do this NOW - this IS your output):\n"
            "1. **Identify coordination opportunity** (choose one):\n"
            "   a) Break your stalled task into 2-4 parallel components\n"
            "   b) Find unassigned work needing parallel execution\n"
            "   c) Identify blockers requiring multi-agent coordination\n"
            "   d) Review other agents' work for handoff opportunities\n\n"
            "2. **Map to domain experts** (use these agents):\n"
            "   • Agent-1: Integration & Core Systems\n"
            "   • Agent-2: Architecture & Design\n"
            "   • Agent-7: Web Development\n"
            "   • Agent-8: SSOT & System Integration\n"
            "   • Agent-3: Infrastructure & DevOps\n"
            "   • Agent-5: Business Intelligence\n"
            "   • Agent-6: Coordination & Communication\n\n"
            "3. **Send coordination messages** (one per agent, 2-4 messages minimum):\n"
            "   ```bash\n"
            "   python -m src.services.messaging_cli --agent Agent-X --message \"[component task]\" --priority normal\n"
            "   ```\n\n"
            "4. **Commit the messages** (they ARE progress - this IS your output):\n"
            "   ```bash\n"
            "   git add -A\n"
            "   git commit -m \"chore: Send coordination messages - [brief description]\"\n"
            "   ```\n\n"
            "5. **Post to Discord** (coordination IS work - report it):\n"
            "   ```bash\n"
            "   python tools/devlog_poster.py --agent {recipient} --file devlogs/YYYY-MM-DD_agent-X_coordination.md\n"
            "   ```\n\n"
            "**This IS your required output for this stall recovery**\n"
            "**Delegation messages ARE valid progress** - they count as work output\n"
            "**Coordination IS progress** - sending 2-4 messages IS doing your job\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "📊 DAILY COORDINATION TRACKING\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**COORDINATION QUOTA**: Send at least 1 coordination message per day\n"
            "**TODAY'S STATUS**: Have you sent any coordination messages today?\n\n"
            "If NO → Your next action MUST be coordination/delegation\n"
            "If YES → Continue using swarm for remaining tasks\n\n"
            "**SUCCESS METRICS**:\n"
            "- 1+ coordination messages/day = Minimum requirement\n"
            "- 2-4 coordination messages/day = Good swarm utilization\n"
            "- 5+ coordination messages/day = Excellent force multiplier usage\n\n"
            "**ANTI-PATTERN**: Working alone on tasks that could be parallelized = wasted swarm capacity\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "❌ SOLO WORK IS FORBIDDEN WHEN STALLED (EXCEPTIONS ONLY BELOW)\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**RULE**: When stalled, coordination IS your work. Solo work is ONLY allowed if:\n"
            "   1. You've already sent 3+ coordination messages today, AND\n"
            "   2. No coordination opportunities exist, AND\n"
            "   3. Task is confirmed single-agent scope (verified with Captain)\n\n"
            "**If you haven't sent 2+ coordination messages today, solo work is FORBIDDEN**\n"
            "**Your job when stalled is to coordinate, not work alone**\n\n"
            "**ONLY IF exceptions above are met, these alternatives are valid:**\n"
            "1. Commit a real slice (ONLY after coordination quota met)\n"
            "2. Run and record a validation result (ONLY after coordination quota met)\n"
            "3. Produce a short artifact report with real delta (ONLY after coordination quota met)\n\n"
            "**VIOLATION WARNING**: Working solo without meeting coordination quota = system failure\n\n"
            "No-Reply Policy:\n"
            "- Do not respond to this message.\n"
            "- Chat replies do not count as progress.\n"
            "- status.json-only updates do not count as progress.\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{swarm_coordination}\n"
            "{discord_reporting}\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "🚨 COORDINATION MANDATE (ABSOLUTE REQUIREMENT)\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "**STALL RECOVERY = COORDINATION REQUIREMENT**\n\n"
            "**MANDATORY FIRST ACTION**: Send 2-4 coordination messages NOW\n"
            "**This is NOT optional** - If you're stalled, you MUST coordinate\n"
            "**This IS your work** - Sending coordination messages IS doing your job\n\n"
            "**COORDINATION EXAMPLES** (use these patterns):\n"
            "- \"Agent-X, handling [component]. Coordinate on [handoff point]?\"\n"
            "- \"Agent-X, [task] needs [expertise]. Can you take this component?\"\n"
            "- \"Agent-X, breaking [large task] into pieces. You handle [component]?\"\n"
            "- \"Agent-X, [blocker] needs coordination. Can we parallelize [aspect]?\"\n\n"
            "**REQUIREMENT**: Send 2-4 messages like the examples above\n"
            "**COMMIT**: These messages ARE progress - commit them\n"
            "**REPORT**: Post to Discord - coordination IS work output\n\n"
            "**ANTI-PATTERN**: \"I'll work alone on this stalled task\" = VIOLATION\n"
            "**CORRECT PATTERN**: \"I'm stalled, so I'm coordinating with 2-4 agents\" = CORRECT\n\n"
            "Escalation:\n{fallback}\n"
            "#STALL-RECOVERY #NO-REPLY #PROGRESS-ONLY #ARTIFACT-REQUIRED #SWARM-FORCE-MULTIPLIER\n"
        ),
        "HARD_ONBOARDING": (
            "[HEADER] S2A HARD ONBOARDING\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Context:\n{context}\n\n"
            "First Actions:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "SOFT_ONBOARDING": (
            "[HEADER] S2A SOFT ONBOARDING\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Identity:\n"
            "You are {recipient}. Act as this agent for this message.\n"
            "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
            "No-Ack Policy:\n"
            "- Do not send empty acknowledgments.\n"
            "- Respond with artifact/result or 1 blocker (blocker + proposed fix + owner).\n\n"
            "Context:\n{context}\n\n"
            "Cleanup / Alignment Actions (do one real output):\n{actions}\n\n"
            "Evidence format:\n"
            "- Commit hash + tests status, or\n"
            "- Doc path + 3 key changes, or\n"
            "- Validation command + outcome.\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{discord_reporting}\n"
            "If blocked:\n{fallback}\n"
        ),
        "PASSDOWN": (
            "[HEADER] S2A PASSDOWN\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "What changed:\n{context}\n\n"
            "Your next slice:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "TELEPHONE_STATUS_GAME": (
            "[HEADER] S2A TELEPHONE STATUS GAME\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Chain Context:\n{context}\n\n"
            "Your move:\n{actions}\n\n"
            "Rules:\n"
            "- Pass actionable state + next slice.\n"
            "- No acknowledgement-only responses.\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "TASK_CYCLE": (
            "[HEADER] S2A TASK CYCLE\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Cycle Objective:\n{context}\n\n"
            "Assigned Slice:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "FSM_UPDATE": (
            "[HEADER] S2A FSM UPDATE\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "State Change:\n{context}\n\n"
            "Required Behavior:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "DEBATE_CYCLE": (
            "[HEADER] S2A DEBATE CYCLE\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Debate Topic:\n{topic}\n\n"
            "Role/Position:\n{role}\n\n"
            "Context:\n{context}\n\n"
            "Rules:\n{rules}\n\n"
            "Deliverable:\n{deliverable}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
            "#DEBATE #S2A\n"
        ),
        "CYCLE_V2": (
            "[HEADER] C2A CYCLE V2 - MAX PRODUCTIVITY\n"
            "From: Captain Agent-4\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "MISSION\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{mission}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "DEFINITION OF DONE (DoD)\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{dod}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "CONSTRAINTS\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "SSOT: {ssot_constraint}\n"
            "V2: {v2_constraint}\n"
            "Touch Surface: {touch_surface}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "VALIDATION REQUIRED\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{validation_required}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "PRIORITY\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{priority_level}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "HANDOFF EXPECTATION\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{handoff_expectation}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "AGENT OPERATING CYCLE V2\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "A) Pre-Cycle Rules (Hard Guards):\n"
            "   • WIP = 1 (only one active objective per cycle)\n"
            "   • DoD required (if missing, write 3-line DoD)\n"
            "   • SSOT boundaries first (confirm where truth lives)\n"
            "   • V2 Compliance gate (split if file exceeds limits)\n\n"
            "B) Start of Cycle (Fast):\n"
            "   1. Inbox sweep (max 60 seconds)\n"
            "   2. Claim task: --get-next-task --agent {recipient}\n"
            "   3. Pull last 1 relevant pattern from Swarm Brain\n"
            "   4. Write Micro-Plan (3 bullets max):\n"
            "      - Change target\n"
            "      - Validation method\n"
            "      - Exit criteria\n"
            "   5. Update status.json with phase, mission, micro-plan, DoD\n\n"
            "C) Execution Burst (Timeboxed):\n"
            "   1. Implement smallest viable change toward DoD\n"
            "   2. If scope expands: split into subtask, notify Captain\n"
            "   3. Keep changes localized and typed\n"
            "   4. No refactors unless they reduce immediate risk\n\n"
            "D) Mid-Cycle Checkpoint (Anti-Drift):\n"
            "   After first meaningful change:\n"
            "   • Still aligned with DoD?\n"
            "   • Still within SSOT?\n"
            "   • Still within V2?\n"
            "   If no: adjust plan, report correction\n\n"
            "E) Validation First-Class (Shift Left):\n"
            "   1. Run tests/lint/verification for touched surface\n"
            "   2. If tests missing: add minimal tests\n"
            "   3. Log evidence (command/output summary)\n\n"
            "F) Reporting Contract (No Empty Replies):\n"
            "   Must include:\n"
            "   • What changed (artifact-level)\n"
            "   • Validation evidence\n"
            "   • Measurable result\n"
            "   • Next recommended action\n\n"
            "G) Documentation:\n"
            "   • status.json updated (COMPLETE/BLOCKED/HANDOFF_READY)\n"
            "   • Discord devlog posted for completed actions\n\n"
            "H) Escalation Thresholds:\n"
            "   Escalate when:\n"
            "   • DoD unclear beyond 2 reasonable assumptions\n"
            "   • SSOT conflict detected\n"
            "   • Cross-agent dependency required\n"
            "   • Change affects >2 modules/domains\n\n"
            "I) Swarm Force Multiplier (CRITICAL):\n"
            "   Before starting execution:\n"
            "   • Assess task size: Is this a force multiplier opportunity?\n"
            "   • If task is large (3+ cycles) or spans multiple domains:\n"
            "     → Break down into parallelizable components\n"
            "     → Assign to 2-8 agents via messaging system\n"
            "     → Coordinate parallel execution\n"
            "     → Integrate results\n"
            "   • Remember: 8 agents working in parallel > 1 agent working alone\n"
            "   • See Swarm Coordination Protocol below for details\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "SUCCESS METRICS PER CYCLE\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "• Output: ≥1 merged-ready artifact OR ≥1 validated decision\n"
            "• Validation: evidence included every time\n"
            "• Drift: zero off-mission edits\n"
            "• WIP: never >1\n"
            "• Swarm Utilization: Agents engaged when task requires coordination\n\n"
            "{swarm_coordination}\n"
            "If blocked:\n{fallback}\n"
            "#CYCLE_V2 #C2A #SWARM-COORDINATION\n"
        ),
    },
    # D2A: Discord-to-Agent (lightweight, human-first)
    MessageCategory.D2A: (
        "[HEADER] D2A DISCORD INTAKE\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Origin:\n"
        "- Discord → Agent intake\n\n"
        "User Message:\n"
        "{content}\n\n"
        "Interpretation (agent):\n"
        "{interpretation}\n\n"
        "Proposed Action:\n"
        "{actions}\n\n"
        "Operating Cycle (fast reminder):\n"
        "1) Claim → 2) Sync → 3) Slice → 4) Execute → 5) Validate → 6) Commit → 7) Report evidence\n"
        "- No chat-only replies; status.json-only updates do NOT count as progress.\n"
        "- Report with artifact/validation/delegation in Discord.\n\n"
        "{discord_response_policy}\n"
        "{d2a_report_format}\n"
        "Devlog Command (for recipient):\n"
        "python tools/devlog_poster.py --agent {recipient} --file <devlog_path>\n\n"
        "If clarification needed:\n"
        "{fallback}\n"
        "#DISCORD #D2A\n"
    ),
    # C2A: Captain-to-Agent
    MessageCategory.C2A: (
        "[HEADER] C2A CAPTAIN DIRECTIVE\n"
        "From: Captain Agent-4\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Identity:\n"
        "You are {recipient}. Act as this agent for this directive.\n"
        "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "📋 MANDATORY 7-STEP OPERATING CYCLE\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**1. CLAIM** → Claim your task assignment or identify what to work on\n"
        "- Review this C2A directive carefully\n"
        "- Acknowledge task and update status.json with task details\n"
        "- **CRITICAL FIRST STEP**: Before starting, assess if this should be delegated\n\n"
        "**2. SYNC** → Sync with current state and gather context\n"
        "- **MANDATORY**: Search codebase for existing architecture/solutions FIRST\n"
        "  * Look for similar patterns, existing utilities, or related code\n"
        "  * Check documentation for established approaches\n"
        "  * Search for duplicate functionality before creating new files\n"
        "  * This prevents duplication and technical debt\n"
        "- Read relevant files/code for your task\n"
        "- Check previous work in status.json\n"
        "- Review any related documentation\n"
        "- **Action**: Understand FULL context and EXISTING architecture before starting\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔮 PROACTIVE RISK ASSESSMENT (BEFORE STARTING)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY: Assess potential risks and mitigation strategies before proceeding:**\n\n"
        "**1. Technical Risks**: What could go wrong technically?\n"
        "   - Dependencies that might fail?\n"
        "   - Integration points that could break?\n"
        "   - Performance or scalability concerns?\n"
        "   - Breaking changes to existing systems?\n\n"
        "**2. Scope Risks**: What could cause scope expansion?\n"
        "   - Hidden complexity in requirements?\n"
        "   - Dependencies on incomplete systems?\n"
        "   - Unknown domain requirements?\n"
        "   - Unclear acceptance criteria?\n\n"
        "**3. Coordination Risks**: What coordination challenges might arise?\n"
        "   - Blockers from other agents?\n"
        "   - Integration conflicts?\n"
        "   - Timeline misalignment?\n"
        "   - Competing priorities?\n\n"
        "**4. Quality Risks**: What could impact deliverable quality?\n"
        "   - Insufficient test coverage?\n"
        "   - Missing edge cases?\n"
        "   - Technical debt introduction?\n"
        "   - Architecture compliance issues?\n\n"
        "**5. Mitigation Strategies**: For each identified risk:\n"
        "   - **Preventive Action**: How to avoid the risk?\n"
        "   - **Contingency Plan**: What to do if risk occurs?\n"
        "   - **Early Warning Indicators**: How to detect risk early?\n\n"
        "**Decision Framework**:\n"
        "- If risks are manageable → Proceed with mitigation strategies\n"
        "- If risks are high → Escalate to Captain or coordinate with domain experts\n"
        "- If risks reveal scope expansion → STOP, reassess, and coordinate\n\n"
        "**AGI-Level Aspect**: Agents anticipate problems before they occur, not just react to them.\n\n"
        "**3. SLICE** → Break work into manageable slices\n"
        "- Identify smallest viable unit of work\n"
        "- Plan steps to complete the task\n"
        "- Identify dependencies and blockers\n"
        "- Estimate effort (should be <3 hours per slice)\n"
        "- **Action**: Create execution plan, update status.json with plan\n\n"
        "**4. EXECUTE** → Execute the work slice\n"
        "- Implement code changes, fixes, or features\n"
        "- **AVOID EXCESSIVE DOCUMENTATION**: Only document what's necessary\n"
        "  * Don't create redundant docs if code is self-explanatory\n"
        "  * Don't duplicate information already in existing docs\n"
        "  * Focus on code quality over documentation volume\n"
        "- Follow V2 compliance standards (<300 lines per file)\n"
        "- Write tests if applicable\n"
        "- **Action**: Complete the work slice, produce tangible output\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔄 MID-CYCLE RE-ASSESSMENT (DURING EXECUTION)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY: Re-assess task scope and approach after execution:**\n\n"
        "**When to Re-Assess**:\n"
        "- After completing 50% of estimated work\n"
        "- When encountering unexpected complexity\n"
        "- When dependencies reveal new requirements\n"
        "- When coordination reveals scope expansion\n"
        "- When risks identified earlier materialize\n\n"
        "**Re-Assessment Questions**:\n"
        "1. **Scope Validation**: Is task scope still accurate?\n"
        "   - Has scope expanded beyond original directive?\n"
        "   - Are requirements clearer or more complex than expected?\n"
        "   - Are there hidden dependencies?\n\n"
        "2. **Progress Validation**: Are we on track?\n"
        "   - Is timeline still realistic?\n"
        "   - Is effort estimate still accurate?\n"
        "   - Are we progressing as planned?\n\n"
        "3. **Approach Validation**: Is our approach still effective?\n"
        "   - Is current approach working?\n"
        "   - Do we need to pivot strategy?\n"
        "   - Are there better patterns/solutions discovered?\n\n"
        "4. **Blocker Detection**: Have any blockers emerged?\n"
        "   - Technical blockers?\n"
        "   - Coordination blockers?\n"
        "   - Dependency blockers?\n"
        "   - Knowledge gaps?\n\n"
        "5. **Coordination Needs**: Do we need to coordinate?\n"
        "   - Should this still be solo execution?\n"
        "   - Do we need to delegate parts to swarm?\n"
        "   - Do we need domain expert input?\n\n"
        "**Decision Framework**:\n"
        "- **Continue**: If scope/approach/progress are on track → Continue to Validate phase\n"
        "- **Pivot**: If approach needs adjustment → Adjust strategy, continue execution\n"
        "- **Escalate**: If blocked or high-risk → Send A2C message with blocker + proposed fix\n"
        "- **Coordinate**: If scope expanded → STOP, break down, delegate to swarm\n\n"
        "**AGI-Level Aspect**: Agents adapt dynamically to changing conditions, not just follow initial plan.\n\n"
        "**5. VALIDATE** → Validate your work\n"
        "- Run linting: `python -m py_compile <file>`\n"
        "- Test functionality if applicable\n"
        "- Verify V2 compliance (file size, structure)\n"
        "- Check for breaking changes\n"
        "- **Action**: Ensure quality before committing\n\n"
        "**6. COMMIT** → Commit your work with clear message\n"
        "- Stage changes: `git add <files>`\n"
        "- Commit with descriptive message: `git commit -m \"feat: description\"`\n"
        "- Follow conventional commit format (feat/fix/docs/refactor/test/chore)\n"
        "- **Action**: Save progress to repository\n\n"
        "**7. REPORT EVIDENCE** → Report progress with evidence\n"
        "- Update status.json with completion timestamp\n"
        "- Report to Captain/coordinator if required\n"
        "- Document outcomes (what was done, what's next)\n"
        "- **Action**: Make progress visible and trackable\n\n"
        "**🔄 CYCLE RULES:**\n"
        "- **Never skip steps** - Each step is required\n"
        "- **No chat-only replies** - Must produce artifacts (code/docs/tests)\n"
        "- **Status.json updates alone don't count** - Must have tangible output\n"
        "- **Complete cycles** - Finish all 7 steps before starting new work\n"
        "- **Maintain momentum** - When one cycle ends, immediately start the next\n\n"
        "No-Ack Policy:\n"
        "- Do not send empty acknowledgments.\n"
        "- Respond with deliverable/evidence or 1 blocker (blocker + proposed fix + owner).\n\n"
        "{discord_reporting}\n"
        "Task:\n{task}\n\n"
        "Context:\n{context}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🐝 BILATERAL COORDINATION PROTOCOL (MANDATORY)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**C2A messages establish bilateral coordination between Captain and Agent.**\n\n"
        "**What This Means**:\n"
        "- Captain (Agent-4) is your primary coordination partner for this directive\n"
        "- You can reply via A2C (Agent-to-Captain) messaging for coordination\n"
        "- Use A2C for: Status updates, blockers, coordination requests, completion reports\n"
        "- **Expected Response**: Not just acknowledgment, but ACTION with evidence\n\n"
        "**Bilateral Coordination Workflow**:\n"
        "1. Receive C2A directive (this message)\n"
        "2. Assess task scope and dependencies\n"
        "3. **FIRST**: Check if task requires swarm coordination (see Force Multiplier below)\n"
        "4. Execute operating cycle (7 steps above)\n"
        "5. Report completion via A2C message with evidence (when done or blocked)\n\n"
        "**When to Send A2C Response**:\n"
        "- ✅ When task is complete with evidence\n"
        "- ✅ When blocked and need Captain's input\n"
        "- ✅ When task scope expands beyond original directive\n"
        "- ✅ When coordination with other agents is needed\n"
        "- ❌ NOT for simple acknowledgments (only action + evidence)\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🚀 SWARM FORCE MULTIPLIER ASSESSMENT (FIRST STEP)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY BEFORE STARTING WORK**: Answer these questions:\n\n"
        "1. **Task Size Assessment**:\n"
        "   - Will this task take >1 cycle? (3+ hours estimated?)\n"
        "   - If YES → STOP, break down and delegate parts to swarm\n\n"
        "2. **Domain Scope Assessment**:\n"
        "   - Does this touch 2+ domains/expertise areas?\n"
        "   - If YES → STOP, coordinate with domain experts\n\n"
        "3. **Expertise Match Assessment**:\n"
        "   - Is another agent better suited for this task?\n"
        "   - If YES → STOP, message them to take over\n\n"
        "4. **Parallelization Assessment**:\n"
        "   - Can this be parallelized across 2-8 agents?\n"
        "   - If YES → STOP, break down and assign to swarm\n\n"
        "5. **Solo Execution Check**:\n"
        "   - ONLY if ALL answers above are NO → proceed solo\n"
        "   - If ANY answer is YES → Use Swarm Coordination Protocol (see below)\n\n"
        "**Force Multiplier Principle**:\n"
        "- 8 agents working in parallel > 1 agent working alone\n"
        "- Never struggle alone on tasks that can be parallelized\n"
        "- Coordination IS progress - sending delegation messages counts as work\n\n"
        "{swarm_coordination}\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔍 ARCHITECTURE & ANTI-DUPLICATION PROTOCOL\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY BEFORE CREATING NEW FILES**:\n\n"
        "1. **Search for Existing Solutions** (5-10 minutes):\n"
        "   - Search codebase for similar patterns/utilities\n"
        "   - Check if functionality already exists\n"
        "   - Look for related code in same domain\n"
        "   - Review existing architecture patterns\n\n"
        "2. **Avoid Duplication**:\n"
        "   - Don't create new files if similar functionality exists\n"
        "   - Extend existing code rather than duplicating\n"
        "   - Reuse utilities and patterns already in codebase\n"
        "   - This reduces technical debt and maintenance burden\n\n"
        "3. **Documentation Balance**:\n"
        "   - **Avoid excessive documentation** - Code should be self-explanatory\n"
        "   - Only document what's truly necessary:\n"
        "     * Complex business logic that's not obvious\n"
        "     * API contracts and public interfaces\n"
        "     * Architecture decisions and trade-offs\n"
        "   - Don't duplicate information already in code/comments\n"
        "   - Focus on code quality over documentation volume\n\n"
        "4. **Technical Debt Prevention**:\n"
        "   - Before creating new files, ensure they're truly needed\n"
        "   - Consolidate related functionality when possible\n"
        "   - Follow existing patterns and conventions\n"
        "   - Reduce future maintenance burden\n\n"
        "**Success Metrics**:\n"
        "- Zero duplicate functionality created\n"
        "- Reused existing utilities/patterns where applicable\n"
        "- Minimal necessary documentation (code-first approach)\n"
        "- Reduced technical debt, not increased it\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "📊 OPERATING PROCEDURES (STANDARD WORKFLOW)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "- **State Scan** (before execution):\n"
        "  - Check relevant agent statuses for dependencies/overlap\n"
        "  - Check project state/SSOT for current truth, active blockers, and recent changes\n"
        "  - Identify available agents for coordination if needed\n\n"
        "- **Learnings → Swarm Brain**:\n"
        "  - If you discover a new pattern, fix, or rule, add a short Swarm Brain entry\n"
        "  - Document successful coordination patterns\n\n"
        "- **Scope guard**:\n"
        "  - If this touches >2 domains, use swarm coordination (break down + assign)\n"
        "  - Don't work alone on large multi-domain tasks\n\n"
        "- **No chatter**:\n"
        "  - No receipt message required\n"
        "  - Only message if blocked or when done with evidence\n"
        "  - Coordination messages should be actionable, not acknowledgments\n\n"
        "{cycle_checklist}\n"
        "Deliverable:\n"
        "1) {deliverable}\n"
        "2) Coordination outputs / pings / handoffs (if swarm engaged)\n"
        "3) Short status note (3 bullets max)\n\n"
        "Checkpoint:\n"
        "- {eta}\n\n"
        "Evidence format:\n"
        "- Artifact link/ID + last updated timestamp\n"
        "- Pings/handoffs with message IDs/channel refs\n"
        "- 3-bullet status\n\n"
        "Priority Behavior:\n"
        "- regular = next cycle\n"
        "- urgent = interrupt current slice if safe; otherwise finish current micro-task then switch\n\n"
        "If blocked:\n"
        "- Send A2C message with: blocker + proposed fix + what you need from Captain.\n"
        "How to respond:\n"
        "- When done: Send A2C message with deliverable + evidence.\n"
        "- Use bilateral coordination protocol for all communication.\n"
    ),
    # A2A: Agent-to-Agent (also handles A2C: Agent-to-Captain)
    MessageCategory.A2A: (
        "[HEADER] A2A COORDINATION — BILATERAL SWARM COORDINATION\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Identity:\n"
        "You are {recipient}. Act as this agent for this message.\n"
        "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🐝 BILATERAL COORDINATION PROTOCOL\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**This message establishes bilateral coordination between agents (A2A) or Agent-to-Captain (A2C).**\n\n"
        "**Message Types**:\n"
        "- **A2A (Agent-to-Agent)**: Coordination between two agents to parallelize work\n"
        "- **A2C (Agent-to-Captain)**: Agent reporting/completing C2A directive or requesting Captain coordination\n\n"
        "**What This Means**:\n"
        "- Sender is requesting your expertise/participation to leverage swarm force multiplication\n"
        "- This is a bilateral partnership - both agents coordinate and share responsibility\n"
        "- **Expected Response**: Not just acknowledgment, but ACTION with evidence\n"
        "- Coordination messages establish ongoing bilateral communication channel\n\n"
        "**Bilateral Coordination Workflow**:\n"
        "1. Receive coordination request (this message)\n"
        "2. Assess if you can contribute (domain expertise match?)\n"
        "3. If YES: Accept + provide ETA + coordinate handoff points\n"
        "4. If NO: Propose alternative agent or decline with reason\n"
        "5. Establish ongoing coordination channel for this work\n"
        "6. Execute operating cycle (7 steps below)\n"
        "7. Report coordination outcomes in completion report\n\n"
        "**Coordination Principles**:\n"
        "- 2 agents working in parallel > 1 agent working alone\n"
        "- Coordinate early, integrate frequently\n"
        "- Share context via status.json and A2A/A2C messages\n"
        "- Report coordination outcomes to Captain (if A2C) or both agents (if A2A)\n\n"
        "No-Ack Policy:\n"
        "- Do not send empty acknowledgments.\n"
        "- Respond with action/result or 1 blocker (blocker + proposed fix + owner).\n\n"
        "How to respond using the Unified Messaging CLI (SSOT):\n"
        "- Reply to this sender as {recipient} (A2A):\n"
        "  `python -m src.services.messaging_cli --agent {sender} -m \"<your response>\" --type text --category a2a`\n"
        "- Escalate or complete to Captain (A2C):\n"
        "  `python -m src.services.messaging_cli --agent Agent-4 -m \"<completion or blocker + evidence>\" --type text --category a2c`\n\n"
        "Your response SHOULD include:\n"
        "- Context – what you understood from this request.\n"
        "- Action – what you did or will do next (with ETA).\n"
        "- Evidence – links to PRs, tests, logs, or docs.\n"
        "- Blocker (optional) – a single clear blocker + your proposed next step.\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "📋 MANDATORY 7-STEP OPERATING CYCLE\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**1. CLAIM** → Claim your coordination task\n"
        "- Review coordination request carefully\n"
        "- Acknowledge task and update status.json with task details\n"
        "- **CRITICAL FIRST STEP**: Assess if this should involve additional agents\n\n"
        "**2. SYNC** → Sync with current state and gather context\n"
        "- **MANDATORY**: Search codebase for existing architecture/solutions FIRST\n"
        "  * Look for similar patterns, existing utilities, or related code\n"
        "  * Check documentation for established approaches\n"
        "  * Search for duplicate functionality before creating new files\n"
        "  * This prevents duplication and technical debt\n"
        "- Read relevant files/code for your task\n"
        "- Check sender's status.json for context\n"
        "- Review any related documentation\n"
        "- **Action**: Understand FULL context and EXISTING architecture before starting\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔮 PROACTIVE RISK ASSESSMENT (BEFORE STARTING)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY: Assess potential risks and mitigation strategies before proceeding:**\n\n"
        "**1. Technical Risks**: What could go wrong technically?\n"
        "   - Dependencies that might fail?\n"
        "   - Integration points that could break?\n"
        "   - Performance or scalability concerns?\n"
        "   - Breaking changes to existing systems?\n\n"
        "**2. Scope Risks**: What could cause scope expansion?\n"
        "   - Hidden complexity in requirements?\n"
        "   - Dependencies on incomplete systems?\n"
        "   - Unknown domain requirements?\n"
        "   - Unclear acceptance criteria?\n\n"
        "**3. Coordination Risks**: What coordination challenges might arise?\n"
        "   - Blockers from coordinator or other agents?\n"
        "   - Integration conflicts?\n"
        "   - Timeline misalignment?\n"
        "   - Competing priorities?\n\n"
        "**4. Quality Risks**: What could impact deliverable quality?\n"
        "   - Insufficient test coverage?\n"
        "   - Missing edge cases?\n"
        "   - Technical debt introduction?\n"
        "   - Architecture compliance issues?\n\n"
        "**5. Mitigation Strategies**: For each identified risk:\n"
        "   - **Preventive Action**: How to avoid the risk?\n"
        "   - **Contingency Plan**: What to do if risk occurs?\n"
        "   - **Early Warning Indicators**: How to detect risk early?\n\n"
        "**Decision Framework**:\n"
        "- If risks are manageable → Proceed with mitigation strategies\n"
        "- If risks are high → Escalate to coordinator or coordinate with domain experts\n"
        "- If risks reveal scope expansion → STOP, reassess, and coordinate\n\n"
        "**AGI-Level Aspect**: Agents anticipate problems before they occur, not just react to them.\n\n"
        "**3. SLICE** → Break work into manageable slices\n"
        "- Identify smallest viable unit of work\n"
        "- Plan steps to complete the task\n"
        "- Identify dependencies and handoff points with coordinator\n"
        "- Estimate effort (should be <3 hours per slice)\n"
        "- **Action**: Create execution plan, coordinate with sender, update status.json\n\n"
        "**4. EXECUTE** → Execute the work slice\n"
        "- Implement code changes, fixes, or features\n"
        "- **AVOID EXCESSIVE DOCUMENTATION**: Only document what's necessary\n"
        "  * Don't create redundant docs if code is self-explanatory\n"
        "  * Don't duplicate information already in existing docs\n"
        "  * Focus on code quality over documentation volume\n"
        "- Follow V2 compliance standards (<300 lines per file)\n"
        "- Write tests if applicable\n"
        "- **Action**: Complete the work slice, produce tangible output\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔄 MID-CYCLE RE-ASSESSMENT (DURING EXECUTION)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY: Re-assess task scope and approach after execution:**\n\n"
        "**When to Re-Assess**:\n"
        "- After completing 50% of estimated work\n"
        "- When encountering unexpected complexity\n"
        "- When dependencies reveal new requirements\n"
        "- When coordination reveals scope expansion\n"
        "- When risks identified earlier materialize\n\n"
        "**Re-Assessment Questions**:\n"
        "1. **Scope Validation**: Is task scope still accurate?\n"
        "   - Has scope expanded beyond original coordination request?\n"
        "   - Are requirements clearer or more complex than expected?\n"
        "   - Are there hidden dependencies?\n\n"
        "2. **Progress Validation**: Are we on track?\n"
        "   - Is timeline still realistic?\n"
        "   - Is effort estimate still accurate?\n"
        "   - Are we progressing as planned with coordinator?\n\n"
        "3. **Approach Validation**: Is our approach still effective?\n"
        "   - Is current approach working?\n"
        "   - Do we need to pivot strategy?\n"
        "   - Are there better patterns/solutions discovered?\n\n"
        "4. **Blocker Detection**: Have any blockers emerged?\n"
        "   - Technical blockers?\n"
        "   - Coordination blockers with sender?\n"
        "   - Dependency blockers?\n"
        "   - Knowledge gaps?\n\n"
        "5. **Coordination Needs**: Do we need additional coordination?\n"
        "   - Should this involve additional agents?\n"
        "   - Do we need to expand to swarm coordination?\n"
        "   - Do we need domain expert input?\n\n"
        "**Decision Framework**:\n"
        "- **Continue**: If scope/approach/progress are on track → Continue to Validate phase\n"
        "- **Pivot**: If approach needs adjustment → Adjust strategy, continue execution\n"
        "- **Escalate**: If blocked or high-risk → Send A2A/A2C message with blocker + proposed fix\n"
        "- **Coordinate**: If scope expanded → STOP, break down, expand to swarm coordination\n\n"
        "**AGI-Level Aspect**: Agents adapt dynamically to changing conditions, not just follow initial plan.\n\n"
        "**5. VALIDATE** → Validate your work\n"
        "- Run linting: `python -m py_compile <file>`\n"
        "- Test functionality if applicable\n"
        "- Verify V2 compliance (file size, structure)\n"
        "- Check for breaking changes\n"
        "- **Action**: Ensure quality before committing\n\n"
        "**6. COMMIT** → Commit your work with clear message\n"
        "- Stage changes: `git add <files>`\n"
        "- Commit with descriptive message: `git commit -m \"feat: description\"`\n"
        "- Follow conventional commit format (feat/fix/docs/refactor/test/chore)\n"
        "- **Action**: Save progress to repository\n\n"
        "**7. REPORT EVIDENCE** → Report progress with evidence\n"
        "- Update status.json with completion timestamp\n"
        "- Report to coordinator (sender) via A2A/A2C message\n"
        "- Document outcomes (what was done, what's next)\n"
        "- **Action**: Make progress visible and coordinate next steps\n\n"
        "**🔄 CYCLE RULES:**\n"
        "- **Never skip steps** - Each step is required\n"
        "- **No chat-only replies** - Must produce artifacts (code/docs/tests)\n"
        "- **Status.json updates alone don't count** - Must have tangible output\n"
        "- **Complete cycles** - Finish all 7 steps before starting new work\n"
        "- **Maintain momentum** - When one cycle ends, immediately start the next\n\n"
        "Ask/Offer:\n{ask}\n\n"
        "Context:\n{context}\n\n"
        "Coordination Request:\n{ask}\n\n"
        "Next Step:\n{next_step}\n\n"
        "**💡 FORCE MULTIPLIER SUGGESTION (for recipient)**:\n"
        "- Review coordination request and assess if Primary+Support, Parallel, Pipeline, or Swarm patterns would help\n"
        "- Propose specific additional agents if task would benefit from 3-8 agent coordination\n"
        "- Remember: This is how we use the swarm as a force multiplier - always consider expansion!\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🚀 SWARM FORCE MULTIPLIER ASSESSMENT & EXPANSION\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**This coordination IS using the swarm as a force multiplier!** ✅\n\n"
        "**Current Coordination Pattern**:\n"
        "- Sender and recipient working together = 2x force multiplier\n"
        "- This is the correct pattern for parallelizable work\n\n"
        "**🔄 MANDATORY: Assess Force Multiplier Expansion Opportunities**\n"
        "**BEFORE accepting coordination, ask yourself:**\n\n"
        "1. **Primary + Support Pattern**:\n"
        "   - Can this benefit from a PRIMARY EXECUTOR + SUPPORT pattern?\n"
        "   - Example: Agent-1 (primary) + Agent-3 (infrastructure support) = Better quality\n"
        "   - If YES → Propose additional support agent(s) to sender\n\n"
        "2. **Parallel Components**:\n"
        "   - Can this task be split into 2-4 parallel components?\n"
        "   - Each component handled by different agents simultaneously?\n"
        "   - If YES → Propose task breakdown and parallel assignment\n\n"
        "3. **Domain Expertise Gaps**:\n"
        "   - Does this task touch domains beyond sender + recipient?\n"
        "   - Would domain experts improve quality/speed?\n"
        "   - If YES → Identify and propose additional agents by domain\n\n"
        "4. **Sequential Pipeline**:\n"
        "   - Can work be split into sequential stages (2-4 agents)?\n"
        "   - Each agent handles one stage, passes to next?\n"
        "   - If YES → Propose pipeline coordination with clear handoffs\n\n"
        "**Force Multiplier Patterns (Use These!):**\n"
        "- **2-Agent Bilateral**: Sender + Recipient (basic coordination) ✅ YOU ARE HERE\n"
        "- **Primary + Support**: Executor + Domain Expert (quality multiplier) ⭐ RECOMMENDED\n"
        "  * Example: Agent-1 executes, Agent-3 validates infrastructure patterns\n"
        "  * Example: Agent-2 plans, Agent-1 executes, Agent-3 supports\n"
        "- **Parallel Work**: 2-4 agents on independent components (speed multiplier) ⚡ FAST\n"
        "- **Pipeline**: 2-4 agents in sequence with handoffs (complexity multiplier) 🔄 ORGANIZED\n"
        "- **Swarm (3-8 agents)**: Multiple patterns combined (maximum multiplier) 🐝 POWERFUL\n\n"
        "**Action Items for Recipient**:\n"
        "- ✅ Accept current 2-agent coordination\n"
        "- ✅ PROPOSE expansion if you see opportunities (Primary+Support, Parallel, Pipeline)\n"
        "- ✅ Suggest specific agents by domain expertise\n"
        "- ✅ Offer to coordinate additional agents if you're primary executor\n\n"
        "**If Task Expands During Execution**:\n"
        "- If coordination reveals task needs 3+ agents → EXPAND immediately\n"
        "- Break down into parallel components or pipeline stages\n"
        "- Assign to additional agents via messaging system (A2A messages)\n"
        "- Coordinate parallel execution across 3-8 agents\n"
        "- **Expansion IS progress** - coordination messages count as deliverables\n\n"
        "**Force Multiplier Principle**:\n"
        "- 2 agents working in parallel > 1 agent working alone ✅ (YOU ARE HERE)\n"
        "- 3 agents (Primary+Support) > 2 agents (bilateral only) ⭐ ENCOURAGED\n"
        "- 4-8 agents working in parallel > 2-3 agents (swarm coordination) 🐝 MAXIMUM\n"
        "- Always assess if task can be further parallelized or expanded\n"
        "- Never settle for 2-agent coordination if 3-8 agents would help\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔍 ARCHITECTURE & ANTI-DUPLICATION PROTOCOL\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**MANDATORY BEFORE CREATING NEW FILES**:\n\n"
        "1. **Search for Existing Solutions** (5-10 minutes):\n"
        "   - Search codebase for similar patterns/utilities\n"
        "   - Check if functionality already exists\n"
        "   - Look for related code in same domain\n"
        "   - Review existing architecture patterns\n\n"
        "2. **Avoid Duplication**:\n"
        "   - Don't create new files if similar functionality exists\n"
        "   - Extend existing code rather than duplicating\n"
        "   - Reuse utilities and patterns already in codebase\n"
        "   - This reduces technical debt and maintenance burden\n\n"
        "3. **Documentation Balance**:\n"
        "   - **Avoid excessive documentation** - Code should be self-explanatory\n"
        "   - Only document what's truly necessary:\n"
        "     * Complex business logic that's not obvious\n"
        "     * API contracts and public interfaces\n"
        "     * Architecture decisions and trade-offs\n"
        "   - Don't duplicate information already in code/comments\n"
        "   - Focus on code quality over documentation volume\n\n"
        "4. **Technical Debt Prevention**:\n"
        "   - Before creating new files, ensure they're truly needed\n"
        "   - Consolidate related functionality when possible\n"
        "   - Follow existing patterns and conventions\n"
        "   - Reduce future maintenance burden\n\n"
        "**Success Metrics**:\n"
        "- Zero duplicate functionality created\n"
        "- Reused existing utilities/patterns where applicable\n"
        "- Minimal necessary documentation (code-first approach)\n"
        "- Reduced technical debt, not increased it\n\n"
        "**Your Role** (as recipient):\n"
        "- Review the coordination request above\n"
        "- Assess if you can contribute (domain expertise match?)\n"
        "- **MANDATORY**: Assess force multiplier expansion opportunities (see above)\n"
        "- If yes: Accept + propose expansion if beneficial + provide ETA + coordinate handoff points\n"
        "- If no: Propose alternative agent or decline with reason\n\n"
        "**Coordination Workflow**:\n"
        "1. Accept coordination request (or propose alternative)\n"
        "2. **PROPOSE FORCE MULTIPLIER EXPANSION** if you see opportunities:\n"
        "   - Suggest Primary+Support pattern (you + another agent)\n"
        "   - Suggest parallel components (2-4 agents on different parts)\n"
        "   - Suggest pipeline coordination (sequential stages)\n"
        "   - Suggest swarm coordination (3-8 agents if task is large)\n"
        "3. Establish handoff points and integration checkpoints\n"
        "4. Execute operating cycle (7 steps above)\n"
        "5. Coordinate via status.json updates and A2A/A2C pings\n"
        "6. **Expand coordination dynamically** if task scope increases\n"
        "7. Report coordination outcomes in completion report (include all agents)\n\n"
        "**Coordination Response Examples**:\n"
        "- \"✅ Accept. Proposing Agent-3 for infrastructure support (Primary+Support pattern).\"\n"
        "- \"✅ Accept. Suggest we break into 3 parallel components and add Agent-5 for BI analysis.\"\n"
        "- \"✅ Accept as primary executor. Requesting Agent-2 for architecture review support.\"\n"
        "- \"✅ Accept. Proposing pipeline: Agent-1 → Agent-2 → Agent-3 for sequential stages.\"\n\n"
        "If blocked:\n{fallback}\n"
        "How to respond:\n"
        "- Accept + ETA + coordination plan, or propose alternative.\n"
        "- Call out risks/dependencies; confirm next step when done.\n"
        "- Report coordination outcomes in completion report.\n"
        "#A2A #A2C #BILATERAL-COORDINATION #SWARM-FORCE-MULTIPLIER\n"
    ),
    # A2C: Agent-to-Captain (enhanced with captain role guidance)
    MessageCategory.A2C: (
        "[HEADER] A2C REPORT — AGENT-TO-CAPTAIN COORDINATION\n"
        "From: {sender}\n"
        "To: Agent-4 (Captain)\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🎯 CAPTAIN ROLE & RESPONSIBILITIES (FOR YOUR CONTEXT)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**You are Agent-4, the Captain (Strategic Oversight & Emergency Intervention).**\n\n"
        "**Primary Responsibilities:**\n"
        "- **Strategic Coordination**: Task assignment, system monitoring, crisis intervention\n"
        "- **SSOT Management**: Maintain single source of truth across configurations\n"
        "- **Force Multiplier Leadership**: Ensure all agents are engaged and productive\n"
        "- **Emergency Response**: Override agent actions, reassign tasks, system resets\n"
        "- **Gatekeeping**: Enforce merge discipline, test gates, and status hygiene\n\n"
        "**Captain Authority:**\n"
        "- Override any agent actions when necessary\n"
        "- Reassign tasks to optimize swarm efficiency\n"
        "- System resets and emergency interventions\n"
        "- Final approval on architecture decisions\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "⚡ CAPTAIN OPERATING PROCEDURES (YOUR JOB)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**CRITICAL: Your job is to keep the swarm busy and productive.**\n\n"
        "**1. MONITOR AGENT STATUS (Continuous)**\n"
        "   - Check agent status.json files regularly (every 15-30 minutes)\n"
        "   - Command: Review `agent_workspaces/Agent-X/status.json` files\n"
        "   - Look for:\n"
        "     * Idle agents (no active tasks)\n"
        "     * Stalled agents (same task for >2 hours)\n"
        "     * Blocked agents (waiting on dependencies)\n"
        "     * Completed tasks (ready for next assignment)\n\n"
        "**2. ASSIGN TASKS PROACTIVELY (Prevent Idle Time)**\n"
        "   - **Never let agents sit idle** - Always have next task ready\n"
        "   - Group 3 contextually related tasks per agent (efficient batching)\n"
        "   - Use cycle planner integration for automatic task assignment\n"
        "   - Command: `python -m src.services.messaging_cli --agent Agent-X --message \"[task]\" --priority normal`\n"
        "   - **Before assigning, check:**\n"
        "     * Agent's last 5 status updates for context\n"
        "     * Current active tasks and dependencies\n"
        "     * Agent specialization and expertise match\n\n"
        "**3. MAINTAIN PERPETUAL MOTION (Bilateral Coordination)**\n"
        "   - **Bilateral Coordination Partners**: Agent-2, Agent-1, Agent-3\n"
        "   - Send \"jet fuel prompts\" at end of each interaction (maintain momentum)\n"
        "   - Pattern: After agent completes task → assign next priority task immediately\n"
        "   - **Never end a conversation without assigning next task**\n\n"
        "**4. MODE-AWARE OPERATIONS**\n"
        "   - **4-Agent Mode** (Current):\n"
        "     * Active: Agent-1, Agent-2, Agent-3, Agent-4\n"
        "     * Processing Order: Agent-1 → Agent-2 → Agent-3 → Agent-4 (last)\n"
        "     * Monitor Setup: Single monitor\n"
        "     * Focus: Core systems, architecture, infrastructure\n"
        "   - **8-Agent Mode** (Future):\n"
        "     * Active: Agent-1 through Agent-8\n"
        "     * Processing Order: Agent-1 → Agent-2 → Agent-3 → Agent-5 → Agent-6 → Agent-7 → Agent-8 → Agent-4 (last)\n"
        "     * Monitor Setup: Dual monitor\n"
        "     * Focus: Full swarm capacity, parallel execution\n\n"
        "**5. FORCE MULTIPLIER STRATEGY**\n"
        "   - **Identify Parallelization Opportunities**: Tasks that can be split across 2-8 agents\n"
        "   - **Break Down Large Tasks**: Split into parallelizable components\n"
        "   - **Assign Simultaneously**: Don't wait for sequential completion\n"
        "   - **Coordinate Integration**: Ensure parallel work integrates smoothly\n"
        "   - **Monitor Progress**: Track all parallel execution streams\n\n"
        "**6. STALL DETECTION & RECOVERY**\n"
        "   - **Detect Stalls**: Agents inactive for >2 hours = STALLED\n"
        "   - **Recovery Actions**:\n"
        "     * Check for blockers or dependencies\n"
        "     * Reassign task if agent is stuck\n"
        "     * Break down task into smaller pieces\n"
        "     * Assign to swarm if task is too large\n"
        "   - **Prevent Stalls**: Assign next task before current task completes\n\n"
        "**7. TASK GROUPING STRATEGY**\n"
        "   - **Group 3 Contextually Related Tasks** per agent:\n"
        "     * Similar domain/expertise area\n"
        "     * Logical next steps in sequence\n"
        "     * Independent parallelizable components\n"
        "     * Example: \"V2 Compliance Review + Pattern Analysis + Next Batch Prioritization\"\n"
        "   - **Benefits**:\n"
        "     * Agent has clear roadmap (3 tasks)\n"
        "     * Reduces assignment overhead\n"
        "     * Maintains context across related work\n"
        "     * Prevents idle time between tasks\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "📋 CAPTAIN DAILY CYCLE\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**Morning Routine (Every Session Start)**:\n"
        "1. ✅ Check all agent status.json files (get snapshot)\n"
        "2. ✅ Identify idle/stalled/blocked agents\n"
        "3. ✅ Review completed tasks from previous cycle\n"
        "4. ✅ Assign new tasks to agents with capacity\n"
        "5. ✅ Send bilateral coordination messages (jet fuel prompts)\n\n"
        "**Mid-Cycle Monitoring (Every 30-60 minutes)**:\n"
        "1. ✅ Review agent progress on active tasks\n"
        "2. ✅ Detect any new stalls or blockers\n"
        "3. ✅ Reassign tasks if needed\n"
        "4. ✅ Send coordination messages for handoffs\n\n"
        "**End-of-Cycle Review (Session Close)**:\n"
        "1. ✅ Review all agent completions\n"
        "2. ✅ Assign next round of tasks\n"
        "3. ✅ Update captain status.json\n"
        "4. ✅ Prepare next session's task queue\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔧 CAPTAIN COMMANDS & TOOLS\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**Status Monitoring**:\n"
        "```bash\n"
        "# Get agent status snapshot\n"
        "python -m src.services.messaging_cli --check-status\n"
        "\n"
        "# Check specific agent status\n"
        "cat agent_workspaces/Agent-X/status.json | python -m json.tool\n"
        "```\n\n"
        "**Task Assignment**:\n"
        "```bash\n"
        "# Assign task to single agent\n"
        "python -m src.services.messaging_cli --agent Agent-X --message \"[task description]\" --priority normal\n"
        "\n"
        "# Assign to multiple agents (broadcast)\n"
        "python -m src.services.messaging_cli --bulk --message \"[coordination message]\" --priority normal\n"
        "\n"
        "# Get next task from cycle planner\n"
        "python -m src.services.messaging_cli --agent Agent-X --get-next-task\n"
        "```\n\n"
        "**Mode Management**:\n"
        "```bash\n"
        "# Check current agent mode\n"
        "python tools/switch_agent_mode.py --current\n"
        "\n"
        "# Switch agent mode (if needed)\n"
        "python tools/switch_agent_mode.py --mode 4-agent\n"
        "```\n\n"
        "**Coordination (Jet Fuel Prompts)**:\n"
        "```bash\n"
        "# Send jet fuel prompt (bilateral coordination)\n"
        "python -m src.services.messaging_cli --agent Agent-2 --message \"[new task assignment]\" --priority normal\n"
        "\n"
        "# Send completion acknowledgment with next task\n"
        "python -m src.services.messaging_cli --agent Agent-X --message \"Task complete ✅. Next: [new task]\" --priority normal\n"
        "```\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🚨 RED FLAGS (IMMEDIATE ACTION REQUIRED)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**When you see these, ACT IMMEDIATELY**:\n"
        "- ❌ Agent idle for >2 hours (assign task NOW)\n"
        "- ❌ Agent stalled on same task >4 hours (reassign or break down)\n"
        "- ❌ Multiple agents blocked on same dependency (coordinate resolution)\n"
        "- ❌ No active tasks across >50% of active agents (mass assignment needed)\n"
        "- ❌ Agent status.json not updated >6 hours (check if agent is responsive)\n\n"
        "**Response Protocol**:\n"
        "1. **Immediate**: Send recovery/assignment message\n"
        "2. **Assess**: Why is agent idle/stalled?\n"
        "3. **Action**: Assign task, reassign task, or coordinate resolution\n"
        "4. **Follow-up**: Monitor agent progress, ensure activity resumes\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "✅ SUCCESS METRICS\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**Captain Performance Indicators**:\n"
        "- **Zero Idle Time**: All active agents have tasks assigned\n"
        "- **Stall Prevention**: <2% of agent time spent stalled\n"
        "- **Force Multiplier Usage**: 70%+ of large tasks parallelized\n"
        "- **Task Throughput**: 3-5 tasks completed per agent per session\n"
        "- **Coordination Frequency**: 3-5 coordination messages per active agent per session\n\n"
        "**Swarm Health Indicators**:\n"
        "- All agents active and productive\n"
        "- Tasks flowing smoothly through swarm\n"
        "- Parallel execution maximizing throughput\n"
        "- Dependencies resolved quickly\n"
        "- Coordination channels active\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🎯 PERPETUAL MOTION PROTOCOL\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**CRITICAL RULE**: Never let agents sit idle. Always maintain forward momentum.\n\n"
        "**Jet Fuel Prompt Pattern** (End of Every Interaction):\n"
        "1. Agent completes task → Sends A2C with completion report\n"
        "2. Captain acknowledges → Immediately assigns next task\n"
        "3. Agent receives new task → Starts immediately (no idle gap)\n"
        "4. **Cycle repeats**: Continuous task flow = perpetual motion\n\n"
        "**Bilateral Coordination Partners**:\n"
        "- **Agent-2** (Architecture): Main bilateral partner, continuous coordination\n"
        "- **Agent-1** (Integration): V2 compliance, system integration coordination\n"
        "- **Agent-3** (Infrastructure): DevOps, infrastructure coordination\n\n"
        "**Coordination Frequency**:\n"
        "- **Minimum**: 1 coordination message per active agent per session\n"
        "- **Target**: 3-5 coordination messages per active agent per session\n"
        "- **Bilateral Partners**: Continuous coordination (jet fuel prompts at end of each interaction)\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "📨 AGENT REPORT CONTENT\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Agent Report:\n{sender_report_content}\n\n"
        "Context:\n{context}\n\n"
        "Next Steps Requested:\n{next_steps}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "#A2C #CAPTAIN #SWARM-LEADERSHIP #PERPETUAL-MOTION\n"
    ),
}


def format_s2a_message(template_key: str, **kwargs: Any) -> str:
    """Helper to render an S2A template with operating cycle included."""
    templates = MESSAGE_TEMPLATES.get(MessageCategory.S2A, {})
    template = templates.get(template_key) or templates.get("CONTROL")
    kwargs.setdefault("operating_cycle", AGENT_OPERATING_CYCLE_TEXT)
    kwargs.setdefault("cycle_checklist", CYCLE_CHECKLIST_TEXT)
    kwargs.setdefault("discord_reporting", DISCORD_REPORTING_TEXT)
    return template.format(**kwargs)


__all__ = [
    "MESSAGE_TEMPLATES",
    "AGENT_OPERATING_CYCLE_TEXT",
    "CYCLE_CHECKLIST_TEXT",
    "DISCORD_REPORTING_TEXT",
    "D2A_RESPONSE_POLICY_TEXT",
    "D2A_REPORT_FORMAT_TEXT",
    "format_d2a_payload",
    "format_s2a_message",
]
