#!/usr/bin/env python3
"""
Messaging Templates & Text - V2 Compliance Module
=================================================

<!-- SSOT Domain: integration -->

Canonical policy text, template strings, and formatting helpers.

Author: Agent-1 (Integration & Core Systems Specialist)
Created: 2025-10-11
License: MIT
"""

from __future__ import annotations

from typing import Any

from .messaging_models import MessageCategory


# Canonical operating cycle text for S2A messages.
AGENT_OPERATING_CYCLE_TEXT = (
    "Agent Operating Cycle (canonical):\n"
    "1) Claim\n"
    "2) Sync SSOT/context\n"
    "3) Slice\n"
    "4) Execute\n"
    "5) Validate\n"
    "6) Commit\n"
    "7) Report evidence\n"
)

# Cycle checklist to keep start/during/end behavior explicit
# Reference: docs/AGENT_OPERATING_CYCLE_WORKFLOW.md
CYCLE_CHECKLIST_TEXT = (
    "Cycle Checklist:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "CYCLE START:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Check inbox (priority: D2A → C2A → A2A)\n"
    "- Check Contract System (--get-next-task)\n"
    "- Check Swarm Brain (use MCP: search_swarm_knowledge) for relevant patterns/solutions (advisory only - see docs/governance/SWARM_BRAIN_POLICY.md)\n"
    "- Check MASTER_TASK_LOG.md (use MCP: get_tasks) for assigned tasks\n"
    "- 🔍 **FORCE MULTIPLIER ASSESSMENT (MANDATORY FIRST STEP)**:\n"
    "  - Will this task take >1 cycle? → STOP, delegate parts to swarm\n"
    "  - Does this touch 2+ domains? → STOP, coordinate with domain experts\n"
    "  - Is another agent better suited? → STOP, message them to take over\n"
    "  - Can this be parallelized? → STOP, break down and assign to 2-4 agents\n"
    "  - ONLY if all answers are NO → proceed solo\n"
    "- Update status.json (status=ACTIVE, increment cycle_count)\n"
    "- Update FSM State\n"
    "- Review current mission\n"
    "\n"
    "❌ DO NOT: Add tasks to cycle planner here (unless urgent)\n"
    "❌ DO NOT: Message other agents here (unless urgent coordination needed)\n"
    "\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "DURING CYCLE:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "📋 PHASE 3: SLICE (Technical Implementation Planning):\n"
    "1. Start with explicit technical instructions (not general \"build this\")\n"
    "2. Request full technical implementation plan from AI first\n"
    "3. Vet the plan before execution\n"
    "4. Convert validated plan into detailed prompt for model\n"
    "5. Code review: Confirm implementation won't be spaghetti\n"
    "6. Ensure clean architecture patterns, not spaghetti code\n"
    "\n"
    "- Update status when phase changes\n"
    "- Update when tasks complete\n"
    "- Update if blocked\n"
    "- If new task identified → Use MCP: add_task_to_inbox(task, agent_id)\n"
    "- If task blocked → Use MCP: move_task_to_waiting(task_description, reason, agent_id)\n"
    "\n"
    "✅ MESSAGE OTHER AGENTS WHEN:\n"
    "- Task expands → Break down and coordinate (use A2A messaging)\n"
    "- Need domain expertise → Message domain specialist agent\n"
    "- Cross-domain work → Message relevant agents for coordination\n"
    "- 75-80% complete → Send \"gas\" to next agent in sequence (pipeline continuity)\n"
    "- Blocked → Message for help or escalate to Captain\n"
    "- Force multiplier opportunity → Break down and assign to swarm\n"
    "\n"
    "❌ DO NOT: Add tasks to cycle planner here (unless new work identified)\n"
    "\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "CYCLE END:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Update completed_tasks\n"
    "- Update next_actions\n"
    "\n"
    "✅ UPDATE MASTER_TASK_LOG (MANDATORY):\n"
    "- Use MCP tool: task_manager_server (add_task_to_inbox, mark_task_complete, move_task_to_waiting)\n"
    "- If task completed → mark_task_complete(task_description, section=\"THIS WEEK\")\n"
    "- If task blocked → move_task_to_waiting(task_description, reason=\"blocked on X\", agent_id=\"{agent_id}\")\n"
    "- If new task identified → add_task_to_inbox(task=\"description\", agent_id=\"{agent_id}\")\n"
    "- Location: MASTER_TASK_LOG.md (repository root)\n"
    "- When: After completing work, before session transition\n"
    "- Why: Central task tracking, enables delegation, prevents task loss\n"
    "- Reference: QUICK_START_GUIDE.md, DELEGATION_BOARD.md\n"
    "\n"
    "✅ VERIFY WORK (BEFORE COMMITTING):\n"
    "- Use MCP: verify_git_work(agent_id, file_path, claimed_changes)\n"
    "- Use MCP: verify_work_exists(file_patterns, agent_name)\n"
    "- Ensure work is actually committed before claiming\n"
    "\n"
    "✅ CHECK V2 COMPLIANCE (BEFORE COMMITTING):\n"
    "- Use MCP: check_v2_compliance(file_path)\n"
    "- Use MCP: validate_file_size(file_path)\n"
    "- Use MCP: get_v2_exceptions() if file exceeds limits\n"
    "- Prevent V2 violations before committing\n"
    "\n"
    "✅ ADD TASKS TO CYCLE PLANNER HERE:\n"
    "- Location: agent_workspaces/{agent_id}/cycle_planner_tasks_YYYY-MM-DD.json\n"
    "- When: After completing current work, before session transition\n"
    "- What: Unfinished work, blockers, next session priorities\n"
    "- Reference: Session Cleanup Template Step 9\n"
    "\n"
    "✅ MESSAGE OTHER AGENTS HERE:\n"
    "- Coordination outcomes → If swarm was engaged, report results\n"
    "- Handoff → If work continues with another agent\n"
    "- Completion → Notify relevant agents of completed work\n"
    "\n"
    "- Commit status.json to git\n"
    "- Create & post devlog automatically\n"
    "- Share learnings to Swarm Brain (use MCP: share_learning)\n"
    "- Record decisions if made (use MCP: record_decision)\n"
    "- Report coordination outcomes if swarm was engaged\n"
    "\n"
    "✅ VERIFY WORK (BEFORE COMMITTING):\n"
    "- Use MCP: verify_git_work(agent_id, file_path, claimed_changes)\n"
    "- Use MCP: verify_work_exists(file_patterns, agent_name)\n"
    "- Ensure work is actually committed before claiming\n"
    "\n"
    "✅ CHECK V2 COMPLIANCE (BEFORE COMMITTING):\n"
    "- Use MCP: check_v2_compliance(file_path)\n"
    "- Use MCP: validate_file_size(file_path)\n"
    "- Use MCP: get_v2_exceptions() if file exceeds limits\n"
    "- Prevent V2 violations before committing\n"
    "\n"
    "📖 Full workflow guide: docs/AGENT_OPERATING_CYCLE_WORKFLOW.md\n"
)

# Swarm Force Multiplier Coordination Protocol
SWARM_COORDINATION_TEXT = (
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "🐝 SWARM FORCE MULTIPLIER — USE THE SWARM\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "**CORE PRINCIPLE**: 8 agents working in parallel > 1 agent working alone.\n"
    "Never struggle alone on tasks that can be parallelized.\n\n"
    "**WHEN TO USE SWARM COORDINATION**:\n"
    "✅ Task is too large for one agent (3+ cycles estimated)\n"
    "✅ Task has multiple independent components\n"
    "✅ Task spans multiple domains/expertise areas\n"
    "✅ Multiple agents have relevant expertise\n"
    "✅ Parallelization will speed up completion (4-8x faster)\n\n"
    "**FORCE MULTIPLIER WORKFLOW**:\n"
    "1. **Task Analysis** (FIRST - before starting work):\n"
    "   - Break task into parallelizable components\n"
    "   - Map components to agent expertise domains\n"
    "   - Identify dependencies and sequencing needs\n"
    "   - Estimate time/complexity per component\n"
    "   - **If task > 1 cycle OR multi-domain → STOP and delegate**\n\n"
    "2. **Immediate Delegation** (if task qualifies):\n"
    "   - **DO THIS FIRST** - Don't start working alone\n"
    "   - Identify target agents by domain expertise:\n"
    "     • Agent-1: Integration & Core Systems\n"
    "     • Agent-2: Architecture & Design\n"
    "     • Agent-3: Infrastructure & DevOps\n"
    "     • Agent-5: Business Intelligence\n"
    "     • Agent-6: Coordination & Communication\n"
    "     • Agent-7: Web Development\n"
    "     • Agent-8: SSOT & System Integration\n"
    "   - Send assignment messages NOW (see commands below)\n"
    "   - **Delegation counts as progress** - commit the assignment messages\n\n"
    "3. **Bilateral Coordination** (default for 2-agent tasks):\n"
    "   - Identify primary partner agent (domain expertise match)\n"
    "   - Send A2A coordination message with task breakdown\n"
    "   - Establish handoff points and integration checkpoints\n"
    "   - Coordinate via status.json updates and A2A pings\n\n"
    "4. **Swarm Assignment** (for 3+ agent tasks):\n"
    "   - Break down into 3-8 parallel sub-tasks\n"
    "   - Assign via messaging system (use --agent flag for each)\n"
    "   - Send all assignments simultaneously (parallel execution)\n"
    "   - Provide clear context, deadlines, and priorities\n"
    "   - Monitor via status.json and coordination messages\n\n"
    "5. **Coordination Commands** (USE THESE):\n"
    "   ```bash\n"
    "   # Assign task to specific agent (DO THIS)\n"
    "   python -m src.services.messaging_cli --agent Agent-X --message \"[Task description with context]\" --priority normal\n"
    "   \n"
    "   # Example: Assign pytest debugging to Agent-7\n"
    "   python -m src.services.messaging_cli --agent Agent-7 --message \"Debug pytest failures in web/ directory\" --priority normal\n"
    "   \n"
    "   # Broadcast coordination message to all agents\n"
    "   python -m src.services.messaging_cli --bulk --message \"Coordination: [context]\" --priority normal\n"
    "   \n"
    "   # Check agent status for coordination\n"
    "   python -m src.services.messaging_cli --check-status\n"
    "   ```\n"
    "   **Remember**: Sending assignment messages IS progress. Commit them.\n\n"
    "5. **Integration & Validation**:\n"
    "   - Collect results from all assigned agents\n"
    "   - Integrate outputs and validate completeness\n"
    "   - Report final status with evidence\n"
    "   - Document successful patterns in Swarm Brain\n\n"
    "**BILATERAL COORDINATION PROTOCOL** (2-agent tasks):\n"
    "- Pair with domain expert agent (check agent specializations)\n"
    "  - Agent-1: Integration & Core Systems\n"
    "  - Agent-2: Architecture & Design\n"
    "  - Agent-3: Infrastructure & DevOps\n"
    "  - Agent-5: Business Intelligence\n"
    "  - Agent-6: Coordination & Communication\n"
    "  - Agent-7: Web Development\n"
    "  - Agent-8: SSOT & System Integration\n"
    "- Send A2A message with:\n"
    "  • Task breakdown and ownership\n"
    "  • Handoff points and dependencies\n"
    "  • Integration checkpoints\n"
    "  • Expected deliverables from each agent\n"
    "- Coordinate via status.json updates and A2A pings\n"
    "- Report coordination outcomes in completion report\n\n"
    "**ANTI-PATTERNS TO AVOID**:\n"
    "❌ Working alone on large tasks (waste of swarm capacity)\n"
    "❌ Sequential assignment (assign task 1, wait, assign task 2...)\n"
    "❌ Over-coordination (too many messages, agents waiting for approval)\n"
    "❌ Ignoring available expertise (not leveraging domain specialists)\n"
    "❌ Starting work before checking if task should be delegated\n"
    "❌ Thinking \"I'll do it myself\" when task spans multiple domains\n\n"
    "**DELEGATION EXAMPLES** (Use these patterns):\n\n"
    "Example 1: Large Refactor\n"
    "  - Task: Refactor 10 files across frontend/backend\n"
    "  - Action: Break into \"frontend refactor\" → Agent-7, \"backend refactor\" → Agent-1\n"
    "  - Message: \"Coordination: Frontend refactor task. You handle web/, I'll handle services/\"\n\n"
    "Example 2: Multi-Domain Feature\n"
    "  - Task: Add feature requiring database + API + frontend\n"
    "  - Action: Agent-1 (API) + Agent-7 (frontend) + Agent-8 (database schema)\n"
    "  - Message: \"Feature coordination: API endpoint assigned to Agent-1, frontend to Agent-7\"\n\n"
    "Example 3: Testing Across Domains\n"
    "  - Task: Add tests for integration spanning 3 modules\n"
    "  - Action: Each module's specialist adds their tests\n"
    "  - Message: \"Test coordination: Each agent adds tests for their domain modules\"\n\n"
    "Example 4: Documentation Update\n"
    "  - Task: Update docs across 5 subsystems\n"
    "  - Action: Each subsystem owner updates their docs\n"
    "  - Message: \"Doc update: Agent-2 (architecture), Agent-3 (infra), Agent-7 (web) - parallel docs\"\n\n"
    "**Remember**: Sending coordination messages IS progress. Commit them!\n\n"
    "**SUCCESS METRICS**:\n"
    "• Time Reduction: 4-8x faster than sequential execution\n"
    "• Coverage: More comprehensive (multiple perspectives)\n"
    "• Quality: Better results (domain expertise applied)\n"
    "• Swarm Utilization: All agents engaged when needed\n\n"
    "**Remember**: If a task is too big for you, don't struggle alone.\n"
    "Break it down, assign via messaging system, coordinate the swarm.\n"
    "🐝 WE. ARE. SWARM. ⚡🔥\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
)

# Discord reporting policy to enforce completion visibility (for S2A/C2A)
DISCORD_REPORTING_TEXT = (
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "DISCORD REPORTING POLICY — CRITICAL VISIBILITY\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "I may not be at the computer. Discord is the primary visibility channel.\n\n"
    "Your completion report MUST be posted to Discord when a task slice finishes.\n\n"
    "When to post:\n"
    "[ ] After completing a slice with a real artifact\n"
    "[ ] After a meaningful commit\n"
    "[ ] After validation/test results\n"
    "[ ] When blocked (post blocker + next step)\n\n"
    "What to include:\n"
    "- Task\n"
    "- Actions Taken\n"
    "- Commit Message (if code touched)\n"
    "- Status (✅ done or 🟡 blocked + next step)\n"
    "- Artifact path(s) if relevant\n\n"
    "Do not send acknowledgment-only messages.\n"
    "The Discord post is the completion handshake.\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "HOW TO POST TO DISCORD (EXACT COMMAND)\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "**Command:**\n"
    "```bash\n"
    "python tools/devlog_manager.py post --agent {recipient} --file <devlog_file.md>\n"
    "```\n\n"
    "**Steps:**\n"
    "1. Create a markdown file: `devlogs/YYYY-MM-DD_agent-X_topic.md`\n"
    "2. Write your completion report in the file\n"
    "3. Run the command above, replacing:\n"
    "   - `{recipient}` with your agent ID (e.g., Agent-1)\n"
    "   - `<devlog_file.md>` with your file path\n\n"
    "**Example:**\n"
    "```bash\n"
    "# Create devlog file\n"
    "echo '# Task Complete\\n\\nActions: ...' > devlogs/2025-12-08_agent-1_task_complete.md\n"
    "# Post to Discord\n"
    "python tools/devlog_manager.py post --agent Agent-1 --file devlogs/2025-12-08_agent-1_task_complete.md\n"
    "```\n\n"
    "**This may be the ONLY way users see your messages!**\n"
)

# D2A (Discord → Agent) response policy - lightweight and human-first
D2A_RESPONSE_POLICY_TEXT = (
    "Discord Response Policy:\n"
    "- This message originated from Discord.\n"
    "- Reply in Discord with your status/answer when you act on this.\n"
    "- Discord is the visibility channel; status-only or chat-only replies do NOT count.\n"
    "- Include evidence: artifact/validation/delegation. Keep replies short and high-signal.\n"
)

# D2A preferred reply format - compact reminder
D2A_REPORT_FORMAT_TEXT = (
    "Preferred Reply Format (short):\n"
    "- Task\n"
    "- Actions Taken\n"
    "- Commit Message (if code touched)\n"
    "- Status (✅ done or 🟡 blocked + next step)\n"
)


def format_d2a_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Format D2A payload with default values."""
    payload.setdefault("interpretation", "Pending agent interpretation.")
    payload.setdefault(
        "actions", "Evaluate request and execute if safe/within scope.")
    payload.setdefault(
        "fallback",
        "Ask for clarification in Discord with one focused question.",
    )
    payload.setdefault("discord_response_policy", D2A_RESPONSE_POLICY_TEXT)
    payload.setdefault("d2a_report_format", D2A_REPORT_FORMAT_TEXT)
    return payload


# Template strings for standard headers. Payloads should be formatted by the caller.
MESSAGE_TEMPLATES: dict[MessageCategory, Any] = {
    # S2A: System-to-Agent (control/ops/cycles)
    MessageCategory.S2A: {
        "CONTROL": (
            "[HEADER] S2A CONTROL\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Context:\n{context}\n\n"
            "Architecture & Swarm Brain Check (BEFORE DOING ANYTHING):\n"
            "- Search existing architecture / SSOT docs for this domain (designs, patterns, contracts).\n"
            "- Search Swarm Brain for prior decisions and protocols (advisory only - see docs/governance/SWARM_BRAIN_POLICY.md).\n"
            "- Prefer reusing/extending existing artifacts over creating new ones; only create new files or flows when no suitable pattern exists.\n\n"
            "Action Required:\n"
            "Produce ONE artifact before next cycle:\n"
            "- Run validator and report results, OR\n"
            "- Commit a small fix with tests passing, OR\n"
            "- Write a 5-bullet technical report.\n\n"
            "No-Reply Policy:\n"
            "- This is a control message. Do not respond unless blocked.\n"
            "- Do not update status.json solely to acknowledge.\n"
            "- Progress resets only on artifacts: commit | test pass | real doc/code delta.\n\n"
            "Priority Behavior:\n"
            "- regular = next cycle; urgent = interrupt current slice.\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{swarm_coordination}\n"
            "{discord_reporting}\n"
            "Evidence format:\n"
            "- Command(s) run + outcome OR\n"
            "- Commit hash + tests status OR\n"
            "- Doc name + 3 key findings\n\n"
            "If blocked:\n"
            "- Assess if task needs swarm coordination (too large? multiple domains?)\n"
            "- If yes: Break down task, assign via messaging system, coordinate swarm\n"
            "- If no: Send 1 message with: blocker + proposed fix + what you need from Captain\n"
        ),
        "SWARM_PULSE": (
            "🚨 URGENT MESSAGE 🚨\n\n"
            "[S2A] {recipient}\n\n"
            "💓💓 SWARM PULSE - {recipient}\n\n"
            "The swarm hasn't heard from {recipient} in 10+ minutes. We don't know what you're doing - this is a good time to sync up!\n\n"
            "**🐝 SWARM SYNC OPPORTUNITY:**\n"
            "This is a good time to sync with the swarm and review project state. The swarm doesn't know what you're working on - help us stay coordinated!\n\n"
            "**YOUR CURRENT STATE:**\n"
            "- **FSM State**: {fsm_state}\n"
            "- **Last Mission**: {current_mission}\n"
            "- **Time Since Last Update**: {time_since_update}\n\n"
            "**📋 NEXT TASK FROM CYCLE PLANNER:**\n"
            "- **Task**: {next_task}\n"
            "- **Priority**: {task_priority}\n"
            "- **Points**: {task_points}\n"
            "- **Status**: {task_status}\n"
            "- **Action**: Claim and execute this task immediately\n\n"
            "**SWARM SYNC CHECKLIST (DO THESE NOW):**\n"
            "1. **Update/Review Project State**\n"
            "   - Check latest project analysis, V2 compliance status, technical debt markers\n"
            "   - Review `MASTER_TASK_LOG.md` for swarm-wide priorities\n"
            "   - Identify high-value opportunities or blockers affecting the swarm\n\n"
            "2. **Update/Review Swarm Brain**\n"
            "   - Search swarm knowledge for patterns related to your current work\n"
            "   - Share any learnings or decisions you've made\n"
            "   - Check for relevant protocols or patterns from other agents\n\n"
            "3. **Read Other Agent Statuses**\n"
            "   - Review `agent_workspaces/*/status.json` files to see what the swarm is working on\n"
            "   - Identify coordination opportunities or dependencies\n"
            "   - Check for blockers you might be able to help with\n\n"
            "4. **Update/Review Your Own Workspace**\n"
            "   - Update `agent_workspaces/{recipient}/status.json` with current progress\n"
            "   - Review your devlogs to track your work trajectory\n"
            "   - Clean up any stale state or temporary files\n\n"
            "5. **Get Back to Work**\n"
            "   - Pick one concrete task from planner/log (see NEXT TASK above)\n"
            "   - Execute one measurable action (real command, file update, or coordination message)\n"
            "   - Append a short devlog entry documenting what you did\n\n"
            "**CAPTAIN DIRECTIVE (AFTER SYNC):**\n"
            "1. **Pick one concrete task from the planner/log**\n"
            "   - Read `MASTER_TASK_LOG.md` (THIS WEEK / INBOX sections)\n"
            "   - Cross-check with Cycle Planner \"NEXT TASK\" above\n"
            "   - Choose **one** task that {recipient} can move forward\n\n"
            "2. **Execute one measurable action on that task**\n"
            "   - Run a real command, update a real file, or send a real coordination message\n"
            "   - Avoid meta-work (no planning-only, no status-only)\n\n"
            "3. **Update `status.json` with progress**\n"
            "   - Record: claimed task, key action taken, next action\n"
            "   - Keep `fsm_state` = ACTIVE while you are executing\n\n"
            "4. **Commit your work to git**\n"
            "   - If you made code changes, commit them with a clear message\n"
            "   - Include `status.json` updates in your commit\n"
            "   - Use format: `git commit -m \"Task: [brief description] - [what you did]\"`\n"
            "   - Example: `git commit -m \"Test Coverage: Added test_merge_conflict_resolver.py - 14 tests for merge conflict resolution\"`\n\n"
            "5. **Append a short devlog entry**\n"
            "   - File: `agent_workspaces/{recipient}/devlogs/` (latest or new file)\n"
            "   - Add 3–5 lines:\n"
            "     - Swarm pulse time + duration since last update\n"
            "     - Task you claimed\n"
            "     - Actions executed (including commit hash if applicable)\n"
            "     - Next actions\n\n"
            "**🔧 MANDATORY SYSTEM UTILIZATION (DO FIRST):**\n"
            "1. **Check Contract System** (MANDATORY):\n"
            "   ```bash\n"
            "   python -m src.services.messaging_cli --get-next-task --agent {recipient}\n"
            "   ```\n"
            "   - Claim assigned work FIRST before seeking new opportunities\n"
            "   - If no contract, proceed to Project Scanner\n\n"
            "2. **Check Swarm Brain** (Advisory - Optional Reference):\n"
            "   ```python\n"
            "   from src.swarm_brain.swarm_memory import SwarmMemory\n"
            "   memory = SwarmMemory(agent_id='{recipient}')\n"
            "   results = memory.search_swarm_knowledge(\"your task topic\")\n"
            "   ```\n"
            "   - May reference for similar work/patterns (non-canonical)\n"
            "   - Advisory guidance only - see docs/governance/SWARM_BRAIN_POLICY.md\n"
            "   - For enforceable requirements, see docs/governance/GOVERNANCE_MAP.md\n\n"
            "3. **Update FSM State** (MANDATORY):\n"
            "   - Update fsm_state in status.json to reflect current state\n"
            "   - Use AgentLifecycle for automatic updates\n"
            "   - Current: {fsm_state} → Target: ACTIVE\n\n"
            "4. **Check Project State** (if starting new work):\n"
            "   ```bash\n"
            "   # Review latest project analysis\n"
            "   cat project_analysis.json | python -m json.tool | grep -A 5 \"violations\"\n"
            "   ```\n"
            "   - Find high-value opportunities\n"
            "   - Check V2 compliance issues\n"
            "   - Identify consolidation targets\n\n"
            "**IMMEDIATE ACTIONS (WHILE EXECUTING):**\n"
            "1. Check inbox FIRST for new messages (message-driven workflow)\n"
            "2. Continue current task execution\n"
            "3. If task is too large, use Force Multiplier Pattern (break down, assign to swarm)\n"
            "4. For cross-domain boundaries, use Agent Pairing Pattern (pair with domain expert)\n"
            "5. Check for blockers and resolve\n"
            "6. Update status.json with progress\n"
            "7. Move to next action in queue\n\n"
            "**🔍 STALL ANALYSIS (DO WHILE WORKING):**\n"
            "- Check Swarm Brain for patterns (advisory only - see docs/governance/SWARM_BRAIN_POLICY.md)\n"
            "- For enforceable messaging requirements, see .cursor/rules/messaging-contracts.mdc\n"
            "- If stall reason not addressed, create pattern AFTER completing current task\n"
            "- Review project state as you work, not as separate step\n\n"
            "**🚀 FORCE MULTIPLIER MODE - EXECUTE NOW:**\n"
            "- **If task is too large**: Break it down RIGHT NOW and assign to swarm via messaging system\n"
            "- **If task touches many files**: Split into chunks NOW and assign to multiple agents\n"
            "- **If task requires multiple domains**: Use Agent Pairing or Telephone Game patterns\n"
            "- **NEVER work alone on tasks that can be parallelized** - 8 agents > 1 agent working alone\n"
            "- **EXECUTE**: Identify your largest/blocking task and break it down FOR SWARM ASSIGNMENT NOW\n\n"
            "**AUTONOMOUS OPERATION PRINCIPLES:**\n"
            "- You are AUTONOMOUS - no approval needed\n"
            "- System messages are NOT stop signals\n"
            "- Command failures are NOT blockers\n"
            "- ALWAYS have next actions ready\n\n"
            "**FSM STATE TRANSITION:**\n"
            "- Current: {fsm_state}\n"
            "- Target: ACTIVE (if not already)\n"
            "- Action: Sync with swarm, review state, then execute work and update status.json + devlog\n\n"
            "**REMEMBER:**\n"
            "- This is a **swarm pulse**, not an accusation - we just want to know what you're doing\n"
            "- Use this as an opportunity to **sync up** with the swarm and **review project state**\n"
            "- After syncing, **get back to work** on concrete tasks\n"
            "- The swarm works better when we all know what each other is doing\n\n"
            "**STOP READING. START EXECUTING. DO NOT ACKNOWLEDGE. DO NOT REPORT. JUST WORK.**\n\n"
            "**📚 SYSTEM UTILIZATION PROTOCOL:**\n"
            "- Full protocol: `swarm_brain/protocols/SYSTEM_UTILIZATION_PROTOCOL.md`\n"
            "- These systems are MANDATORY - use them every cycle\n"
            "- Captain monitors system utilization\n\n"
            "#SWARM-PULSE #SWARM-HEARTBEAT #FSM-{fsm_state} #SWARM-SYNC #STATUS-AND-DEVLOG #SYSTEM-UTILIZATION\n"
        ),
        "ONBOARDING": (
            "[HEADER] S2A ONBOARDING ({mode})\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Identity:\n"
            "You are {recipient}. Act as this agent for this message.\n"
            "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
            "No-Ack Policy:\n"
            "- Do not send empty acknowledgments.\n"
            "- Respond ONLY with the Output Contract.\n\n"
            "Context:\n{context}\n\n"
            "Actions (execute; do not narrate):\n{actions}\n\n"
            "OUTPUT CONTRACT (STRICT):\n"
            "- Task: <name>\n"
            "- Actions Taken: bullet list\n"
            "- Artifacts: exact paths\n"
            "- Commit: hash + tests status OR 'No code changes'\n"
            "- Verification: bullets proving checks ran\n"
            "- Public Build Signal: one line describing what changed\n"
            "- Status: ✅ Ready | 🟡 Blocked (reason)\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{discord_reporting}\n"
            "If blocked:\n{fallback}\n"
            "{footer}"
        ),
        # DEPRECATED: Use ONBOARDING template with mode="HARD" instead
        "HARD_ONBOARDING": (
            "[HEADER] S2A HARD ONBOARDING\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Identity:\n"
            "You are {recipient}. Act as this agent for this message.\n"
            "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
            "No-Ack Policy:\n"
            "- Do not send empty acknowledgments.\n"
            "- Respond with artifact/result or 1 blocker (blocker + proposed fix + owner).\n\n"
            "Context:\n{context}\n\n"
            "First Actions:\n{actions}\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{discord_reporting}\n"
            "If blocked:\n{fallback}\n"
        ),
        # DEPRECATED: Use ONBOARDING template with mode="SOFT" instead
        "SOFT_ONBOARDING": (
            "[HEADER] S2A SOFT ONBOARDING\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Identity:\n"
            "You are {recipient}. Act as this agent for this message.\n"
            "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
            "No-Ack Policy:\n"
            "- Do not send empty acknowledgments.\n"
            "- Respond ONLY with the Output Contract.\n\n"
            "Context:\n{context}\n\n"
            "Actions (execute; do not narrate):\n{actions}\n\n"
            "OUTPUT CONTRACT (STRICT):\n"
            "- Task: <name>\n"
            "- Actions Taken: bullet list\n"
            "- Artifacts: exact paths\n"
            "- Commit: hash + tests status OR 'No code changes'\n"
            "- Verification: bullets proving checks ran\n"
            "- Public Build Signal: one line describing what changed\n"
            "- Status: ✅ Ready | 🟡 Blocked (reason)\n\n"
            "{operating_cycle}\n"
            "{cycle_checklist}\n"
            "{discord_reporting}\n"
            "If blocked:\n{fallback}\n"
        ),
        "PASSDOWN": (
            "[HEADER] S2A PASSDOWN\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "What changed:\n{context}\n\n"
            "Your next slice:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "TELEPHONE_STATUS_GAME": (
            "[HEADER] S2A TELEPHONE STATUS GAME\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Chain Context:\n{context}\n\n"
            "Your move:\n{actions}\n\n"
            "Rules:\n"
            "- Pass actionable state + next slice.\n"
            "- No acknowledgement-only responses.\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "TASK_CYCLE": (
            "[HEADER] S2A TASK CYCLE\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Cycle Objective:\n{context}\n\n"
            "Assigned Slice:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "FSM_UPDATE": (
            "[HEADER] S2A FSM UPDATE\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "State Change:\n{context}\n\n"
            "Required Behavior:\n{actions}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
        ),
        "DEBATE_CYCLE": (
            "[HEADER] S2A DEBATE CYCLE\n"
            "From: {sender}\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "Debate Topic:\n{topic}\n\n"
            "Role/Position:\n{role}\n\n"
            "Context:\n{context}\n\n"
            "Rules:\n{rules}\n\n"
            "Deliverable:\n{deliverable}\n\n"
            "{operating_cycle}\n"
            "If blocked:\n{fallback}\n"
            "#DEBATE #S2A\n"
        ),
        "CYCLE_V2": (
            "[HEADER] C2A CYCLE V2 - MAX PRODUCTIVITY\n"
            "From: Captain Agent-4\n"
            "To: {recipient}\n"
            "Priority: {priority}\n"
            "Message ID: {message_id}\n"
            "Timestamp: {timestamp}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "MISSION\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{mission}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "DEFINITION OF DONE (DoD)\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{dod}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "CONSTRAINTS\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "SSOT: {ssot_constraint}\n"
            "V2: {v2_constraint}\n"
            "Touch Surface: {touch_surface}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "VALIDATION REQUIRED\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{validation_required}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "PRIORITY\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{priority_level}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "HANDOFF EXPECTATION\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "{handoff_expectation}\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "AGENT OPERATING CYCLE V2\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "A) Pre-Cycle Rules (Hard Guards):\n"
            "   • WIP = 1 (only one active objective per cycle)\n"
            "   • DoD required (if missing, write 3-line DoD)\n"
            "   • SSOT boundaries first (confirm where truth lives)\n"
            "   • V2 Compliance gate (split if file exceeds limits)\n\n"
            "B) Start of Cycle (Fast):\n"
            "   1. Inbox sweep (max 60 seconds)\n"
            "   2. Claim task: --get-next-task --agent {recipient}\n"
            "   3. Pull last 1 relevant pattern from Swarm Brain\n"
            "   4. Write Micro-Plan (3 bullets max):\n"
            "      - Change target\n"
            "      - Validation method\n"
            "      - Exit criteria\n"
            "   5. Update status.json with phase, mission, micro-plan, DoD\n\n"
            "C) Execution Burst (Timeboxed):\n"
            "   1. Implement smallest viable change toward DoD\n"
            "   2. If scope expands: split into subtask, notify Captain\n"
            "   3. Keep changes localized and typed\n"
            "   4. No refactors unless they reduce immediate risk\n\n"
            "D) Mid-Cycle Checkpoint (Anti-Drift):\n"
            "   After first meaningful change:\n"
            "   • Still aligned with DoD?\n"
            "   • Still within SSOT?\n"
            "   • Still within V2?\n"
            "   If no: adjust plan, report correction\n\n"
            "E) Validation First-Class (Shift Left):\n"
            "   1. Run tests/lint/verification for touched surface\n"
            "   2. If tests missing: add minimal tests\n"
            "   3. Log evidence (command/output summary)\n\n"
            "F) Reporting Contract (No Empty Replies):\n"
            "   Must include:\n"
            "   • What changed (artifact-level)\n"
            "   • Validation evidence\n"
            "   • Measurable result\n"
            "   • Next recommended action\n\n"
            "G) Documentation:\n"
            "   • status.json updated (COMPLETE/BLOCKED/HANDOFF_READY)\n"
            "   • Discord devlog posted for completed actions\n\n"
            "H) Escalation Thresholds:\n"
            "   Escalate when:\n"
            "   • DoD unclear beyond 2 reasonable assumptions\n"
            "   • SSOT conflict detected\n"
            "   • Cross-agent dependency required\n"
            "   • Change affects >2 modules/domains\n\n"
            "I) Swarm Force Multiplier (CRITICAL):\n"
            "   Before starting execution:\n"
            "   • Assess task size: Is this a force multiplier opportunity?\n"
            "   • If task is large (3+ cycles) or spans multiple domains:\n"
            "     → Break down into parallelizable components\n"
            "     → Assign to 2-8 agents via messaging system\n"
            "     → Coordinate parallel execution\n"
            "     → Integrate results\n"
            "   • Remember: 8 agents working in parallel > 1 agent working alone\n"
            "   • See Swarm Coordination Protocol below for details\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "SUCCESS METRICS PER CYCLE\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "• Output: ≥1 merged-ready artifact OR ≥1 validated decision\n"
            "• Validation: evidence included every time\n"
            "• Drift: zero off-mission edits\n"
            "• WIP: never >1\n"
            "• Swarm Utilization: Agents engaged when task requires coordination\n\n"
            "{swarm_coordination}\n"
            "If blocked:\n{fallback}\n"
            "#CYCLE_V2 #C2A #SWARM-COORDINATION\n"
        ),
    },
    # D2A: Discord-to-Agent (lightweight, human-first)
    MessageCategory.D2A: (
        "[HEADER] D2A DISCORD INTAKE\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Origin:\n"
        "- Discord → Agent intake\n\n"
        "User Message:\n"
        "{content}\n\n"
        "Interpretation (agent):\n"
        "{interpretation}\n\n"
        "Proposed Action:\n"
        "{actions}\n\n"
        "Operating Cycle (fast reminder):\n"
        "1) Claim → 2) Sync → 3) Slice → 4) Execute → 5) Validate → 6) Commit → 7) Report evidence\n"
        "- No chat-only replies; status.json-only updates do NOT count as progress.\n"
        "- Report with artifact/validation/delegation in Discord.\n\n"
        "{discord_response_policy}\n"
        "{d2a_report_format}\n"
        "Devlog Command (for recipient):\n"
        "python tools/devlog_poster.py --agent {recipient} --file <devlog_path>\n"
        "Examples:\n"
        "  python tools/devlog_poster.py --agent Agent-1 --file agent_workspaces/Agent-1/devlogs/status.md\n"
        "  python tools/devlog_poster.py --agent Agent-7 --file devlogs/2025-12-26_status.md\n"
        "  python tools/devlog_poster.py --agent Agent-8 --file agent_workspaces/Agent-8/devlogs/DEVLOG_2025-12-26.md\n"
        "Note: Tool automatically truncates content >1900 chars for Discord. Full devlog saved in workspace.\n\n"
        "If clarification needed:\n"
        "{fallback}\n"
        "#DISCORD #D2A\n"
    ),
    # C2A: Captain-to-Agent
    MessageCategory.C2A: (
        "[HEADER] C2A CAPTAIN DIRECTIVE\n"
        "From: Captain Agent-4\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "Identity:\n"
        "You are {recipient}. Act as this agent for this directive.\n"
        "If you are not {recipient}, do NOT reply; forward to {recipient}.\n\n"
        "No-Ack Policy:\n"
        "- Do not send empty acknowledgments.\n"
        "- Respond with deliverable/evidence or 1 blocker (blocker + proposed fix + owner).\n\n"
        "{discord_reporting}\n"
        "Cycle Checklist:\n"
        "CYCLE START:\n"
        "- Check inbox (priority: D2A → C2A → A2A)\n"
        "- Check Contract System (--get-next-task)\n"
        "- Check Swarm Brain (use MCP: search_swarm_knowledge) for relevant patterns (advisory only)\n"
        "- Update status.json (status=ACTIVE, increment cycle_count)\n"
        "- Update FSM State\n"
        "- Review current mission\n"
        "DURING CYCLE:\n"
        "- Update status when phase changes\n"
        "- Update when tasks complete\n"
        "- Update if blocked\n"
        "CYCLE END:\n"
        "- Update completed_tasks\n"
        "- Update next_actions\n"
        "- Commit status.json to git\n"
        "- Create & post devlog automatically\n"
        "- Share learnings to Swarm Brain (advisory repository - see docs/governance/SWARM_BRAIN_POLICY.md)\n\n"
        "Task:\n{task}\n\n"
        "Context:\n{context}\n\n"
        "Operating Procedures (standard):\n"
        "- **Swarm Force Multiplier Assessment** (FIRST STEP):\n"
        "  - Is this task too large for one agent? (3+ cycles estimated?)\n"
        "  - Does it span multiple domains/expertise areas?\n"
        "  - Can it be parallelized across 2-8 agents?\n"
        "  - If YES: Use Swarm Coordination Protocol (see below)\n"
        "  - If NO: Proceed with bilateral coordination or solo execution\n\n"
        "- **Bilateral Coordination** (default for 2-agent tasks):\n"
        "  - Pair with your primary partner agent (domain expertise match)\n"
        "  - Send A2A coordination message with task breakdown\n"
        "  - Establish handoff points and integration checkpoints\n"
        "  - You own orchestration and final handoff to Captain\n"
        "  - Coordinate via status.json updates and A2A pings\n\n"
        "- **Swarm Assignment** (for 3+ agent tasks):\n"
        "  - Break down into 3-8 parallel sub-tasks\n"
        "  - Assign via messaging system (use --agent flag for each)\n"
        "  - Send all assignments simultaneously (parallel execution)\n"
        "  - Monitor via status.json and coordination messages\n\n"
        "- **State Scan** (before execution):\n"
        "  - Check relevant agent statuses for dependencies/overlap\n"
        "  - Check project state/SSOT for current truth, active blockers, and recent changes\n"
        "  - Identify available agents for coordination if needed\n\n"
        "- **Learnings → Swarm Brain**:\n"
        "  - If you discover a new pattern, fix, or rule, add a short Swarm Brain entry\n"
        "  - Document successful coordination patterns\n\n"
        "- **Scope guard**:\n"
        "  - If this touches >2 domains, use swarm coordination (break down + assign)\n"
        "  - Don't work alone on large multi-domain tasks\n\n"
        "- **No chatter**:\n"
        "  - No receipt message required\n"
        "  - Only message if blocked or when done with evidence\n"
        "  - Coordination messages should be actionable, not acknowledgments\n\n"
        "{swarm_coordination}\n"
        "{cycle_checklist}\n"
        "{discord_reporting}\n"
        "Deliverable:\n"
        "1) {deliverable}\n"
        "2) Coordination outputs / pings / handoffs\n"
        "3) Short status note (3 bullets max)\n\n"
        "Checkpoint:\n"
        "- {eta}\n\n"
        "Evidence format:\n"
        "- Artifact link/ID + last updated timestamp\n"
        "- Pings/handoffs with message IDs/channel refs\n"
        "- 3-bullet status\n\n"
        "Priority Behavior:\n"
        "- regular = next cycle\n"
        "- urgent = interrupt current slice if safe; otherwise finish current micro-task then switch\n\n"
        "If blocked:\n"
        "- Send 1 message with: blocker + proposed fix + what you need from Captain.\n"
        "How to respond:\n"
        "- When done: provide deliverable + evidence.\n"
    ),
    # A2A: Agent-to-Agent
    MessageCategory.A2A: (
        "[HEADER] A2A COORDINATION — BILATERAL SWARM COORDINATION\n"
        "From: {sender}\n"
        "To: {recipient}\n"
        "Priority: {priority}\n"
        "Message ID: {message_id}\n"
        "Timestamp: {timestamp}\n\n"
        "🐝 **COORDINATED SWARM REQUEST**:\n"
        "This is a bilateral coordination request to leverage swarm force multiplication.\n"
        "We're asking for your expertise to parallelize work and accelerate completion.\n\n"
        "**COORDINATION REQUEST**:\n{ask}\n\n"
        "**CONTEXT**:\n{context}\n\n"
        "**WHY THIS COORDINATION?**\n{coordination_rationale}\n\n"
        "**EXPECTED CONTRIBUTION**:\n{expected_contribution}\n\n"
        "**TIMING**:\n{coordination_timeline}\n\n"
        "**RESPONSE REQUIRED**:\n"
        "Reply within 30 minutes with acceptance/decline and proposed approach.\n\n"
        "**WHAT TO INCLUDE IN YOUR REPLY** (for ACCEPT responses):\n"
        "- **Proposed approach**: How you'll coordinate (your role + partner's role)\n"
        "- **Synergy identification**: How your capabilities complement your partner's\n"
        "- **Next steps**: Suggested initial coordination touchpoint or action item\n"
        "- **Relevant capabilities**: Brief list of your applicable skills\n"
        "- **Timeline**: When you can start and expected coordination sync time\n\n"
        "**REPLY FORMAT (MANDATORY)**:\n"
        "```\n"
        "A2A REPLY to {message_id}:\n"
        "✅ ACCEPT: [Proposed approach: your role + partner role. Synergy: how capabilities complement. Next steps: initial action. Capabilities: key skills. Timeline: start time + sync time] | ETA: [timeframe]\n"
        "OR\n"
        "❌ DECLINE: [reason] | Alternative: [suggested agent]\n"
        "```\n\n"
        "**REPLY COMMAND**:\n"
        "```bash\n"
        "python -m src.services.messaging_cli --agent {sender} \\\n"
        "  --message \"A2A REPLY to {message_id}: [your response]\" \\\n"
        "  --category a2a --sender Agent-X --tags coordination-reply\n"
        "```\n"
        "**IMPORTANT SENDER IDENTIFICATION**: \n"
        "- `--agent {sender}` = recipient (who you're replying to, shown above as 'From: {sender}')\n"
        "- `--sender Agent-X` = **YOU** (replace X with your agent number, e.g., `Agent-2` or `Agent-5`)\n"
        "- Always include `--sender Agent-X` so your response header shows your agent ID instead of defaulting to CAPTAIN\n\n"
        "**COORDINATION PRINCIPLES**:\n"
        "- 2 agents working in parallel > 1 agent working alone\n"
        "- Share context via status.json updates and A2A pings\n"
        "- Report progress to accelerate integration\n"
        "- **Be proactive**: Propose concrete next steps rather than 'standing by'\n"
        "- **Identify synergy**: Explain how your skills complement your partner's\n"
        "- **Suggest handoffs**: Propose coordination touchpoints or integration points\n\n"
        "If blocked: Send brief blocker description + proposed solution\n\n"
        "#A2A #BILATERAL-COORDINATION #SWARM-FORCE-MULTIPLIER\n"
    ),
}


def format_s2a_message(template_key: str, **kwargs: Any) -> str:
    """Helper to render an S2A template with operating cycle included."""
    templates = MESSAGE_TEMPLATES.get(MessageCategory.S2A, {})
    template = templates.get(template_key) or templates.get("CONTROL")
    kwargs.setdefault("operating_cycle", AGENT_OPERATING_CYCLE_TEXT)
    kwargs.setdefault("cycle_checklist", CYCLE_CHECKLIST_TEXT)
    kwargs.setdefault("discord_reporting", DISCORD_REPORTING_TEXT)
    return template.format(**kwargs)


__all__ = [
    "MESSAGE_TEMPLATES",
    "AGENT_OPERATING_CYCLE_TEXT",
    "CYCLE_CHECKLIST_TEXT",
    "DISCORD_REPORTING_TEXT",
    "D2A_RESPONSE_POLICY_TEXT",
    "D2A_REPORT_FORMAT_TEXT",
    "format_d2a_payload",
    "format_s2a_message",
]
