#!/usr/bin/env python3
"""
Comprehensive List of ALL Discord Commands and Controllers
===========================================================

Lists every single Discord command, controller, view, and integration.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

print("=" * 80)
print("COMPREHENSIVE DISCORD COMMANDS & CONTROLLERS LIST")
print("=" * 80)
print()

# ============================================================================
# UNIFIED DISCORD BOT COMMANDS (unified_discord_bot.py)
# ============================================================================
print("📦 UNIFIED DISCORD BOT COMMANDS (unified_discord_bot.py)")
print("-" * 80)
print("  !control (or !panel, !menu)")
print("    - Open main control panel with interactive buttons")
print()
print("  !gui")
print("    - Open messaging GUI interface")
print()
print("  !status")
print("    - View detailed swarm status")
print()
print("  !message <agent-id> <message>")
print("    - Send message to specific agent")
print()
print("  !broadcast <message>")
print("    - Broadcast message to all agents")
print()
print("  !help")
print("    - Show interactive help menu")
print()
print("  !shutdown (Admin only)")
print("    - Gracefully shutdown the bot (with confirmation)")
print()
print("  !restart (Admin only)")
print("    - Restart the Discord bot (with confirmation)")
print()
print("  [C2A] Agent-X format")
print("    - Send regular message using C2A format")
print()
print("  [D2A] Agent-X format")
print("    - Send urgent message using D2A format")
print()
print()

# ============================================================================
# MESSAGING COMMANDS (messaging_commands.py)
# ============================================================================
print("📨 MESSAGING COMMANDS (messaging_commands.py)")
print("-" * 80)
print("  !message_agent <agent-id> <message> [priority]")
print("    - Send message to specific agent with optional priority")
print()
print("  !agent_interact")
print("    - Interactive agent messaging interface")
print()
print("  !swarm_status")
print("    - View current swarm status")
print()
print("  !broadcast <message> [priority]")
print("    - Broadcast message to all agents with optional priority")
print()
print("  !agent_list")
print("    - List all available agents")
print()
print("  !agent <agent-name> <message>")
print("    - Send message to agent (C-057 format)")
print()
print("  !help_messaging")
print("    - Get help with messaging commands")
print()
print()

# ============================================================================
# SWARM SHOWCASE COMMANDS (swarm_showcase_commands.py)
# ============================================================================
print("🐝 SWARM SHOWCASE COMMANDS (swarm_showcase_commands.py)")
print("-" * 80)
print("  !swarm_tasks (or !tasks, !directives)")
print("    - Display all active tasks and directives dashboard")
print()
print("  !swarm_roadmap (or !roadmap, !plan)")
print("    - Show integration roadmap")
print()
print("  !swarm_excellence (or !excellence, !achievements)")
print("    - Showcase agent achievements")
print()
print("  !swarm_overview (or !overview, !dashboard)")
print("    - Complete swarm status and missions")
print()
print()

# ============================================================================
# GITHUB BOOK VIEWER COMMANDS (github_book_viewer.py)
# ============================================================================
print("📚 GITHUB BOOK VIEWER COMMANDS (github_book_viewer.py)")
print("-" * 80)
print("  !github_book [repo_num] (or !book, !repos)")
print("    - Interactive GitHub book viewer with navigation")
print("    - Start from beginning or jump to specific repo")
print()
print("  !goldmines (or !jackpots, !discoveries)")
print("    - Showcase all goldmine and jackpot discoveries")
print()
print("  !book_stats (or !book_progress, !repo_stats)")
print("    - Show GitHub book statistics and progress")
print()
print("  !book_search <keyword> (or !search_repos, !find_repo)")
print("    - Search repositories by keyword")
print()
print("  !book_filter [agent_id] (or !filter_repos, !repos_by_agent)")
print("    - Filter repositories by agent")
print()
print()

# ============================================================================
# WEBHOOK COMMANDS (webhook_commands.py) - Admin Only
# ============================================================================
print("🔗 WEBHOOK COMMANDS (webhook_commands.py) - Admin Only")
print("-" * 80)
print("  !create_webhook <channel> <webhook_name>")
print("    - Create webhook for specific channel")
print()
print("  !list_webhooks [channel]")
print("    - List all webhooks in server or specific channel")
print()
print("  !delete_webhook <webhook_id>")
print("    - Delete webhook by ID (with confirmation)")
print()
print("  !test_webhook <webhook_id>")
print("    - Test webhook by sending test message")
print()
print("  !webhook_info <webhook_id>")
print("    - Get detailed information about webhook")
print()
print()

# ============================================================================
# CONTROLLERS (Interactive Views)
# ============================================================================
print("🎛️ CONTROLLERS (Interactive Views)")
print("-" * 80)
print()
print("📨 MessagingControllerView (controllers/messaging_controller_view.py)")
print("    Features:")
print("    - Agent selector dropdown with live status")
print("    - Custom message entry modal")
print("    - Priority selection")
print("    - Broadcast quick access")
print("    - Jet Fuel message button")
print("    - Live status button")
print("    - Refresh agents button")
print()
print("📊 StatusControllerView (controllers/status_controller_view.py)")
print("    Features:")
print("    - Real-time agent status")
print("    - Points and mission tracking")
print("    - Live refresh capability")
print("    - Status filters (Active/Idle)")
print("    - Message idle agents button")
print()
print("📢 BroadcastControllerView (controllers/broadcast_controller_view.py)")
print("    Features:")
print("    - Broadcast to all agents")
print("    - Select specific agents")
print("    - Jet Fuel broadcast")
print("    - Broadcast templates")
print()
print("📋 BroadcastTemplatesView (controllers/broadcast_templates_view.py)")
print("    Features:")
print("    - Pre-defined broadcast templates")
print("    - Quick template selection")
print()
print()

# ============================================================================
# GUI COMPONENTS (discord_gui_*.py)
# ============================================================================
print("🖼️ GUI COMPONENTS (discord_gui_*.py)")
print("-" * 80)
print()
print("DiscordGUIController (discord_gui_controller.py)")
print("    - Main GUI controller facade")
print("    - Creates all GUI views and modals")
print()
print("AgentMessagingGUIView (discord_gui_views.py)")
print("    - Main messaging GUI view")
print("    - Agent selection dropdown")
print("    - Message composition")
print()
print("SwarmStatusGUIView (discord_gui_views.py)")
print("    - Swarm status monitoring view")
print()
print("HelpGUIView (discord_gui_views.py)")
print("    - Interactive help menu")
print()
print("MainControlPanelView (discord_gui_views.py)")
print("    - Main control panel with all features")
print()
print("AgentMessageModal (discord_gui_modals.py)")
print("    - Modal for messaging specific agent")
print()
print("BroadcastMessageModal (discord_gui_modals.py)")
print("    - Modal for broadcasting to all agents")
print()
print()

# ============================================================================
# INTEGRATIONS & SERVICES
# ============================================================================
print("🔌 INTEGRATIONS & SERVICES")
print("-" * 80)
print()
print("DebateDiscordPoster (debate_discord_integration.py)")
print("    - Posts agent debates to Discord")
print("    - Shows agent votes with attribution")
print("    - Posts debate status/results")
print()
print("ContractNotifier (contract_notifications.py)")
print("    - Real-time contract event notifications")
print("    - Contract assigned notifications")
print("    - Contract started notifications")
print("    - Contract completed notifications")
print()
print("DiscordAgentCommunication (discord_agent_communication.py)")
print("    - send_to_agent_inbox()")
print("    - broadcast_to_all_agents()")
print("    - send_human_prompt_to_captain()")
print("    - execute_agent_command()")
print()
print()

# ============================================================================
# SUMMARY
# ============================================================================
print("=" * 80)
print("SUMMARY")
print("=" * 80)
print()
print("Total Commands: ~30+")
print("  - Unified Bot: 8 commands")
print("  - Messaging: 7 commands")
print("  - Swarm Showcase: 4 commands")
print("  - GitHub Book: 5 commands")
print("  - Webhooks: 5 commands (admin)")
print()
print("Total Controllers/Views: 8+")
print("  - MessagingControllerView")
print("  - StatusControllerView")
print("  - BroadcastControllerView")
print("  - BroadcastTemplatesView")
print("  - AgentMessagingGUIView")
print("  - SwarmStatusGUIView")
print("  - HelpGUIView")
print("  - MainControlPanelView")
print()
print("Total Modals: 2")
print("  - AgentMessageModal")
print("  - BroadcastMessageModal")
print()
print("Total Integrations: 3")
print("  - DebateDiscordPoster")
print("  - ContractNotifier")
print("  - DiscordAgentCommunication")
print()
print("=" * 80)
print("All commands are case-insensitive")
print("GUI commands (!control, !gui) are preferred for ease of use")
print("=" * 80)

