#!/usr/bin/env python3
"""
OSRS Enums - Agent Cellphone V2
===============================

OSRS game enums and constants.
Follows V2 standards: ≤200 LOC, SRP, OOP principles.

Author: V2 SWARM CAPTAIN
License: MIT
"""

from enum import Enum


class OSRSSkill(Enum):
    """OSRS Skills"""
    ATTACK = "attack"
    STRENGTH = "strength"
    DEFENCE = "defence"
    HITPOINTS = "hitpoints"
    RANGED = "ranged"
    PRAYER = "prayer"
    MAGIC = "magic"
    COOKING = "cooking"
    WOODCUTTING = "woodcutting"
    FLETCHING = "fletching"
    FISHING = "fishing"
    FIREMAKING = "firemaking"
    CRAFTING = "crafting"
    SMITHING = "smithing"
    MINING = "mining"
    HERBLORE = "herblore"
    AGILITY = "agility"
    THIEVING = "thieving"
    SLAYER = "slayer"
    FARMING = "farming"
    RUNECRAFTING = "runecrafting"
    HUNTER = "hunter"
    CONSTRUCTION = "construction"


class OSRSLocation(Enum):
    """OSRS Game Locations - Enhanced with Dadudekc systems"""
    LUMBRIDGE = "lumbridge"
    VARROCK = "varrock"
    FALADOR = "falador"
    ARDOUGNE = "ardougne"
    CAMELOT = "camelot"
    YANILLE = "yanille"
    GRAND_EXCHANGE = "grand_exchange"
    BARBARIAN_VILLAGE = "barbarian_village"
    EDGEVILLE = "edgeville"
    DRAYNOR = "draynor"
    AL_KHARID = "al_kharid"
    TUTORIAL_ISLAND = "tutorial_island"
    WILDERNESS = "wilderness"
    CATHERBY = "catherby"
    SEERS_VILLAGE = "seers_village"
    PORT_PHASMATYS = "port_phasmatys"
    CANIFIS = "canifis"
    MORTON = "morton"
    BURGH_DE_ROTT = "burgh_de_rott"
    PISCATORIS = "piscatoris"
    OGRE_ENCLAVE = "ogre_enclave"
    GU_TANOTH = "gu_tanoth"
    TAI_BWO_WANNAI = "tai_bwo_wannai"
    SHILO_VILLAGE = "shilo_village"
    POLLNIVNEACH = "pollnivneach"
    SOPHANEM = "sophanem"
    ELIDINIS = "elidinis"
    MENAPHOS = "menaphos"
    SOPHANEM_DUNGEON = "sophanem_dungeon"
    KALPHITE_LAIR = "kalphite_lair"
    GOD_WARS_DUNGEON = "god_wars_dungeon"
    ABYSS = "abyss"
    RUNECRAFTING_ALTARS = "runecrafting_altars"


class OSRSGameState(Enum):
    """OSRS Game States"""
    IDLE = "idle"
    SKILLING = "skilling"
    COMBAT = "combat"
    QUESTING = "questing"
    TRADING = "trading"
    NAVIGATING = "navigating"
    INVENTORY_MANAGEMENT = "inventory_management"
    BANKING = "banking"
    SHOPPING = "shopping"
    CRAFTING = "crafting"
    SMITHING = "smithing"
    COOKING = "cooking"
    FISHING = "fishing"
    WOODCUTTING = "woodcutting"
    MINING = "mining"
    FARMING = "farming"
    THIEVING = "thieving"
    AGILITY = "agility"
    SLAYER = "slayer"
    RUNECRAFTING = "runecrafting"
    HUNTER = "hunter"
    CONSTRUCTION = "construction"
    MAGIC = "magic"
    PRAYER = "prayer"
    RANGED = "ranged"
    MELEE = "melee"
    DEFENCE = "defence"
    HITPOINTS = "hitpoints"
    STRENGTH = "strength"
    ATTACK = "attack"


class OSRSActionType(Enum):
    """OSRS Action Types"""
    SKILL_TRAINING = "skill_training"
    COMBAT = "combat"
    QUEST = "quest"
    TRADE = "trade"
    NAVIGATE = "navigate"
    INVENTORY_MANAGEMENT = "inventory_management"
    BANK = "bank"
    SHOP = "shop"
    CRAFT = "craft"
    SMITH = "smith"
    COOK = "cook"
    FISH = "fish"
    WOODCUT = "woodcut"
    MINE = "mine"
    FARM = "farm"
    THIEVE = "thieve"
    AGILITY = "agility"
    SLAYER = "slayer"
    RUNECRAFT = "runecraft"
    HUNT = "hunt"
    CONSTRUCT = "construct"
    CAST_SPELL = "cast_spell"
    PRAY = "pray"
    SHOOT = "shoot"
    ATTACK = "attack"
    DEFEND = "defend"
    HEAL = "heal"
    BUFF = "buff"
    DEBUFF = "debuff"
    SPECIAL_ATTACK = "special_attack"
    ULTIMATE_ABILITY = "ultimate_ability"
