#!/usr/bin/env python3
"""
Generate Coordination Handoff Message
Creates formatted message for Agent-4 with test results and Agent-7 handoff instructions.

Usage:
    python tools/generate_coordination_handoff_message.py [--results-file FILE]
    
Generates a ready-to-send message for Agent-4 coordination handoff.
"""

import json
import sys
import argparse
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent.parent


def load_latest_results():
    """Load latest test results file."""
    results_dir = PROJECT_ROOT / "agent_workspaces" / "Agent-1"
    result_files = sorted(results_dir.glob("trading_robot_phase3_fastapi_test_results_*.json"))
    
    if not result_files:
        return None
    
    with open(result_files[-1], 'r', encoding='utf-8') as f:
        return json.load(f)


def generate_handoff_message(results: dict) -> str:
    """Generate coordination handoff message."""
    timestamp = results.get("timestamp", datetime.now().isoformat())
    endpoint = results.get("endpoint", "http://localhost:8001")
    success = results.get("success", False)
    
    status = "✅ PASS" if success else "❌ FAIL"
    
    message = f"""🚀 FastAPI Integration Test Results - Coordination Handoff

**From:** Agent-1
**To:** Agent-4
**Timestamp:** {timestamp}
**Status:** {status}

## Test Execution Summary

- **Endpoint:** {endpoint}
- **Execution Time:** {timestamp}
- **Test Status:** {status}
"""
    
    # Extract test counts from stdout if available
    if "stdout" in results and results["stdout"]:
        stdout = results["stdout"]
        # Try to extract pytest summary
        if "passed" in stdout.lower():
            lines = stdout.split('\n')
            for line in lines:
                if "passed" in line.lower() or "failed" in line.lower():
                    message += f"- **Test Summary:** {line.strip()}\n"
                    break
    
    message += f"""
## Results for Agent-7 WordPress Verification

"""
    
    if success:
        message += """✅ FastAPI service is operational
✅ WordPress endpoints should now return 200:
   - `/wp-json/tradingrobotplug/v1/account`
   - `/wp-json/tradingrobotplug/v1/positions`

**Agent-7 Action Items:**
1. Verify `/wp-json/tradingrobotplug/v1/account` returns 200
2. Verify `/wp-json/tradingrobotplug/v1/positions` returns 200
3. Confirm FastAPI connection is working
"""
    else:
        message += """❌ FastAPI service not operational
⚠️  WordPress endpoints will return 500 until FastAPI is connected

**Agent-7 Action Items:**
- Wait for FastAPI service to be ready
- Retry verification after service is operational
"""
    
    message += """
## Next Steps

1. Agent-4 coordinates Agent-7 WordPress verification
2. Agent-7 verifies endpoints return 200
3. Agent-4 coordinates final validation

---
*Generated by Agent-1 FastAPI validation pipeline*
"""
    
    return message


def main():
    parser = argparse.ArgumentParser(description="Generate coordination handoff message")
    parser.add_argument("--results-file", help="Test results JSON file (auto-detects latest if not specified)")
    parser.add_argument("--output", help="Output file for message (prints to stdout if not specified)")
    args = parser.parse_args()
    
    # Load results
    if args.results_file:
        with open(args.results_file, 'r', encoding='utf-8') as f:
            results = json.load(f)
    else:
        results = load_latest_results()
        if not results:
            print("❌ No test results found. Run tests first or specify --results-file")
            sys.exit(1)
        print(f"📄 Using latest results file")
    
    # Generate message
    message = generate_handoff_message(results)
    
    # Output
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(message)
        print(f"📊 Handoff message saved to: {output_path}")
    else:
        print(message)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())

