#!/usr/bin/env python3
"""
Integration Health Checker - Swarm Productivity Tool
===================================================

Quick health check for integration work:
- Verifies tool availability
- Checks integration readiness
- Validates repository state
- Reports integration health

Author: Agent-2 (Architecture & Design Specialist)
Date: 2025-11-26
License: MIT
V2 Compliance: <400 lines
"""

import sys
from pathlib import Path
from typing import Dict, List, Tuple
import json


def check_tool_availability() -> Dict[str, bool]:
    """Check if integration tools are available."""
    tools_dir = Path("tools")
    required_tools = [
        "detect_venv_files.py",
        "enhanced_duplicate_detector.py",
        "pattern_analyzer.py",
        "check_integration_issues.py",
        "verify_integration_tools.py"
    ]
    
    results = {}
    for tool in required_tools:
        tool_path = tools_dir / tool
        results[tool] = tool_path.exists()
    
    return results


def check_documentation_availability() -> Dict[str, bool]:
    """Check if integration documentation is available."""
    docs_dir = Path("docs/integration")
    key_docs = [
        "INTEGRATION_QUICK_START.md",
        "STAGE1_INTEGRATION_METHODOLOGY.md",
        "INTEGRATION_BEST_PRACTICES.md",
        "INTEGRATION_PATTERNS_CATALOG.md",
        "TOOL_USAGE_GUIDE.md"
    ]
    
    results = {}
    for doc in key_docs:
        doc_path = docs_dir / doc
        results[doc] = doc_path.exists()
    
    return results


def check_repository_state(repo_path: Path) -> Dict[str, any]:
    """Check repository state for integration readiness."""
    results = {
        "exists": repo_path.exists(),
        "is_git_repo": False,
        "has_python_files": False,
        "has_tests": False,
        "has_venv_files": False,
        "has_duplicates": False
    }
    
    if not results["exists"]:
        return results
    
    # Check if git repo
    results["is_git_repo"] = (repo_path / ".git").exists()
    
    # Check for Python files
    python_files = list(repo_path.rglob("*.py"))
    results["has_python_files"] = len(python_files) > 0
    results["python_file_count"] = len(python_files)
    
    # Check for test files
    test_files = [f for f in python_files if "test" in f.name.lower()]
    results["has_tests"] = len(test_files) > 0
    results["test_file_count"] = len(test_files)
    
    # Quick check for venv files (common patterns)
    venv_patterns = ["site-packages", "venv", ".venv", "__pycache__"]
    results["has_venv_files"] = any(
        any(pattern in str(f) for pattern in venv_patterns)
        for f in repo_path.rglob("*")
    )
    
    return results


def generate_health_report(
    tools: Dict[str, bool],
    docs: Dict[str, bool],
    repo_state: Dict[str, any] = None
) -> str:
    """Generate health check report."""
    report = "# Integration Health Check Report\n\n"
    report += "**Date**: 2025-11-26\n"
    report += "**Generated By**: Agent-2 (Architecture & Design Specialist)\n\n"
    report += "---\n\n"
    
    # Tools section
    report += "## 🛠️ **Tools Availability**\n\n"
    tool_count = sum(1 for v in tools.values() if v)
    total_tools = len(tools)
    report += f"**Status**: {tool_count}/{total_tools} tools available\n\n"
    
    for tool, available in tools.items():
        status = "✅" if available else "❌"
        report += f"- {status} {tool}\n"
    
    report += "\n---\n\n"
    
    # Documentation section
    report += "## 📚 **Documentation Availability**\n\n"
    doc_count = sum(1 for v in docs.values() if v)
    total_docs = len(docs)
    report += f"**Status**: {doc_count}/{total_docs} key documents available\n\n"
    
    for doc, available in docs.items():
        status = "✅" if available else "❌"
        report += f"- {status} {doc}\n"
    
    report += "\n---\n\n"
    
    # Repository state section
    if repo_state:
        report += "## 📁 **Repository State**\n\n"
        if repo_state.get("exists"):
            report += f"- **Exists**: ✅\n"
            report += f"- **Git Repo**: {'✅' if repo_state.get('is_git_repo') else '❌'}\n"
            report += f"- **Python Files**: {'✅' if repo_state.get('has_python_files') else '❌'} ({repo_state.get('python_file_count', 0)} files)\n"
            report += f"- **Test Files**: {'✅' if repo_state.get('has_tests') else '❌'} ({repo_state.get('test_file_count', 0)} files)\n"
            report += f"- **Venv Files**: {'⚠️' if repo_state.get('has_venv_files') else '✅'}\n"
        else:
            report += "- **Exists**: ❌\n"
    
    report += "\n---\n\n"
    
    # Overall health
    tool_health = (tool_count / total_tools * 100) if total_tools > 0 else 0
    doc_health = (doc_count / total_docs * 100) if total_docs > 0 else 0
    
    overall_health = (tool_health + doc_health) / 2
    
    report += "## 🎯 **Overall Health**\n\n"
    report += f"- **Tools**: {tool_health:.1f}%\n"
    report += f"- **Documentation**: {doc_health:.1f}%\n"
    report += f"- **Overall**: {overall_health:.1f}%\n\n"
    
    if overall_health >= 90:
        report += "**Status**: 🟢 **Excellent** - Ready for integration work\n"
    elif overall_health >= 70:
        report += "**Status**: 🟡 **Good** - Minor gaps, ready for integration\n"
    elif overall_health >= 50:
        report += "**Status**: 🟠 **Fair** - Some gaps, review needed\n"
    else:
        report += "**Status**: 🔴 **Poor** - Significant gaps, setup needed\n"
    
    return report


def main():
    """Main execution."""
    print("=" * 60)
    print("🔍 INTEGRATION HEALTH CHECKER")
    print("=" * 60)
    print()
    
    # Check tools
    print("📊 Checking tools...")
    tools = check_tool_availability()
    tool_count = sum(1 for v in tools.values() if v)
    print(f"   ✅ {tool_count}/{len(tools)} tools available")
    print()
    
    # Check documentation
    print("📚 Checking documentation...")
    docs = check_documentation_availability()
    doc_count = sum(1 for v in docs.values() if v)
    print(f"   ✅ {doc_count}/{len(docs)} key documents available")
    print()
    
    # Check repository if provided
    repo_state = None
    if len(sys.argv) > 1:
        repo_path = Path(sys.argv[1])
        print(f"📁 Checking repository: {repo_path}")
        repo_state = check_repository_state(repo_path)
        print(f"   ✅ Repository check complete")
        print()
    
    # Generate report
    report = generate_health_report(tools, docs, repo_state)
    report_file = Path("integration_health_report.md")
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print("=" * 60)
    print("📊 SUMMARY")
    print("=" * 60)
    print(f"✅ Report saved to: {report_file}")
    print("=" * 60)


if __name__ == "__main__":
    main()

