#!/usr/bin/env python3
"""
Stage 1 Readiness Checker - Agent-7
====================================

Checks if repositories are ready for Stage 1 Step 4 (Repository Merging).
Verifies integration planning, duplicate resolution, venv cleanup, and integration review.

Author: Agent-7
Date: 2025-11-27
Priority: HIGH
V2 Compliance: ✅ (<400 lines)
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional

# Add project root to path
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))


def check_integration_planning(repo_name: str) -> bool:
    """Check if integration planning is complete."""
    planning_file = project_root / "agent_workspaces" / "Agent-7" / "INTEGRATION_PLANNING_PROGRESS.md"
    if not planning_file.exists():
        return False
    
    content = planning_file.read_text(encoding="utf-8")
    return repo_name in content and "Integration Plan" in content


def check_duplicate_resolution(repo_name: str) -> bool:
    """Check if duplicate resolution is complete."""
    # Check for enhanced duplicate detection reports
    report_file = project_root / "agent_workspaces" / "Agent-2" / f"{repo_name}_ENHANCED_DUPLICATES.md"
    return report_file.exists()


def check_venv_cleanup(repo_name: str) -> bool:
    """Check if venv cleanup is complete."""
    # Check integration checks results
    results_file = project_root / "agent_workspaces" / "Agent-7" / "integration_checks_results.json"
    if not results_file.exists():
        return False
    
    try:
        with open(results_file, 'r', encoding="utf-8") as f:
            results = json.load(f)
        
        for repo_data in results:
            if repo_data.get("repo") == repo_name:
                venv_check = repo_data.get("venv_check", {})
                output = venv_check.get("output", "")
                return "0" in output or "No virtual environment files detected" in output
    except Exception:
        pass
    
    return False


def check_integration_review(repo_name: str) -> bool:
    """Check if integration review is complete."""
    results_file = project_root / "agent_workspaces" / "Agent-7" / "integration_checks_results.json"
    if not results_file.exists():
        return False
    
    try:
        with open(results_file, 'r', encoding="utf-8") as f:
            results = json.load(f)
        
        for repo_data in results:
            if repo_data.get("repo") == repo_name:
                return repo_data.get("status") == "checked"
    except Exception:
        pass
    
    return False


def check_repo_readiness(repo_name: str) -> Dict[str, bool]:
    """Check all readiness criteria for a repository."""
    return {
        "integration_planning": check_integration_planning(repo_name),
        "duplicate_resolution": check_duplicate_resolution(repo_name),
        "venv_cleanup": check_venv_cleanup(repo_name),
        "integration_review": check_integration_review(repo_name)
    }


def generate_readiness_report(repos: List[str]) -> str:
    """Generate readiness report for multiple repositories."""
    report_lines = [
        "=" * 60,
        "📊 STAGE 1 READINESS CHECKER REPORT",
        "=" * 60,
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Generated by: Agent-7",
        "",
    ]
    
    all_ready = True
    
    for repo in repos:
        readiness = check_repo_readiness(repo)
        all_steps_complete = all(readiness.values())
        
        status = "✅ READY" if all_steps_complete else "⏳ NOT READY"
        all_ready = all_ready and all_steps_complete
        
        report_lines.extend([
            f"\n📦 {repo}",
            f"Status: {status}",
            f"  Step 3 (Integration Planning): {'✅' if readiness['integration_planning'] else '❌'}",
            f"  Step 5 (Duplicate Resolution): {'✅' if readiness['duplicate_resolution'] else '❌'}",
            f"  Step 6 (Venv Cleanup): {'✅' if readiness['venv_cleanup'] else '❌'}",
            f"  Step 7 (Integration Review): {'✅' if readiness['integration_review'] else '❌'}",
        ])
    
    report_lines.extend([
        "",
        "=" * 60,
        f"Overall Status: {'✅ ALL READY' if all_ready else '⏳ SOME NOT READY'}",
        "=" * 60,
    ])
    
    return "\n".join(report_lines)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python tools/stage1_readiness_checker.py <repo1> [repo2] ...")
        print("\nExample:")
        print("  python tools/stage1_readiness_checker.py FocusForge TBOWTactics Superpowered-TTRPG")
        sys.exit(1)
    
    repos = sys.argv[1:]
    report = generate_readiness_report(repos)
    print(report)
    
    # Save report
    report_file = project_root / "agent_workspaces" / "Agent-7" / f"STAGE1_READINESS_REPORT_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_file.write_text(report, encoding="utf-8")
    print(f"\n📄 Report saved to: {report_file}")


if __name__ == "__main__":
    main()







