#!/usr/bin/env python3
"""
⚠️  DEPRECATED: This script is deprecated and will be removed in a future version.

Please use the new modular implementation instead:
    python -m tools.cycle_accomplishments.main

The new implementation combines all features from v1.0 and v2.0 with:
- Better modular architecture
- Blog post generation (Victor voice)
- Enhanced Discord posting (chunked + file upload)
- Cross-platform compatibility (fixes hardcoded /workspace path)
- Protocol v2.0

This script will continue to work but is no longer maintained.
"""

import json
import os
import datetime
import re
import yaml
from pathlib import Path
import glob
import sys
import traceback

# Add project root to path to allow imports from src/tools
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

try:
    from tools.categories.communication_tools import DiscordRouterPoster
    DISCORD_AVAILABLE = True
except ImportError as e:
    print(f"⚠️  Could not import DiscordRouterPoster. Discord posting will be skipped.")
    print(f"   Error details: {e}")
    DISCORD_AVAILABLE = False
except Exception as e:
    print(f"⚠️  Unexpected error importing DiscordRouterPoster: {e}")
    import traceback
    traceback.print_exc()
    DISCORD_AVAILABLE = False

def load_voice_profile():
    """Load Victor's voice profile."""
    profile_path = project_root / "config" / "voice_profiles" / "victor_voice_profile.yaml"
    if profile_path.exists():
        try:
            with open(profile_path, 'r') as f:
                return yaml.safe_load(f)
        except Exception as e:
            print(f"⚠️ Error loading voice profile: {e}")
    return None

def apply_victor_voice(text, profile, mode='narrative'):
    """
    Apply Victor's voice rules heuristically.
    
    Mode: 'narrative' (blog) or 'operational' (report)
    """
    if not profile:
        return text.lower() # Basic fallback
        
    rules = profile.get('voice_profile', {}).get('modes', {}).get(mode, {}).get('rules', {})
    lexicon = profile.get('voice_profile', {}).get('lexicon', {})
    
    # 1. Lowercase (mostly)
    if rules.get('casing') == 'mostly lowercase':
        # Split into lines to preserve some structure
        lines = text.split('\n')
        processed_lines = []
        for line in lines:
            # Keep report metadata keys capitalized-ish if needed, but for blog we want lower
            processed_lines.append(line.lower())
        text = '\n'.join(processed_lines)

    # 2. Remove Bullets
    if not rules.get('use_bullets', True):
        # Replace bullets with just newlines or simple breaks
        text = re.sub(r'^\s*-\s+', '', text, flags=re.MULTILINE)
        
    # 3. Formatting removal (Markdown headers to text)
    if mode == 'narrative':
        text = re.sub(r'^#+\s+', '', text, flags=re.MULTILINE)
        text = text.replace('**', '') # Remove bold
        
    # 4. Lexicon Swaps
    avoid = lexicon.get('avoid_terms', [])
    
    replacements = {
        "completed tasks": "shipped items",
        "achievements": "wins",
        "active tasks": "building",
        "current mission": "current focus",
        "status:": "state:",
        "priority:": "level:",
        "in progress": "building",
        "generated by": "signal from",
        "total agents": "swarm size",
    }
    
    for old, new in replacements.items():
        text = text.replace(old, new)
        
    # 5. Structure adjustment (Narrative flow)
    if mode == 'narrative':
        # Compact multiple newlines
        text = re.sub(r'\n{3,}', '\n\n', text)
    
    return text

def generate_narrative_blog_content(agents_data, total_completed, total_achievements, active_agents, date_str):
    """Generate the blog post content using Victor's narrative voice."""
    
    profile = load_voice_profile()
    
    # Intro
    content = f"cycle report for {date_str}.\n"
    content += f"swarm size: {active_agents}.\n"
    content += f"shipped items: {total_completed}.\n"
    content += f"wins: {total_achievements}.\n\n"
    
    content += "here is the signal.\n\n"
    
    for data in agents_data:
        agent_id = data.get("agent_id", "unknown").lower()
        agent_name = data.get("agent_name", "unknown").lower()
        mission = data.get("current_mission", "no mission").lower()
        
        content += f"{agent_id} ({agent_name})\n"
        content += f"focus: {mission}\n\n"
        
        # Completed (Narrative style: just list them simply)
        completed = data.get("completed_tasks", [])
        if completed:
            content += "shipped:\n"
            for task in completed[-5:]: # Top 5 only for blog to keep it tight
                if isinstance(task, str):
                    task_text = task
                elif isinstance(task, dict):
                    task_text = task.get("task", "")
                
                # clean up task text
                task_text = task_text.lower().replace('complete', '').replace('✅', '').strip()
                if task_text:
                    content += f"{task_text}\n"
            content += "\n"
            
        # Achievements
        achievements = data.get("achievements", [])
        if achievements:
            content += "wins:\n"
            for ach in achievements[-3:]:
                if isinstance(ach, str):
                    ach_text = ach
                elif isinstance(ach, dict):
                    ach_text = ach.get("title", "")
                
                ach_text = ach_text.lower().strip()
                if ach_text:
                    content += f"{ach_text}\n"
            content += "\n"
            
        content += "\n"
        
    content += "closure.\n"
    content += "victor.\n"
    
    return content

def generate_report():
    workspace_root = Path("/workspace")
    agent_workspaces = workspace_root / "agent_workspaces"
    
    agents_data = []
    
    total_completed_tasks = 0
    total_achievements = 0
    active_agents = 0
    
    print("Collecting data from agent workspaces...")
    
    # Process Agent 1-8
    for i in range(1, 9):
        agent_id = f"Agent-{i}"
        status_file = agent_workspaces / agent_id / "status.json"
        
        if status_file.exists():
            try:
                with open(status_file, 'r') as f:
                    data = json.load(f)
                    
                agents_data.append(data)
                
                # Count stats
                completed = data.get("completed_tasks", [])
                total_completed_tasks += len(completed)
                
                # Achievements might be in 'achievements'
                achievements = data.get("achievements", [])
                total_achievements += len(achievements)
                
                status = data.get("status", "")
                if "ACTIVE" in status:
                    active_agents += 1
                    
            except Exception as e:
                print(f"Error reading {status_file}: {e}")
        else:
            print(f"Warning: Status file not found for {agent_id}")
                
    # Generate Markdown
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    filename_ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    
    report_content = f"""# Cycle Accomplishments Report

**Generated:** {timestamp}
**Date:** {date_str}
**Agents:** {active_agents}

---

## Summary

**Total Agents:** {active_agents}
**Total Completed Tasks:** {total_completed_tasks}
**Total Achievements:** {total_achievements}

---
"""

    for data in agents_data:
        agent_id = data.get("agent_id", "Unknown")
        agent_name = data.get("agent_name", "Unknown")
        status = data.get("status", "Unknown")
        last_updated = data.get("last_updated", "Unknown")
        priority = data.get("mission_priority", data.get("priority", "Normal"))
        
        report_content += f"\n## {agent_id}: {agent_name}\n\n"
        report_content += f"**Status:** {status}  \n"
        report_content += f"**Priority:** {priority}  \n"
        report_content += f"**Last Updated:** {last_updated}\n\n"
        
        # Current Mission
        current_mission = data.get("current_mission", "No mission set.")
        report_content += f"### Current Mission\n{current_mission}\n\n"
        
        # Completed Tasks
        completed = data.get("completed_tasks", [])
        if isinstance(completed, list) and completed:
            report_content += f"### Completed Tasks ({len(completed)})\n"
            for task in completed[-20:]: # Last 20
                 # Task can be string or dict
                if isinstance(task, str):
                    report_content += f"- {task}\n"
                elif isinstance(task, dict):
                    task_desc = task.get("task", "Unknown Task")
                    details = task.get("details", "")
                    if details:
                        report_content += f"- {task_desc}: {details}\n"
                    else:
                        report_content += f"- {task_desc}\n"
            report_content += "\n"

        # Recent completions (sometimes used instead of completed_tasks for objects)
        recent = data.get("recent_completions", [])
        if recent and not completed: # Fallback if completed_tasks is empty but recent exists
             report_content += f"### Recent Completions ({len(recent)})\n"
             for task in recent[-20:]:
                if isinstance(task, dict):
                    task_desc = task.get("task", "Unknown Task")
                    details = task.get("details", "")
                    if details:
                         report_content += f"- {task_desc}: {details}\n"
                    else:
                         report_content += f"- {task_desc}\n"
                elif isinstance(task, str):
                    report_content += f"- {task}\n"
             report_content += "\n"


        # Achievements
        achievements = data.get("achievements", [])
        if achievements:
            report_content += f"### Achievements ({len(achievements)})\n"
            for ach in achievements[-15:]:
                if isinstance(ach, str):
                    report_content += f"- {ach}\n"
                elif isinstance(ach, dict):
                     # Extract title or description
                     title = ach.get("title", ach.get("description", str(ach)))
                     report_content += f"- {title}\n"
            report_content += "\n"
            
        # Active Tasks
        active = data.get("current_tasks", [])
        if active:
            report_content += f"### Active Tasks ({len(active)})\n"
            for task in active[-10:]:
                if isinstance(task, str):
                    report_content += f"- {task}\n"
                elif isinstance(task, dict):
                    task_desc = task.get("task", "Unknown Task")
                    report_content += f"- {task_desc}\n"
            report_content += "\n"
            
        report_content += "---\n"
        
    report_content += """
## Report Metadata

**Generated By:** Unified Cycle Accomplishments Report Generator
**Protocol:** CYCLE_ACCOMPLISHMENTS_REPORT_GENERATION v2.0
**Format:** Markdown
"""

    # Generate Blog Content (Victor Narrative Voice)
    blog_content_body = generate_narrative_blog_content(
        agents_data, total_completed_tasks, total_achievements, active_agents, date_str
    )

    # Save to docs/blog for autoblogger
    blog_dir = workspace_root / "docs" / "blog"
    blog_dir.mkdir(parents=True, exist_ok=True)
    
    blog_filename = f"cycle_accomplishments_{date_str}.md"
    blog_path = blog_dir / blog_filename
    
    # Create blog-friendly content with Frontmatter
    blog_final_content = f"""---
title: "cycle report: {date_str}"
date: {date_str}
author: victor
category: devlog
tags: [swarm, cycle-report, build-in-public]
excerpt: "swarm size: {active_agents}. shipped: {total_completed_tasks}. the signal."
---

{blog_content_body}
"""
    
    try:
        with open(blog_path, 'w') as f:
            f.write(blog_final_content)
        print(f"Blog post ready (Victor Voice): {blog_path}")
    except Exception as e:
        print(f"Error writing blog post: {e}")

    report_dir = workspace_root / "reports"
    report_dir.mkdir(exist_ok=True)
    report_path = report_dir / f"cycle_accomplishments_{filename_ts}.md"
    
    try:
        with open(report_path, 'w') as f:
            f.write(report_content)
        print(f"Report generated: {report_path}")
        
        # Post to Discord
        if DISCORD_AVAILABLE:
            print("Posting report to Discord (chunked + full file)...")
            try:
                poster = DiscordRouterPoster(agent_id="Agent-4")
                
                # 1. Post Summary
                summary_msg = f"""**Cycle Accomplishments Report**
**Date:** {date_str}
**Agents:** {active_agents}
**Tasks:** {total_completed_tasks} | **Achievements:** {total_achievements}

*Full report generated at: `reports/{report_path.name}`*
"""
                poster.post_update(
                    agent_id="Agent-4", 
                    message=summary_msg, 
                    title="📊 Cycle Report Summary", 
                    priority="normal"
                )

                # 2. Post per-agent details (chunked for readability)
                for data in agents_data:
                    agent_id = data.get("agent_id", "Unknown")
                    agent_name = data.get("agent_name", "Unknown")
                    
                    # Construct Agent Message
                    MAX_CHUNK_SIZE = 1600
                    
                    # Header stats
                    status = data.get("status", "Unknown")
                    priority = data.get("mission_priority", data.get("priority", "Normal"))
                    current_mission = data.get("current_mission", "No mission set.")
                    
                    # Start first chunk
                    agent_msg = f"**Status:** {status} | **Priority:** {priority}\n"
                    agent_msg += f"**Mission:** {current_mission}\n\n"
                    
                    # Completed Tasks
                    completed = data.get("completed_tasks", [])
                    if completed:
                        agent_msg += f"**Completed ({len(completed)}):**\n"
                        for task in completed: 
                            task_str = ""
                            if isinstance(task, str):
                                task_str = f"- {task}\n"
                            elif isinstance(task, dict):
                                task_desc = task.get("task", "Unknown")
                                details = task.get("details", "")
                                if details:
                                    task_str = f"- {task_desc}: {details}\n"
                                else:
                                    task_str = f"- {task_desc}\n"
                            
                            if len(agent_msg) + len(task_str) > MAX_CHUNK_SIZE:
                                poster.post_update(agent_id="Agent-4", message=agent_msg, title=f"📄 {agent_id}: {agent_name}", priority="normal")
                                agent_msg = f"**{agent_id} (Continued):**\n"
                            
                            agent_msg += task_str
                        agent_msg += "\n"

                    # Achievements
                    achievements = data.get("achievements", [])
                    if achievements:
                        agent_msg += f"**Achievements ({len(achievements)}):**\n"
                        for ach in achievements:
                            ach_str = ""
                            if isinstance(ach, str):
                                ach_str = f"- {ach}\n"
                            elif isinstance(ach, dict):
                                title = ach.get("title", ach.get("description", str(ach)))
                                ach_str = f"- {title}\n"
                            
                            if len(agent_msg) + len(ach_str) > MAX_CHUNK_SIZE:
                                poster.post_update(agent_id="Agent-4", message=agent_msg, title=f"📄 {agent_id}: {agent_name}", priority="normal")
                                agent_msg = f"**{agent_id} (Continued):**\n"
                            
                            agent_msg += ach_str
                            
                    # Active Tasks
                    active = data.get("current_tasks", [])
                    if active:
                         agent_msg += f"**Active Tasks ({len(active)}):**\n"
                         for task in active[:10]:
                            task_str = ""
                            if isinstance(task, str):
                                task_str = f"- {task}\n"
                            elif isinstance(task, dict):
                                task_desc = task.get("task", "Unknown Task")
                                task_str = f"- {task_desc}\n"
                            
                            if len(agent_msg) + len(task_str) > MAX_CHUNK_SIZE:
                                poster.post_update(agent_id="Agent-4", message=agent_msg, title=f"📄 {agent_id}: {agent_name}", priority="normal")
                                agent_msg = f"**{agent_id} (Continued):**\n"
                            
                            agent_msg += task_str
                    
                    if agent_msg:
                        poster.post_update(agent_id="Agent-4", message=agent_msg, title=f"📄 {agent_id}: {agent_name}", priority="normal")

                # 3. Upload Full Report File
                print("Uploading full report file...")
                poster.post_update(
                    agent_id="Agent-4",
                    message="📎 **Full Cycle Accomplishments Report (Attached)**",
                    title="📊 Full Report Download",
                    priority="normal",
                    file_path=str(report_path)
                )

            except Exception as e:
                print(f"⚠️ Error posting to Discord: {e}")
                import traceback
                traceback.print_exc()
        else:
            print("ℹ️ Discord posting skipped (module not available)")
            
    except Exception as e:
        print(f"Error writing report: {e}")

if __name__ == "__main__":
    generate_report()
